### ISSUE TITLE
Consolidate documentation

### ISSUE THREAD

**Issue by DanHickstein** [PyAbel/PyAbel#107]
@PyAbel/developers:

There is a potential for overlapping documentation about the general properties of PyAbel. The information is potentially contained in 3 places:
1. The readme file displayed at https://github.com/PyAbel/PyAbel
2. The home page of the wiki: https://github.com/PyAbel/PyAbel/wiki
3. There should be some general information on the main readthedocs.org page: https://pyabel.readthedocs.org/en/latest/index.html

I have a proposal: basically we just use the README as the main central source of information. It's already the main thing people see on the GitHub page and we can make it appear on the readthedocs page. Also, it has a whole git history so that we can track the changes that are being made to it better than we can with the wiki. 

So, we need to do a few things:

1. Change the readme from .md to .rst to allow compatibility with Sphinx. I did this and it seems to work fine. You can see it here: https://github.com/DanHickstein/PyAbel/tree/doc_improvements  (I also updated it quite a bit, so let me know if there are changed you would like to see.)

2. Link the readme to the Sphinx docs. I think that this works reasonably well: http://pyabel-dh-fork.readthedocs.org/en/latest/readme_link.html

3. I don't know quite what to do for the wiki. I think the best it to just have the "Home" page on the wiki link back to the README.rst. The other pages of the wiki are still pretty useful as an easy place to host out notes about the transform methods. Alternatively we could just get rid of the wiki and move towards hosting the technical information about the transform methods in the actual documentation that will appear on readthedocs. 

Thoughts?

I can make a PR for this soon, but wanted to get your thoughts first.

**Comment by DanHickstein** [comment]
By the way, does the @PyAbel/developers tag actually work to tag @rth, @DhrubajyotiDas, @stggh, and @ldes89150?

**Comment by stggh** [comment]
The developer tag works for me, I received this issue. For my commenting was not sure "@ldes89150" was on the list.

**Comment by stggh** [comment]
I love that `READMR.rst`!

Is it possible not display the full url link address?

Dump the wiki. It's a pain to set up (all images must be covertly linked to a pseudo github issue), and maintain.

**Comment by DhrubajyotiDas** [comment]
I got the notification, but I think I'm signed up to receive all updates to PyAbel so I'm not sure if my anecdote is data. 

I have no strong  opinions about the wiki, as long as the content is preserved somewhere and easy to find. If the wiki implies redundant effort then we can abandon it and keep a well maintained Readme.

**Comment by DanHickstein** [comment]
I wasn't planning to dump the whole wiki at this point, just the "Home" page that duplicates the readme. Let's keep the general information about each transform there (for now) on the relevant pages. In the long run, we should likely migrate this information to the `/doc` directory. I think that it's actually pretty easy to include new `.rst` documents here and link them using the `/doc/index.rst`. Each transform could have it's own `<method>.rst` file, and I think that the figures could easily be included in a sub-directory. So, perhaps that's the better long-term solution.

If anybody feels like making the first attempt at migrating one of the transform documents, please feel free to do so.

@stggh, I can get rid of the full URLs. At first I could not figure out how to do short URLs in `.rst` format, but I figured it out. It's weird:
```rst
`link text <http://www.etc.etc.etc.etc>`_
```

**Comment by ldes89150** [comment]
I think @PyAbel/developers doesn't work on me. However, I subscribe this project, so every issues come into my mail box.

Perhaps, I can add some examples related to cold atoms. :)

**Comment by DanHickstein** [comment]
@ldes89150: I invited you to the team :)

And yes, an example relating to cold atoms would be excellent! If you have some pretty data that would be fabulous.

Currently the examples are outdated and overlapping and we need to clean them up a bit. Not bad to have lots of examples, but each should try to highlight a different aspect of PyAbel or specific application.

**Comment by DanHickstein** [comment]
I moved all the information on the transforms from the wiki to `docs/transform_methods`. Proofreading is still needed, but I'm declaring victory here.
