### ISSUE TITLE
Add continous integration and simplify deployement

### ISSUE THREAD

**Issue by rth** [PyAbel/PyAbel#11]
- Add setup to automatically run unit tests with Travis CI on every commit pushed to github
- Check that the package can be installed with,
     
          pip install git+https://github.com/PyAbel/PyAbel.git

   meaning that the dependencies are checked for.

-  Make sure unit tests pass for Python 2.7 and 3.3-3.5 (standard range at present)
-  Verify that unit tests run on Windows, Mac and Linux  (using anaconda in all cases)

**Comment by DanHickstein** [comment]
This seems like a great idea! 

It's pushing the limits of what I know how to do. Do I need to activate the Travis CI part?

**Comment by rth** [comment]
Yeah, I'll create a pull request later today with more details.

**Comment by DanHickstein** [comment]
Great. Thanks!

**Comment by DanHickstein** [comment]
I activated Travis CI for this repo, so it should try to run the tests as soon as we include a .travis.yml file and commit.
