### ISSUE TITLE
Move abel.benchmark.py to the tools directory?

### ISSUE THREAD

**Issue by stggh** [PyAbel/PyAbel#113]
I there a reason that `abel.benchmark.py` remains in the main `abel`directory with all the transform methods? It may be more at home in the (subsequently created) `tools`  directory, since it is used by the unit testing functions. However, my attempt to move it caused all sorts of dependency issues, in `__init__.py` that someone more knowledgeable, and skilled, may be better placed to resolve. I am looking at you @DanHickstein.

**Comment by DanHickstein** [comment]
I don't object to moving it, but it's going to be a bit tedious and perhaps not worth your time at this point.

You would need to remove the line ``from . import benchmark`` from `__init__.py`...

**Comment by DanHickstein** [comment]
I'll close this for now. You can re-open if you feel that this is something that we should do.
