### ISSUE TITLE
Should we recast all input arrays to float64?

### ISSUE THREAD

**Issue by DanHickstein** [PyAbel/PyAbel#117]
I was having some weird issues this morning with the `example_hansenlaw_Xe.py`. The output were negative and I could not figure out what was going on for a long time. Then I realized that the data was being read from the image as `unit16`. During the transform, it was apparently overflowing to negative values. This seems like it might happen frequently with users loading images.

We could probably make some argument about trying to preserve the bit depth of the users image, but I think that the best thing for us to do is to recast all input images to float64 and move on with out lives. If the users want to save their data, they will need to recast to whatever bit depth they wish to save the images. 

For now, I'm going to add another kwarg to the `abel.transform` function: `recast_as_float64=True`. That seems like the safest thing to do for now. 

Any other ideas? @PyAbel/developers

**Comment by stggh** [comment]
@DanHickstein good catch. The Abel transform for Xe had me puzzled. 

Note (for the record) that the inverse Abel transform may, and should, produce negative values, particularly, near the image center (line). Such values are just an over correction, but essential to obtain full the correct inversion profile. The old `basex.exe` forced positive image values, incorrectly truncating the image inversion.

**Comment by DanHickstein** [comment]
Good point @stggh. In this case, almost all of the values were negative, so I knew something must be wrong :)

**Comment by DanHickstein** [comment]
So, I think that the current solution of casting to `float64` in `abel.transform()` should take care of most users. Probably this issue will pop up again when someone tried to run one of the individual transforms methods with other data. One option would be for the individual methods to print a warning of the datatype is not `float`. I'll close this for now.
