### ISSUE TITLE
Error and other messaging

### ISSUE THREAD

**Issue by stggh** [PyAbel/PyAbel#121]
Currently the Abel transforms write messages, usually in the `verbose=True` mode, to the console. This is not ideal. e.g. the GUI has no way of knowing that a method has failed.

I propose that we adopt the [scipy.optimize.minimize()](http://docs.scipy.org/doc/scipy-0.16.1/reference/generated/scipy.optimize.minimize.html) approach and return `results['success'], results['status'], and results['message']`. This fits in with the `dict` return for `abel.transform()` but requires change to the return type, from `ndarray` to `dict` of each of the `abel.<method>.<method>_transform()` methods.

**Comment by DanHickstein** [comment]
I'm not sure what it means for a transform method to fail. Typically, doesn't a failure amount to returning a nonsense transform?

**Comment by stggh** [comment]
e.g.: passing invalid parameters `direction=forward` to those transforms that do not have that functionality.

**Comment by DanHickstein** [comment]
Currently passing an unimplemented direction is raising an exception, so shouldn't that also notify the GUI somehow?

**Comment by stggh** [comment]
Good point. Perhaps, no changes need be made to `abel.<method>_transform()` but something could be added to `abel.transform()`.

**Comment by DanHickstein** [comment]
You would rather have `abel.transform()` raise an exception than the `abel.<method>_transform()` functions? This was the actually the previous behavior, but when you switched to using 
``` python
    abel_transform = {\
      "basex" : abel.basex.basex_transform,
      "direct" : abel.direct.direct_transform,
      "hansenlaw" : abel.hansenlaw.hansenlaw_transform,
      "three_point" : abel.three_point.three_point_transform,
    }
```
rather than the `if`/`elif` statements I think that you removed this functionality. To me, is doesn't make a different which function raises the exception. The result is the same for the user...

**Comment by stggh** [comment]
@DanHickstein logic is in good form today. I agree the core methods should raise the exceptions. Let us consider the centering functions, in `abel/tools/center.py`, the many different methods here, including `scipy.optimize` and `scipy.ndimage` may have something worth knowing, that at the moment is lost in the void and inaccessible.

**Comment by DanHickstein** [comment]
So, you're saying that we should have some mechanism to pass messages from the output of scipy.optimize back up the food change so that users can see them in the `dict` output of `abel.transform()`? Sounds okay in principle, but seems like a nightmare to code. 

Is there is a specific example of something that we should be making the user aware of?

**Comment by stggh** [comment]
I am possibly not clear in my own head what is required:

1. The initial idea was that the information printed by `verbose=True` messages e.g. `center.py` `"Center of mass at ({0}, {1})".format(center[0], center[1])` is available for display by a GUI.

2. The second idea, is that more detailed information about the least-squares fitting is available. The extra dictionary elements are only, as per the `scipy.optimize.minimize()`, `results['success']`, `'status'`, and `'message'`. They may be populated as required. 

The downside is that a `dict` must be returned, e.g. by `find_center` perhaps, this is too much of a change.

**Comment by DanHickstein** [comment]
In general, I'd like to move away from the model of using "verbose" and having PyAbel print statements to the terminal. These are nice for debugging by developers, but they are fairly useless for most users, and create issues like the ones that you are experiencing. You don't see Scipy, Numpy, Matplotlib, etc. functions printing anything to the terminal. They either issue warnings or raise exceptions. 

In the case of getting the center, it seems like the GUI should call the "find_center" function itself and call `abel.transform(IM, center='none')`. (`center='none'` is actually the default, so just calling `abel.transform()` should be fine).

As far as getting the information from the `scipy.optimize.minimize()` function, we should probably just have the `find_image_center_by_slice()` function raise a RuntimeError if `fit['success']==False`. The test of the RuntimeError can contain `fit['message']`. This error could be caught by the GUI and displayed to the user in some way. 

I think that it's better for the  `find_image_center_by_slice()` to throw an error if it cannot find the center. It's better for it to fail obviously than to silently fail to find the center.

**Comment by stggh** [comment]
Sounds good. I agree.

**Comment by DanHickstein** [comment]
Okay, I will leave this open to remind us to change the behavior of `find_image_center_by_slice` to raise an exception rather than just print things.

**Comment by DanHickstein** [comment]
The exception behavior is added in: https://github.com/PyAbel/PyAbel/pull/132
