### ISSUE TITLE
Appveyor 64-bit build not working

### ISSUE THREAD

**Issue by DanHickstein** [PyAbel/PyAbel#125]
This seems like something related to the Cython direct Abel implementation. I turned off the 64-bit Appveyor build because I was tired of seeing the red X next to all of the PRs. 

If @rth has time, he should look into this.

**Comment by rth** [comment]
Sorry everybody, just saw this now. 
@DhrubajyotiDas  Does your PR above fixes the problem (by disabling the 64 bit version which is problematic)?

**Comment by rth** [comment]
Should be fixed in PR #188 .
