### ISSUE TITLE
Docs to-do list

### ISSUE THREAD

**Issue by DanHickstein** [PyAbel/PyAbel#133]
A few things that I didn't have time to take care of in https://github.com/PyAbel/PyAbel/pull/132:

`Abel.tools.analytical` has several functions that are missing docstrings. Maybe @DhrubajyotiDas can add some?

`abel.tools.vmi.anisotropy_parameter` needs math typeset in `:math:` format. Can @stggh do this?

**Comment by stggh** [comment]
Ok. Note, #131 should preferably be merged before I hack away.

**Comment by DanHickstein** [comment]
Sounds good. I can merge #131 soon, but you and @DhrubajyotiDas should take a look first, since I made a whole heap of changes (some of them at 2 AM), and there are probably some typos.

**Comment by DhrubajyotiDas** [comment]
@DanHickstein I'll see what I can do about the `tools.analytical` docstrings.

**Comment by DanHickstein** [comment]
If it makes it easier, you can probably go ahead and merge #132, since you've read through it.

**Comment by stggh** [comment]
Updating the docs has been causing me a few headaches, delays,  because:
1. The docs do not build on my (at work). system. Napoleon appears to be a ubuntu issue(?).
   ```
    [etalon:.+/VMI/PyAbel/doc]$ make html
    sphinx-build -b html -d _build/doctrees   . _build/html
    Running Sphinx v1.2.3

    Extension error:
    Could not import extension sphinx.ext.napoleon (exception: No module named napoleon) 
    Makefile:58: recipe for target 'html' failed
    make: *** [html] Error 1
```

2. `restview` (on my system) does not correctly render display math (LaTeX), the integrall symbol is tiny, and appears to totally ignore the inline :math: `f(r) = ` etc.

3. I would like to format  1/2 width text + 1/2 width image, but this has also proven difficult. This is to replace the first image currently used in `hansenlaw.rst`.

I think for items 1. and 2. I can assume that the processing will (eventually) work correctly. 3. Is a matter of familiarity with sphinx/restructuredtext.

**Comment by DanHickstein** [comment]
A few quick ideas (typing in my phone):

Is Napoleon installed? You need to pip install it per the instructions in
contributing.rst.

Are you using the back ticks after :math:?

I think that you can use :align: right or something like that to shift the
images. The image in readme.rst might be a good example.

On Thursday, March 3, 2016, Steve Gibson <notifications@github.com> wrote:

> Updating the docs has been causing me a few headaches, delays, because:
> 1. The docs do not build on my (at work). system. Napoleon appears to be a
> ubuntu issue(?).
>
>     [etalon:.+/VMI/PyAbel/doc]$ make html
>     sphinx-build -b html -d _build/doctrees   . _build/html
>     Running Sphinx v1.2.3
>
>     Extension error:
>     Could not import extension sphinx.ext.napoleon (exception: No module named napoleon)
>     Makefile:58: recipe for target 'html' failed
>     make: *** [html] Error 1
>
>
>    1.
>
>    restview (on my system) does not correctly render display math
>    (LaTeX), the integrall symbol is tiny, and appears to totally ignore the
>    inline :math: f(r) = etc.
>    2.
>
>    I would like to format 1/2 width text + 1/2 width image, but this has
>    also proven difficult. This is to replace the first image currently used in
>    hansenlaw.rst.
>
> I think for items 1. and 2. I can assume that the processing will
> (eventually) work correctly. 3. Is a matter of familiarity with
> sphinx/restructuredtext.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PyAbel/PyAbel/issues/133#issuecomment-191967063>.
>


-- 
Daniel D. Hickstein
DanHickstein@gmail.com
Phone: 301 787 1853

**Comment by DanHickstein** [comment]
Another idea:

It's pretty easy to make an account on readthedocs.org and set up a build for your branch of the docs. The only trick is that you need to go into settings and check the boxes about "Install in a virtualenv" and "allow access to site packages". 

Then, whenever you push to your branch, you will see the result on readthedocs.org. 

This option actually catches more issues than building locally (since you are seeing exactly what the users will see), but it has the disadvantage that it takes longer for each build of the docs.

**Comment by stggh** [comment]
doc building operates on my (home) Macbook pro. The `virtualenv` is a good idea.

I will try to add input to `hansenlaw`, `tools.vmi` today.

**Comment by DanHickstein** [comment]
I think that these issues were taken care of.
