### ISSUE TITLE
AbelTransform Class  wrapper (I was wrong!)

### ISSUE THREAD

**Issue by stggh** [PyAbel/PyAbel#147]
Having been educated about the advantages of a class wrapper to provide function results for the benchmark results #136. I now (somewhat late) realise that @DanHickstein and @rth were correct all along. **I was wrong!**  The `AbelTransform` class wrapper may work (as long as I ignore the large instance function). It has the *advantage* of showing the user what results are available, e.g. see the benchmark timings(at bottom of this message).

`transform.py` should be changed back to `class  AbelTranform(object)` with the `results['xxx']` given as `self.xxx`.   NB the `fabel/iabel` aspect should not be re-instated, due to the loss of method query functionality.

I am **happy** to make the changes, which should not be too large, but may not have time enough in the next few days. I am away this weekend (for a 3 day break, at the NSW coast).

@DanHickstein, I am very sorry about all the past coding change you made ...
@rth my apologies too!

```python
In [1]: import abel
In [3]: times = abel.benchmark.AbelTiming(n=[101])
# results available as a query
In [4]: times.
times.fabel  times.iabel  times.n      
In [5]: times.iabel
Out[5]: 
{u'basex': [1.1019706726074219],
 u'basex_bs': [245.3019618988037],
 u'direct_python': [5.114078521728516],
 u'hansenlaw': [3.0488967895507812],
 u'three_point': [0.3859996795654297],
 u'three_point_bs': [50.03499984741211]}
```

**Comment by DanHickstein** [comment]
I think that the function-returning-a-dictionary is actually pretty intuitive. Are there additional arguments for a Class, aside from being able to preview the various results in iPython? I'm tempted to stick with what we have for the time being, unless there are reasons to make the switch.

I suppose I do like the cleaner "dot notation"...

**Comment by stggh** [comment]
Having spent the day typing `results['angular_integration']` the possible ipython short cut `results.a<tab>` appeals.

**Comment by DanHickstein** [comment]
Well, the dot notation is really nice, and the class leaves things open for the easy addition of other data-processing features. 

How you visualize the organization of the class? With most of the current `abel.transform()` function in the `__init__` function like we had it before? (Which is fine, I don't think that it's bad style at all for a class to have most of it's functionality in the `__init__` function.) 

Perhaps the angular_integration bit should move into it's own class function since it's possible that only a fraction of users will want this functionality.

Maybe @DhrubajyotiDas has thoughts on this resurrected discussion?

**Comment by stggh** [comment]
Make `def transform()` the instance function, each `results['xxx']` becomes `self.xxx` etc. The biggest change will be to the docs.

The call becomes  `abeltrans = AbelTransform(IM, ...)` with results `abeltrans.transform`, `abeltrans.angular_integration` and `abeltrans.reconstruct`.

**Comment by DhrubajyotiDas** [comment]
@DanHickstein I am not opposed to this change. If we do 
```python
abeltrans = AbelTransform(IM, ...)
```
and then try pressing tab after `abeltrans.`, will the possible results pop up?

**Comment by DanHickstein** [comment]
Yes, I think that will be the behavior in iPython. I don't think regular Python has autocomplete capabilities (could be wrong). Try it with @stggh's example from above:
```python
In [1]: import abel
In [3]: times = abel.benchmark.AbelTiming(n=[101])
In [4]: times.
times.fabel  times.iabel  times.n   
```

**Comment by stggh** [comment]
Another argument in favour of the change from dictionary (back) to class is that 99% of the time I leave off the ['transform'] in `AIM = abel.transform(IM, method="hansenlaw", direction="inverse")` and I am supposed to know what I am doing ...

**Comment by DanHickstein** [comment]
Well, in the case of the class, you (and I!) would simply exchange forgetting to type `.transform` for forgetting to type `['transform']`.  :)

**Comment by stggh** [comment]
No worries. There does not appear to be a great groundswell for the change. I am happy to take advice on either submitting a PR (not yet coded) or to close this issue.

**Comment by DanHickstein** [comment]
I think that you are right that the class is the best way to go. If nothing else, it provides a cleaner `.transform` syntax and leaves room for more options in the future. You'll need to change `transform.py`, the examples, the docs, and probably anywhere else that uses `abel.transform`. You may want to employ a text editor that will allow you to search the whole project for `"abel.transform"` - I've recently been experimenting with [Atom](https://atom.io/) and have been delighted with the "[search project](https://atom.io/docs/v0.194.0/using-atom-find-and-replace)" feature.

While you are at it, I think that we should probably start keeping track of major changes like this in a changelog. In the PR, can you also add a CHANGELOG.rst and include this change. Something like:

```
2016-03-15 - Changed abel.transform to be a class rather than a function. The previous syntax of: ::
   abel.transform(IM)['transform']

has been replaced with: ::
    abel.transform(IM).transform
```

This will come in handy when we want to offer release notes for each new version.

**Comment by stggh** [comment]
For text-in-file searching I use:
```find /start/dir/ -name '*.py' -exec grep 'text to find' {} \; -print```

**Comment by DanHickstein** [comment]
Good work on this @stggh!
