### ISSUE TITLE
Linalg performance

### ISSUE THREAD

**Issue by DanHickstein** [PyAbel/PyAbel#148]
Following up on the benchmarking discussion, I randomly happened across some information on the linear algebra performance in Scipy: 
http://scipy.github.io/old-wiki/pages/PerformanceTips
(scroll down to "Linear Algebra on Large Arrays" near the bottom).

Also:
http://stackoverflow.com/questions/5990577/speeding-up-numpy-dot

Basically, there is the potential to speed up the dot product if you are careful to maintain the alignment of the array. I tried the "fastdot" module here, but it kept about the same speed:

https://www.huyng.com/posts/faster-numpy-dot-product

Just thought that I would make a note of that here.

**Comment by stggh** [comment]
@DanHickstein thanks for this information. All good to know.
