### ISSUE TITLE
DOI for citing PyAbel

### ISSUE THREAD

**Issue by DanHickstein** [PyAbel/PyAbel#149]
I saw that GitHub new supports the use of Zenodo (CERN sponsored repository for open-access papers and datasets) for automatically generating DOIs for software packages. 

In the absence of any other citation for PyAbel, I thought that I would try it out. 

http://dx.doi.org/10.5281/zenodo.47423

It lets us put a little tag in the read-me that people can click on:
https://github.com/DanHickstein/PyAbel/tree/readme_edits#citation

Looks pretty professional :)

Any objections to this? @PyAbel/developers, did I get your name/affiliation correct? I put @stggh last in the "professors-go-last" style. Hopefully that's okay.

**Comment by DhrubajyotiDas** [comment]
This looks really cool! I wasn't aware that software packages could get their own DOIs like this. Very impressive!

**Comment by stggh** [comment]
@DanHickstein you discover the most amazing stuff.  The link looks great, and it stands out.

If it is not too much trouble I would prefer to use full name for the author citation:   
Stephen T. Gibson. 

Tks.

**Comment by DanHickstein** [comment]
Conversion process complete: You are now Stephen T. Gibson.

**Comment by ldes89150** [comment]
@DanHickstein Thanks for doing this.

If you don't mind, I would like to use my full name

Chung-You Shih

instead of using Gilbert Shih.

Thanks!!

**Comment by DanHickstein** [comment]
Thanks for letting me know! Change made.
