### ISSUE TITLE
uploaded corrected file to doc/transform.py

### ISSUE THREAD

**Issue by stggh** [PyAbel/PyAbel#153]
@DanHickstein help ...

The docstring for `IM` in `transform.py` was ambiguous. I tried to upload the corrected file directly, but it has ended up in the `doc` directory!

Are you able to move it to the `abel` directory?

Sorry, about this. I thought a simple file upload would be simpler than a full PR ...

Edit: I found the bin delete file symbol

**Comment by DanHickstein** [comment]
Can you just move it an make a new PR? Nothing wrong with another PR...

**Comment by stggh** [comment]
I found the delete file symbol. All good, I will stick with a PR in future.
