### ISSUE TITLE
sub-pixel transform alignment discussion

### ISSUE THREAD

**Issue by stggh** [PyAbel/PyAbel#159]
`example_all_O2.py` demonstrates pretty good agreement between the transform methods, but at the pixel level there are positional differences between transform methods, as illustrated by the right figure zoom.

![o2-allx](https://cloud.githubusercontent.com/assets/10932229/14479336/b3a73efe-0160-11e6-941e-84a1ad8d0101.png)  ![o2-all-zoomx](https://cloud.githubusercontent.com/assets/10932229/14479349/cb28eb04-0160-11e6-8fe2-8c2a1658025d.png)

The offsets are sub-pixel, about `1/2`-pixel difference between the `hansenlaw` method and `three_point`.

Here is the situation for the "Ominus" sample image [[code](https://gist.github.com/stggh/c4c44c8f29c377a9f8c1ce450d75088e)]
![o-](https://cloud.githubusercontent.com/assets/10932229/14480032/356375e6-0168-11e6-8513-0d7ea6bbbb11.png)
Neither `hansenlaw` nor Dasch `three_point` align perfectly with the original image, but **NB** these are inverse Abel transforms of the **projected** sample image, the forward `hansenlaw` transform.

To attempt to track down any issues with transform method coding, I have run some 1-d function tests. 2d testing will follow.  The 1d-functions include a Gaussian function, which transforms to the same function  <math>x&sigma;&radic;&pi;</math>, where &sigma; is the Gaussian width at `1/e` height, and "curve A" from the [Hansen and Law paper](http://dx.doi.org/10.1364/JOSAA.2.000510) also listed in @DhrubajyotiDas [ipython notebook](https://gist.github.com/DhrubajyotiDas/f8f531ca2cfa3fee6345), which also has a well defined transform. [[Test code](https://gist.github.com/stggh/2d245a6c2187f4d737e978b26be4e8b5)].
1. 1d-Gaussian
   
   _forward_
   There are only two forward transforms in PyAbel, `direct` and `hansenlaw`, both projections agree well with a scaled Gaussian (left side figures below).  The inset is a zoom of the `0-50` radius peak area. 
   
   _inverse_
   I have included the Dasch `three_point` method, which has excellent agreement with the 1d-Gaussian original function. Both `hansenlaw` and `direct` diverge from the Gaussian near the image center-line (function maximum).

![1d-gaussian](https://cloud.githubusercontent.com/assets/10932229/14480593/dc70a548-016d-11e6-9f8a-a4fdee1adc7c.png)
1. curve A 
   
   _forward_
   For this transform there are larger differences.
   
   _inverse_
   Here `direct` goes haywire, and has not been excluded from the difference plot (lower right). `three_point` is stellar, while `hansenlaw` shows a greater deviation.

![1d-curvea](https://cloud.githubusercontent.com/assets/10932229/14480599/defd89b6-016d-11e6-8c29-f3f86369f88a.png)
## Conclusion (so far ...)

The main issue at the moment is, for the 1d-Gaussian transform, is whether the down-turn observed for `direct` and `hansenlaw` is the method, or a pixel offset introduced in the coding. This aspect has been discussed in the past, although I cannot easily locate the link. For `hansenlaw` the deviation is enhanced using a smaller image size.

This issue is raised for advice, ideas, and suggestions as to how best to verify the algorithms. Test cases for 2d images will follow.

**Comment by DanHickstein** [comment]
@stggh,

Thanks for bringing up this issue. At some level, I think that the transform methods are making an approximation that the curve is well-sampled, and as we look at things on a single-pixel level, that approximation may not apply. However, it would be nice if the transform methods produced similar results, even at a single pixel. I don't have much insight into what is going on at this point, but perhaps you can try to make the "single-pixel step function"e example case to make small shifts easier to spot?

**Comment by stggh** [comment]
@DanHickstein good thoughts. Testing continues ...

**Comment by stggh** [comment]
This is interesting. For the analytical step-function test [code](https://gist.github.com/stggh/c1968d7d856447628001740d5a66fc71) with `n=101` :
![step_forward-direct](https://cloud.githubusercontent.com/assets/10932229/14583998/4097fa56-0477-11e6-9a02-7ea873d29971.png)

1. The "shark-fin" shaped forward transform (projection) has close agreement until the inner step.
2.  PyAbel `direct` transform has similar same behaviour to `hansenlaw` (apart from its own odd step-structure?).
3. The difference becomes less apparent for large `n`, but is still present.
4. BTW, the divergence near `x~0` for the `hansenlaw` inverse Abel transform, is what initiated this investigation.

I am not sure what this all means, but IMO interesting none the less.

**Comment by DanHickstein** [comment]
Wow, that is interesting behavior. I wonder how much this depends on the method used for calculating the numerical derivative. `np.gradient` uses second order central differences, but this may not necessarily be what we want. At one point, @rth provides a link to a page about different methods for numerical derivatives.

**Comment by stggh** [comment]
The forward transform operates on the raw image, no derivative issues (I have had time to think about the this ;-) ).

**Comment by DanHickstein** [comment]
Good point! 

Well, actually the analytical solution looks to be off by a pixel on the inside. Shouldn't the max align with the edge of the step function?

**Comment by stggh** [comment]
Interesting observation, although the analytical projection has the same behaviour.

**Comment by DanHickstein** [comment]
? I'm saying that the analytical forward abel (projection) is not quite what I would expect. It seems to be off by a pixel.

**Comment by stggh** [comment]
Right! I did not read your comment with enough care.

**Comment by stggh** [comment]
The forward transform [Wolfram](http://mathworld.wolfram.com/AbelTransform.html) for a unit step <math>0&le; x &le; a</math>, is <math>2(a<sup>2</sup> - x<sup>2</sup>)<sup>&frac12;</sup></math>, which is zero at `x=a`. In principle, there is no signal until <math>x &le; a</math>, and this behaviour is reflected in the PyAbel transforms (`direct` and `hansenlaw`). In this regard, all is well.

For the step-function <math>r<sub>0</sub> &le; r &le; r<sub>1</sub></math> (slight change of limit notation to match the `analytical.py` python code `abel_step_analytical()`). In the region of the step (as above)  <math>g(r) = 2(r<sub>1</sub><sup>2</sup>-r<sup>2</sup>)<sup>&frac12;</sup></math>, before (inside) the step <math>g(r) = 2(r<sub>1</sub><sup>2</sup>-r<sup>2</sup>)<sup>&frac12;</sup>-2(r<sub>0</sub><sup>2</sup>-r<sup>2</sup>)<sup>&frac12;</sup><math> = step - "missing" step.

Hence, the apex of the projection `g(x)` should be at `x=r0`, so the analytical function is incorrect at this position. The PyAbel transforms are correct.

**Comment by stggh** [comment]
In `analytical.py` the definition of the square-pulse  <math>r<sub>0</sub> &le; r &le; r<sub>1</sub></math> differs between the function (line 194) and projection (line 287):
```python
    mask = np.abs(np.abs(self.r) - 0.5*(r1 + r2)) < 0.5*(r2 - r1)

    fr = np.zeros(self.r.shape)
    fr[mask] = A0
            :
    mask = (r >= r0)*(r <= r1)
    F_1d[mask] = 2*np.sqrt(r1**2 - r[mask]**2)
```
While adding `<= 0.5` to line 194, fixes the alignment of the analytical projection with `direct`, but now 'hansenlaw
![step_forward101](https://cloud.githubusercontent.com/assets/10932229/14592688/ca53f400-0564-11e6-95f8-25c0821b9ba5.png)

**Comment by stggh** [comment]
The test-figure provides some mind-blowing alignment illusions. 

Here is the situation for `r0=6.1, r1=13.9`  (I have dropped the inverse Abel transform plot). There is some limit problem here:

![step_forward101](https://cloud.githubusercontent.com/assets/10932229/14593310/3b217610-056c-11e6-9eab-83d8dc5267a0.png)

**Comment by DanHickstein** [comment]
Okay, so it seems like you've basically fixed the analytical case.

But, you now see an issue where the magnitude of the analytical signal doesn't quite line up with the numerical transforms, and the degree of disagreement depends on the exact (decimal) position of the step function. The numerical functions have no knowledge of sub-pixel shifts in the position of the step, so I think that it makes sense that you should see this. 

If you can find the shape of the step that causes the best agreement between the analytical methods and the numerical methods, then I think that this tells us the coordinate system that the numerical methods are actually using.

Unraveling this may take us back to the question that came up during the discussion of even/odd image sizes: what x-values do the transform methods actually assume for the different pixels.

BTW: are you using the direct-C implementation, or the Direct-Python? The slight "wiggle" of the forward-direct transform suggests to me that there is some issue with round-off error. Perhaps integer division is accidentally popping up somewhere. The slight disagreement between the Direct-Python and Direct-C implementations is still an outstanding issue (https://github.com/PyAbel/PyAbel/issues/58), so it would be good to see if this step-function is a case where the two clearly disagree.

**Comment by stggh** [comment]
BTW)
Added a trace print statement to `abel/direct.py` the backend is definitely using direct-C. The wiggle appears when transforming a step function, but not for a Gaussian. Plot compares projection and direct_C forward transform of a 1d-Gaussian and 1d-step [code](https://gist.github.com/stggh/b694b1a85d8d8c95fdca59c74b03fbf8) 

![direct-1d-gauss-step](https://cloud.githubusercontent.com/assets/10932229/14624235/52ef6b34-061c-11e6-8bac-341d57837868.png)

1) even/odd - my nemesis  ... TBC

**Comment by DanHickstein** [comment]
So, I think that the "wiggle" might come from the integration method. It's even more pronounced for the direct_Python implementation. And, if you pass the parameter `int_func=scipy.integrate.trapz`, then you can force it to integrate with scipy's built-in trapezoidal rule, which makes the transform look smooth. I think that Simpson's rule might not work well for such sharp functions. 

![direct-1d-gauss-step](https://cloud.githubusercontent.com/assets/1107796/14627977/d6aed948-05b6-11e6-8b28-642adf44bdc4.png)

Code: https://gist.github.com/DanHickstein/04952937bab72e78adbea8100f111d31

Try passing `correction=False` to the direct methods - it changes the result pretty dramatically. Also, the correction involves a numerical derivative, so, there is still a derivative involved in the calculation of the forward transform using the Direct method (assuming `correction=True`).

**Comment by stggh** [comment]
I also thought of the integration function, but specified `int_func=scipy.integrate.simps`, to no effect ;-)

Note, that although smooth, `direct_python` deviates more than `direct_C` (not shown in the figure below) from the analytical projections, there is some sort of displacement, and the Gaussian rolls over early.

![direct-1d-gauss-step](https://cloud.githubusercontent.com/assets/10932229/14628347/5f246714-0640-11e6-9f43-a945dbf884f4.png)

Your conclusion is correct that the step function is too sharp for the integration method(s).  It may not be a fair test for any of the algorithms.

PS: well spotted the incomplete analytical step projection in my code

**Comment by DanHickstein** [comment]
> I also thought of the integration function, but specified int_func=scipy.integrate.simps, to no effect ;-)

Note also that the `int_func` only has an effect for the Python implementation. You can also specify `np.sum` if you want it to be really bad :)

The Simpson's rule should be a good method in most cases - I think that it should be more accurate than a simple trapezoidal approximation, but maybe it gets confused easier with very sharp features.

**Comment by DanHickstein** [comment]
@stggh, I'm trying to close some of the old issues. Did we come to a conclusion about this? Is this just a fundamental difference between the numerical and analytical approaches?

**Comment by stggh** [comment]
@DanHickstein this issue is not yet resolved. I do know that there is an annoying 0.5 pixel offset for the `hansenlaw` inverse Abel transform.  Differences between other transform methods may well be in the noise.

(@DanHickstein, @rth, @DhrubajyotiDas - it is Saturday morning in OZ, and I see the great amount of activity that has taken place overnight. Fantastic work everyone. I will try to catch up ...)

**Comment by DanHickstein** [comment]
@stggh, are you still under the impression that hansen-law has a half-pixel shift?

In my recent comparison (using your photoion image), Hansen-law, three-point, and Direct have excellent agreement:

![image](https://user-images.githubusercontent.com/1107796/34528104-0d20a1f6-f065-11e7-93fe-089f7a094ad7.png)

As discussed in [Dasch](https://www.osapublishing.org/ao/abstract.cfm?uri=ao-31-8-1146), we should expect minor differences between the transform algorithm in how they treat very sharp functions:

![image](https://user-images.githubusercontent.com/1107796/34528088-ffc46394-f064-11e7-8697-f6663cf0de48.png)

(For the record, https://github.com/PyAbel/PyAbel/pull/204 addresses the oscillations in the Direct-P method discussed above, which were a result of our somewhat improper use of `scipy.integrate.simps`.)

So, can we close this issue? (We might be able to close 4 this week!!)

**Comment by stggh** [comment]
Found `hansenlaw` bug in the grid definition that caused the sub-pixel offset. See PR #206
