### ISSUE TITLE
Wrong example of use code in docs

### ISSUE THREAD

**Issue by furii** [PyAbel/PyAbel#169]
Hi, 
It seems that some interfaces have changed in the 0.7.4 version. That gave me some trouble, especially since the examples of use in the documentation are not correct. Basically abel.transform is now a module, and the transform function is capitalized (abel.Transform). Would be nice if this is fixed in the docs too.

**Comment by furii** [comment]
grep'ed through the source code and it looks like README.rst was the only instance with wrong use of abel.transform. Changed it and created Pull Request.

**Comment by DanHickstein** [comment]
Thanks for catching this!
