### ISSUE TITLE
Need to update links to readthedocs

### ISSUE THREAD

**Issue by DanHickstein** [PyAbel/PyAbel#174]
I got this following e-mail from readthedocs.org today, indicating that they will be migrating user documentation from readthedocs.org to readthedocs.io. I think that the only place that this is an issue is in README.md, but we should make sure that this doesn't break any other links in PyAbel's docs.

e-mail: 

> Hello!
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
> 
> Changes to provide security against broader threats have been in place for a while, however there are still a few scenarios that can only be addressed by migrating to a separate domain.
> 
> We implemented session hijacking detection and took precautions to limit cookie usage, but there are still a number of scenarios utilizing XSS and CSRF attacks that we aren't able to protect against while hosting documentation from subdomains on the readthedocs.org domain. Moving documentation hosting to a separate domain will provide more complete isolation between the two user interfaces.
> 
> Projects will automatically be redirected, and this redirect will remain in place for the foreseeable future. Still, you should plan on updating links to your documentation after the new domain goes live.
> 
> If you notice any problems with the changes, feel free to open an issue on our issue tracker: http://github.com/rtfd/readthedocs.org/issues. If you do notice any security issues, contact us at security@readthedocs.org with more information.
> 
> Keep documenting,
> Read the Docs

**Comment by stggh** [comment]
Received the same message. You are right, only `PyAbel README.md` has the link. However, will `sphinx` need to be updated?

At the moment `readthedocs.io` transfers back to `readthedocs.org`

**Comment by DanHickstein** [comment]
I think that Sphinx itself should not care, but we shall see! :)

**Comment by DanHickstein** [comment]
Okay, this should be addressed in #175, so, I'll close this issue. We can re-open if/when the docs beak :)

**Comment by rth** [comment]
@DanHickstein I forgot, how do we update the docs? Do they get built automatically, or do we need to upload the changes manually to readthedocs?

**Comment by DanHickstein** [comment]
I think that it's totally automatic.
