### ISSUE TITLE
Allow for wider basis functions: investigate why nbf != n/2 +1 doesn't produce the expected result

### ISSUE THREAD

**Issue by DanHickstein** [PyAbel/PyAbel#18]
In most cases, it makes sense to use a number of basis functions so that there is one basis function per pixel. Currently ``nbf`` defaults to ``250`` and we do not mention that ``n`` and ``nbf`` should be changed together. This behavior could be made more obvious by making ``nbf`` default to ``'auto'``, in which case ``nbf`` will be set to ``(n-1)/2``. 

Actually, now that I actually try to use ``nbf != (n-1)/2``, the behavior is not at all what I expected. As @DhrubajyotiDas mentioned in https://github.com/PyAbel/PyAbel/issues/14, a smaller number of basis functions should provide larger functions and better smoothing of the data. Instead, changing the number of basis functions simply provides a basis set that only transforms the center of the image.

``n=501, nbf=250:``
![image](https://cloud.githubusercontent.com/assets/1107796/11282671/cd0968d8-8ebd-11e5-8a41-a8873acb63ab.png)

``n=501, nbf=100``
![image](https://cloud.githubusercontent.com/assets/1107796/11282668/c7df1920-8ebd-11e5-9a9f-c41b83b1429f.png)

**Comment by rth** [comment]
Aww, yes that is a good point. I'm not sure at all that the basis set generation routine is correct when `nbf != (n-1)/2` (n odd)  as we have only tested it against an example basis set that has `2*nbf +1 = n`. I mean it is identical to the matlab implementation, but I don't know if that one was correct in this case. For now, maybe we can just set `nbf='default'`  (and set `nbf = n//2` (integer division) in the code)   as you mentioned?

**Comment by DanHickstein** [comment]
Yes, we should have ``nbf='auto'`` and set it to ``n//2``. We should probably include a warning if the user tried to set nbf to anything different until we figure out what is going one with the basis set generation.

**Comment by DhrubajyotiDas** [comment]
Just noticed something: Typically when `n` is an odd number, say, `5`, then there's `5//2+1 = 3` "unique" points (`r = 0, +/-1, +/-2`) that need to be resolved with the basis functions `nbf`. Currently the `nbf = auto` option will set it to `5//2 = 2` basis functions, when it should default to `5//2 + 1 = 3` basis functions.

**Comment by DanHickstein** [comment]
So, the ``n`` value actually works strangely as well. In the docstring, we say:
```
Abel inverse transform will be performed on a `n x n` area of the image
```
In fact, if ``n=501``, then the transform is performed on a ``500x500`` region. So this bug might compensate for the other bug...

**Comment by rth** [comment]
I think the docsting is wrong, because the in the basis set generation, we do generate a matrices `n x nbf`, where both `n` and `nbf` are odd (e.g. `501x251`). And since the final image is generated as the matrix product of those matrices, the output shape is `n x n`. Just added a unit test for that: `test_basex_shape`.

**Comment by DanHickstein** [comment]
As it stands now, I think that our understanding is that BASEX only works with odd ``n`` and ``nbf=(n//2)+1`` (for example, ``n=101, nbf=51``). So, we have, to some degree, fixed this bug by identifying a fundamental limitation of our current algorithm. So, I propose to close this issue and open another "Enhancement" issue to implement the use of non-pixel-sized basis functions in BASEX. 

Sound good?

**Comment by rth** [comment]
Closing this issue as per @DanHickstein comment above. Further improvement of the BASEX implementation could be done in a separate issue. Particularly if we drop the axis-symmetric implementation in favour of the non axis-symmetric one, as discussed earlier.

**Comment by DanHickstein** [comment]
Yes, this can be closed. Sometime in the future it would still be nice to see an option to use a wider basis set. I think that BASEX.exe even supported this, so it should be possible. A similar result could probably be achieved by smoothing the image before or after our current pixel-sized-basis-set implementation, so it's probably not a feature that people are going to be requesting anytime soon.
