### ISSUE TITLE
multicore image processing

### ISSUE THREAD

**Issue by stggh** [PyAbel/PyAbel#181]
Python provides the  [multiprocessing](https://docs.python.org/2/library/multiprocessing.html) library to execute code on multiple cpu-cores.  I thought this may be a good way to speed-up the Abel transform for large images, and there is nothing more pleasing than viewing all cpus busy, running your job, in `top`.

The easiest place to make the code change is in `abel.transform.Transform._abel_transform_image_by_quadrant.selected_transform(Z)`, changing
```python
        def selected_transform(Z):
            return abel_transform[self.method](Z, direction=self.direction,
                                               **transform_options)
```
to
```python
       def selected_transform(Z):
            func = partial(abel_transform[self.method],direction=self.direction,
                                                       **transform_options)
            return np.array(self.pool.map(func, Z))
```

This splits the image (`Z`) rows over multiple processors (I believe!).  Code available on my fork [multiprocessing.](https://github.com/stggh/PyAbel)

It turns out this **increases** the execution time (only tested for example_hanselaw.py), because, I guess, of the overhead of forking processes. (Edit: also, not good to call image row-by-row for the basis set methods)

Edit2: in principle the 4 image-quadrants could be individually sent to separate processor cores.

 I believe that multi-core processing may be useful for production line Abel transform of many images (such as processing video, @DanHickstein's idea). 

This "issue" is the starting point to implement efficient multiple image Abel transforms in PyAbel.

**Comment by DanHickstein** [comment]
@stggh, Thanks for looking into this!

I am not sure if it's worth breaking up the image into separate rows, since in many cases it's best to just pass the whole glob to scipy/numpy functions that are already heavily optimized. It might depend on how you have your math libraries installed, but they should already have parallel processing. On this iMac, most of the faster transform methods (hansen-law, three-point, etc.) already peg my 4-core CPU at ~400% utilization.

Also, even if we have methods that only run on one core (this seems to be true for the direct_Python, and maybe others), it might not be especially rewarding to try to parallelize them. We should be motivated to try to speed up the individual algorithms if we think that people are likely to try to transform huge images, say 10,000x10,000. (Still, some of our algorithms can handle such huge images, and they can do so using all cores.)

In contrast, I think that the more likely "high bandwidth" application will be transforming many smaller (2,000x2,000 or less) images at very high frame-rates. In this situation, we can granulate the task by sending each image to a separate core (or set of cores). This parallelization is embarassingly parallel, and so we can see speed gains that scale directly with the number of cores that we throw at the problem. Any parallelization that we try to do at a finer level is likely to not scale as favorably.

All this to say, I shy away from actually including and multiprocessing capability to the main PyAbel code-base, since I think that parallel processing is complicated, system architecture dependent, and makes code really hard to read/debug. However, I would love to include an example that shows how multiple images can be processed simultaneously. I'm not completely sure how much that will speed things up for the methods like three-point (which already use all the cores) but if we run it on a cluster, then it should be pretty quick.

**Comment by stggh** [comment]
@DanHickstein I reached the same conclusion, and I agree with your comments. There may be a small case for sending off the 4-quadrants (when the image is symmetric) to individual processors.

I found your comment interesting:
> On this iMac ... already peg my 4-core CPU at ~400% utilization

On my Linux system i7-6700 CPU @ 3.40GHz (8 core) and the School's (ANU) Xeon(R) CPU E5-2697 v3 @ 2.60GHz (56 core, not the 64 I thought) there is **no** evidence of multicore usage when running:
`abel.benchmark.AbelTiming(n=[301, 501, 1001, 1441], n_max_bs=1500, n_max_slow=1500)`
and watching `top`. However, if `multiprocessing.Pool()` is run, then many  cpu-cores are used.

The timings indicate that the system installed `libblas` and `liblapack` are used, and `multiarray` is [available to numpy](http://stackoverflow.com/questions/9000164/how-to-check-blas-lapack-linkage-in-numpy-scipy).

Here is the timing for a 2MB image 1441x1441 (and the smaller ones for our relative comparisons);
i7 6700:
```
In [3]: abel.benchmark.AbelTiming(n=[301, 501, 1001, 1441], n_max_bs=1500, n_max_slow=1500)
Out[3]: 
PyAbel benchmark run on x86_64

time in milliseconds

=========    Basis Abel implementations ==========

Implementation      n = 301           n = 501           n = 1001          n = 1441      
----------------------------------------------------------------------------------------------
        basex_bs    6307.4           20031.0          155548.3          512487.2         
     linbasex_bs      13.2              12.9              69.3             120.4         
onion_peeling_bs       2.8               7.8              38.3              98.1         
  three_point_bs      16.6              30.2             201.5             324.0         
    two_point_bs       3.5               9.9              44.4              91.6         


=========  Forward Abel implementations ==========

Implementation      n = 301           n = 501           n = 1001          n = 1441      
----------------------------------------------------------------------------------------------
        direct_C      23.7              78.9             591.2            1916.0         
   direct_Python      81.9             301.3            4351.0           12326.3         
       hansenlaw       8.3              18.1              67.2             126.2         


=========  Inverse Abel implementations ==========

Implementation      n = 301           n = 501           n = 1001          n = 1441      
----------------------------------------------------------------------------------------------
           basex       2.3              20.1             132.3            1296.0         
        direct_C      21.5              79.9             631.2            1972.3         
   direct_Python      69.1             330.8            4095.5           12402.9         
       hansenlaw       8.5              20.3              76.5             137.4         
        linbasex      35.6             100.1             444.0            1350.8         
    onion_bordas     288.1             939.2            6488.4           23587.7         
   onion_peeling       0.5               1.8              21.3              34.0         
     three_point       0.5               1.9              14.8              60.7         
       two_point       0.6               2.1              12.5              34.1                  
```

Xeon:
```
Out[2]: 
PyAbel benchmark run on x86_64

time in milliseconds

=========    Basis Abel implementations ==========

Implementation      n = 301           n = 501           n = 1001          n = 1441      
----------------------------------------------------------------------------------------------
        basex_bs    8490.2           26535.4          203702.9          667790.2         
     linbasex_bs       8.1              18.5              79.2             159.2         
onion_peeling_bs      38.9              10.5              47.8             110.0         
  three_point_bs      20.2              51.1             218.7             476.3         
    two_point_bs       5.8              14.1              55.2             129.7         


=========  Forward Abel implementations ==========

Implementation      n = 301           n = 501           n = 1001          n = 1441      
----------------------------------------------------------------------------------------------
        direct_C      30.4             116.9             757.4            2191.7         
   direct_Python     120.6             454.4            3307.8           16649.9         
       hansenlaw      11.3              30.9             126.9             204.7         


=========  Inverse Abel implementations ==========

Implementation      n = 301           n = 501           n = 1001          n = 1441      
----------------------------------------------------------------------------------------------
           basex       1.0               9.3              59.9            1058.8         
        direct_C      27.6             117.9             819.5            2255.8         
   direct_Python     118.8             466.4            3313.3           13535.1         
       hansenlaw      12.3              33.3             124.1             230.5         
        linbasex      61.6             154.3             564.9            1184.8         
    onion_bordas     360.0            1081.1            9842.2           14241.3         
   onion_peeling       3.3               8.7               7.1              20.7         
     three_point       0.2               0.6               5.8              15.2         
       two_point       0.3               1.1               5.8              28.9       
```

**Comment by DanHickstein** [comment]
Thanks for these latest benchmarks @stggh! It looks like the 1441 case is staying under 30 ms (for the Xeon), so we can still say that we are achieving HD video data-rates, which is great!

I am surprised that the Xeon crushed the i7, if the processes are really single-core. The i7-6700 is one of the fastest single-core processors ever made: https://browser.primatelabs.com/processor-benchmarks.

How do you know that the transforms themselves are not running in parallel? It would be hard to spot a 20 ms blip if you are just looking at `top` update every second or so. Indeed, most of the basis set generation and slow transforms (which, combined, take up almost all of the time during AbelTiming) are indeed single-core processes. However, try running
```
abel.benchmark.AbelTiming(n=[5001], select=['three_point'])
```
I see it crunch the basis set, and then the transform itself uses all cores. The 1441 size takes 82 ms on this iMac. I would be surprised if your Xeon could beat this by over 4x if it were using only a single core.

But, I think that we can see the diminishing returns of adding more cores.

You should be able to set the number of threads that the numpy linalg functions have access to. For example, if using Anaconda python with MKL:

```
In [16]: abel.benchmark.AbelTiming(n=[1001,1441], select=['three_point'])
Out[16]: 
PyAbel benchmark run on i386

time in milliseconds

=========    Basis Abel implementations ==========

Implementation      n = 1001          n = 1441      
----------------------------------------------------------
  three_point_bs     251.2             630.2         


=========  Forward Abel implementations ==========



=========  Inverse Abel implementations ==========

Implementation      n = 1001          n = 1441      
----------------------------------------------------------
     three_point      29.0              86.8         

In [17]: mkl.get_max_threads()
Out[17]: 4

In [18]: mkl.set_num_threads(1)

In [19]: abel.benchmark.AbelTiming(n=[1001,1441], select=['three_point'])
Out[19]: 
PyAbel benchmark run on i386

time in milliseconds

=========    Basis Abel implementations ==========

Implementation      n = 1001          n = 1441      
----------------------------------------------------------
  three_point_bs     232.2             615.1         


=========  Forward Abel implementations ==========



=========  Inverse Abel implementations ==========

Implementation      n = 1001          n = 1441      
----------------------------------------------------------
     three_point      84.4             250.5         
```

**Comment by stggh** [comment]
@DanHickstein this is interesting. I obtain the same timing values (apart from a factor x1/2).
```
In [4]: import mkl

In [5]: mkl.get_max_threads()
Out[5]: 4
```

yet for the i7-6700 there are 8 cpu-cores, each with 2 threads.
```
 lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    2
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 94
Model name:            Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
Stepping:              3
CPU MHz:               799.987
CPU max MHz:           4000.0000
CPU min MHz:           800.0000
BogoMIPS:              6816.00
Virtualisation:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              8192K
NUMA node0 CPU(s):     0-7
```

**Comment by DanHickstein** [comment]
Do you mean that you were able to set `mkl.set_num_threads(1)` and decrease the performance of the transform? If this is the case, then you switched from multi-core to single core mode and everything makes sense. (Not sure what this factor of 1/2 is that you mentioned...)

The i7-6700 is a only a quad-core, so I think that MKL is doing the correct thing by only using 4 threads. As far as I can tell, the 2-threads-per-core "hyperthreading" thing is basically a marketing gimmick (or, at least in my applications, I haven't seen performance gains by increasing threads above the number of actual cores, despite the i7's claim that it should have 2x the real number of cores).

**Comment by stggh** [comment]
@DanHickstein you are absolutely correct, only 1/2 the cpu-core count contributes to the calculation. 

Thanks, for the thread/processor education.

I will close this "issue" as your original conciusion holds:
>  best to just pass the whole glob to scipy/numpy functions that are already heavily optimized ... already have parallel processing

**Comment by DanHickstein** [comment]
Thanks for bringing this up! It's important to thin about this stuff, and this discussion clarified my thinking. I actually did not realize that we were using more than one core until you posted this :)
