### ISSUE TITLE
Cython extension not building on Windows

### ISSUE THREAD

**Issue by DanHickstein** [PyAbel/PyAbel#183]
In the process of getting PyAbel on conda-forge, I noticed that the Cython extensions were failing on AppVeyor. It looks like some of our attempts to supress the warnings from the C-compiler may be causing problems: https://ci.appveyor.com/project/DanHickstein/pyabel/build/1.0.493

```
C:\Miniconda3\envs\abel-env\Scripts\gcc.bat -mdll -O -Wall -IC:\Miniconda3\envs\abel-env\lib\site-packages\numpy\core\include -IC:\Miniconda3\envs\abel-env\include -IC:\Miniconda3\envs\abel-env\include -c abel\lib\direct.c -o build\temp.win32-3.4\Release\abel\lib\direct.o -Wunused-function -Wunneeded-internal-declaration -Wno-#warnings
gcc.exe: error: unrecognized command line option '-Wunneeded-internal-declaration'
**************************************************
WARNING: Cython extensions failed to build (used in abel.direct).
Typical reasons for this problem are:
  - a C compiler is not installed or not found
  - issues using mingw compiler on Windows 64bit (experimental support for now)
This only means that the abel.direct C implementation will not be available.
```

Perhaps we should simple remove these flags and accept that fact that the C-compiler will spam us with lots of warnings during install?

**Comment by rth** [comment]
@DanHickstein Do you think it's related to https://github.com/PyAbel/PyAbel/issues/125 ? if so I can look into it this tomorrow. 

I'm +1 on removing those custom warning related flags in [`setup.py`](https://github.com/PyAbel/PyAbel/blob/master/setup.py#L55) (as they are compiler specific): if we want to remove them from the install stdout, a better way IMO would be fix the corresponding code in Cuython rather than hiding the warning.

**Comment by DanHickstein** [comment]
Yeah, it's likely that we broke things by trying to make the install process less verbose. If you have time to fix the Cython, then this would be great! Otherwise, we should probably remove all of the warning suppressions from the compiler arguments, since we are seeing that they cause problems for different compilers.

**Comment by DanHickstein** [comment]
In the process of submitting PR https://github.com/PyAbel/PyAbel/pull/184, I noticed that PyAbel fails the AppVeyor build, with an error relating to the Cython code: https://ci.appveyor.com/project/DanHickstein/pyabel/build/1.0.495

So, it seems that we are not doing a perfect job of allowing the C-compile to fail while successfully installing the rest of PyAbel. Also, we are down to just one AppVeyor build (Py2.7 on 32-bit). It would be nice to see if we can re-enable to rest of the tests on windows, even if we cannot get the Cython to work in all cases.

**Comment by DanHickstein** [comment]
Okay, to summarize, we removed all of the "warning suppression" flags from the compiler, which seems like a good long-term decision to avoid problems.

We were able to get the Cython extensions to build on AppVeyor, but only when it uses the MSVC 2015 compiler, which is does only for Py3. For Py2 builds, AppVeyor uses MSVC 2008, which doesn't have the `acosh` function, and fails. Attempts to substitute `acosh` with it's mathematical formula `acosh(x) = ln(1 + sqrt(x**2-1))` mysteriously didn't produce the same results and failed the unit test.

Current status is that we are not building the Cython extensions on AppVeyor for Py2.

**Comment by DanHickstein** [comment]
@rth, Judging from the conda-forge builds, it looks like AppVeyer uses MSVC 2008 for Py3.4 as well. Could you add also disable Cython extensions for Py3.4 as well?
https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.10470/job/7hq5dj95vqvbq694

**Comment by stggh** [comment]
No doubt a typo above, but:  `acosh(x) = ln(x + sqrt(x**2-1))`. However, I wonder what happens when `x <0`.

>  Attempts to substitute acosh with it's mathematical formula acosh(x) = ln(1 + sqrt(x**2-1)) mysteriously didn't produce the same results and failed the unit test

**Comment by rth** [comment]
Py3.4  uses Microsoft Visual Studio 10.0 / 2010, which seems to have the same issue.  I'll give another shot at replacing acosh by it's definition..

**Comment by DanHickstein** [comment]
Yeah, that was a typo above. Acosh is only defined above 1. But, `np.sqrt` returns `nan` for values less than 0, so I think that @rth's code should have worked fine.

**Comment by DanHickstein** [comment]
Oh, I think I see the issue. In @rth's [previous attempt](https://github.com/rth/PyAbel/commit/b92df68695839f6a3032fc7b2844fd67e86dac29), he used:
```python
 +cdef inline double acosh(double x) nogil:
 +    return log(x + sqrt(x**2 + 1))
```
which is actually `asinh`. `acosh` swaps the last `+` for a `-`.

**Comment by stggh** [comment]
Checking the `direct.py` code, I see that `arccosh` is only used for `correction = True` and

>     correction : boolean
  
       if False integration is performed with the Simpson rule,
        the pixel where the weighting function has a singular value is ignored
        if True in addition to the integration with the Simpson rule,
        integration near the singular value is done analytically,
        assuming a piecewise linear data.

So, in principle a C preprocessing statement could ignore the acosh for the compiler, providing an implicit `correction = False` for the crummy MSVC.

**Comment by rth** [comment]
Good catch @DanHickstein , feels like there is a type in every other message / commit these last few days.
I won't be able to make a commit fixing it today, but feel free to do so. Just adding that corrected function to the cython file  and removing the `acosh` cimport should fix it (the `setup.py` should be fine as it is now)...

@stggh yes, but it's C, so the linker is still looking to find references to all functions mentioned in the code and that one is missing...

**Comment by rth** [comment]
P.S: but if that's the problem I'm rather  worried about Travis CI tests still passing even with such error https://travis-ci.org/rth/PyAbel/jobs/189767399

**Comment by stggh** [comment]
@rth, I meant as a preprocessor directive, `#ifdef XXX` dependent on the compiler. The compiler would then not see the acosh code. Although, I must admit I am not sure how this is done.

**Comment by rth** [comment]
@stggh Aww, right, sorry I misread your message.  [This](https://cython.readthedocs.io/en/latest/src/userguide/language_basics.html#conditional-statements) might be relevant then (I have never tried doing preprocessing directives from Cython either)...

**Comment by stggh** [comment]
Neat! Cython makes available `UNAME_SYSNAME, UNAME_NODENAME, UNAME_RELEASE, UNAME_VERSION, UNAME_MACHINE`. It all depends on what these variables look like for MSVC < 2015?  Then in `direct.pyx` add, above line 70:
```python
               if UNAME_XXX != whatever corresponds to old MSVC:
                   if j < N1 - 1 and correction == 1:
```

I am still guessing here ;-)


For Travis CI, many of the `direct` tests are skipped. I presume @DanHickstein and @rth are looking into this?

**Comment by stggh** [comment]
Note that our `acosh` function definition eliminates every system from using the inbuilt function, if available. In the longer term, if applicable, the `if UNAME_XXX` approach may be better.

**Comment by DanHickstein** [comment]
@stggh, Are you assuming that our `acosh` function is going to be considerably slower than the built-in one? My guess is that it's not going to make a huge difference, but I could be wrong. If it is much slower, then it's probably worth it to include some if-statements to change the compiler preferences.

**Comment by stggh** [comment]
Yes, but you are ~~probably~~ usually right. ;-)

**Comment by DanHickstein** [comment]
Closing this issue, since it seems like we have the Cython code building with the new `acosh` function.
