### ISSUE TITLE
Conventions in README?

### ISSUE THREAD

**Issue by DanHickstein** [PyAbel/PyAbel#192]
In a discussion with @stggh, I realized that I was frequently getting confused if `IM[0]` referred to the "top" or "bottom" of an image in PyAbel. So, I was thinking that it might be nice if we listed some of the "PyAbel conventions" in the README file, and if you all had any suggestions for what might be listed there. So far I can think of:

- **Image orientation:** PyAbel adopts the "television" convention, where `IM[0,0]` refers to the **upper** left corner of the image. (This means that `plt.imshow(IM)` should display the image in the proper orientation, without the need to use the `origin='lower'` keyword.) As an example, the x,y-grid for a 5x5 image can be generated using:
    ```python
    x = np.linspace(-2,2,5)
    X,Y = np.meshgrid(x, -x) # notice the minus sign in front of the y-coordinate
    ```

- **Angle:** All angles in PyAbel are measured in radians. When an absolute angle is defined, zero-angle corresponds to the upwards, vertical direction. Positive values are on the right side, and negative values on the left side. The range of angles is from -Pi to +Pi. The polar grid for a 5x5 image can be generated (following the code above) using:
    ```python
    R = np.sqrt(X**2 + Y**2)
    THETA = np.arctan2(X, Y)
    ```
    where the usual "`(Y, X)`" convention of `arctan2` has been reversed in order to place zero-angle in the vertical direction. Consequently, to convert the angular grid back to the Cartesian grid, we use:
    ```python
    X = R*np.sin(THETA)
    Y = R*np.cos(THETA)
    ```

- **Image center:** Fundamentally, the Abel and inverse-Abel transforms in PyAbel consider the center of the image to be located in the center of a pixel. This means that, for a symmetric image, the image will have a width that is an odd number of pixels. (The center pixel is effectively "shared" between both halves of the image.) In most situations, the center is specified using the `center` keyword in `abel.Transform` (or directly using `abel.center.center_image` to find the true center of your image. This processing step takes care of locating the center of the image in the middle of the central pixel. However, if the individual Abel transforms methods are used directly, care must be taken to supply a properly centered image.

EDIT: Fixed a bunch of minor issues with the above on Feb 22, 2017.

Anything else??

(Alternatively, this information might be too specialized, and we should include it in the CONTRIBUTING.md, file.)

**Comment by stggh** [comment]
@DanHickstein this is a very good description. I prefer the information *not* to be in `CONTRIBUTING.rst`, which contains a lot of great information that most people might miss. So, `README.rst` is fine, or how about `CONVENTIONS.rst`?

One minor point, unfortunately, `onion_bordas` uses an even size image, with the grid on the left-bottom pixel corner. 
```
  This function operates on the "right side" of an image. i.e. it works on 
    just half of a cylindrically symmetric image.  Unlike the other transforms,
    the left edge should be the image center, not mid-first pixel. This 
    corresponds to an even-width full image. If not, set `shift_grid=True`
```

See #39 for the grid diagram, perhaps, it could be copied, as the subsequent text is dated.

**Comment by DanHickstein** [comment]
Oh, I didn't realize that `onion_bordas` was stuck in the dark ages. Ultimately, we might not keep it around, since the dasch onion peeling method provides better performance. In the mean time, I guess we need an (*except the `onion_bordas` method) added to the above text.

In the "conventions" text, we may also want to mention a bit about how VMI folks will want to think about the Jacobian when integrating.

**Comment by stggh** [comment]
*Jacobian* another dark horse. Fortunately, we spectroscopists have real spectra, so we know exactly how the intensity should vary with eKE (or eBE) = what the answer should be.

Do you want me to include the above in the upcoming `circularize_image` PR, or will you make a separate one?

**Comment by DanHickstein** [comment]
I think that we understand the Jacobian reasonably well (though it does confuse me every time!). I'll just need to dig through some of our old discussion threads. 

We should shoot for small PRs, so let's keep these separate.

**Comment by stggh** [comment]
Agreed. Good.

**Comment by DanHickstein** [comment]
Should we just declare that "All angles in PyAbel are measured in radians."? (Editing this into my original post)

This was implied in my original description of angle, but in PyAbel we actually still use degrees in a few places. Though I think that @stggh is about to eliminate them in #195.

**Comment by DanHickstein** [comment]
I'm declaring victory, and closing this issue, since it was incorporated in #214.
