### ISSUE TITLE
Docs not building

### ISSUE THREAD

**Issue by DanHickstein** [PyAbel/PyAbel#193]
@stggh raised this issue via e-mail, not sure if it was particular to his machine. I think that it's a real issue, so migrating it here:

@stggh wrote:

Hi Dan,
             Have you tried building the PyAbel docs lately?

My Linux system gives up:
````
[etalon:.+/VMI/PyAbel/doc]$ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.5.1
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 30 source files that are out of date
updating environment: 30 added, 0 changed, 0 removed
reading sources... [  6%] anisotropy_parameter
Exception occurred:
  File "/home/stg121/Software/Python/anaconda3/lib/python3.5/site-packages/Sphinx-1.5.1-py3.5.egg/sphinx/environment/__init__.py", line 869, in process_images
    type='image', subtype='nonlocal_uri')
TypeError: _warn_node() got an unexpected keyword argument 'type'
The full traceback has been saved in /tmp/sphinx-err-7b3a1f6y.log, if you want to report the issue to the developers.

and the error file:
File "/home/stg121/Software/Python/anaconda3/lib/python3.5/site-packages/Sphinx-1.5.1-py3.5.egg/sphinx/environment/__init__.py", line 869, in process_images
    type='image', subtype='nonlocal_uri')
TypeError: _warn_node() got an unexpected keyword argument 'type'
```

So, the error is generated in `anisotropy_parameter.rst` and appears to be image related.

**Comment by DanHickstein** [comment]
Thanks for catching this! I think that it's also causing problems with readthedocs.org.

No issue on my macbook, but I think that this is because I am using sphinx 1.3, while you are using 1.5. I see a similar error reported here:

https://github.com/sphinx-doc/sphinx/issues/2429

I think that this is related to the code that I inserted to suppress some of the warnings that sphinx was giving us. Now, this has backfired and made an error.

I think that you can safely remove lines 330->332 of doc/conf.py (starts with "def _warn_node"). This should case a lot more warnings from sphinx, but hopefully eliminate the error.

**Comment by DanHickstein** [comment]
Hmmm, actually, I'm not quite sure what is happening with readthedocs.org. Looks like the build is getting killed:
https://readthedocs.org/projects/pyabel/builds/4898605/

Perhaps it is briefly using too much RAM (RTD now limits to 1 GB):
https://github.com/rtfd/readthedocs.org/issues/1712

**Comment by stggh** [comment]
Fixed. Well done @DanHickstein !

**Comment by DanHickstein** [comment]
It's currently dying while building the linbasex example. 

Until we figure out what is going wrong, can we remove this example from the docs? (I.e., take out 
```
.. plot:: ../examples/example_linbasex.py
   :include-source:
```

from `doc/example_linbasex.rst`

Probably we just need to reduce the RAM requirements. Perhaps the ` O2-ANU1024.txt.bz2` image can simply be downsampled from 1024x1024 to 512x512 before being transformed. You can make an account on readthedocs.org and tell it to build the documentation for your fork (be sure to specify the working branch) and see if it works.

**Comment by stggh** [comment]
Yes, I see the errors (and others), which I will take a look at:
```
/home/stg121/Software/Python/VMI/PyAbel/abel/linbasex.py:docstring of abel.linbasex.linbasex_transform:14: WARNING: Inline literal start-string without end-string.
/home/stg121/Software/Python/VMI/PyAbel/abel/linbasex.py:docstring of abel.linbasex.linbasex_transform:31: WARNING: Definition list ends without a blank line; unexpected unindent.
/home/stg121/Software/Python/VMI/PyAbel/abel/linbasex.py:docstring of abel.linbasex.linbasex_transform:64: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/stg121/Software/Python/VMI/PyAbel/abel/linbasex.py:docstring of abel.linbasex.linbasex_transform_full:8: WARNING: Inline literal start-string without end-string.
/home/stg121/Software/Python/VMI/PyAbel/abel/linbasex.py:docstring of abel.linbasex.linbasex_transform_full:25: WARNING: Definition list ends without a blank line; unexpected unindent.
/home/stg121/Software/Python/VMI/PyAbel/abel/linbasex.py:docstring of abel.linbasex.linbasex_transform_full:58: WARNING: Block quote ends without a blank line; unexpected unindent.
```

**Comment by DanHickstein** [comment]
I wouldn't worry too much about fixing all of the warnings. Sphinx in pretty picky about how it recommends the docstrings be formatted, and it's happy to tell you about it. We don't necessarily need to fix all of those :)

But we definitely need to get the build working on readthedocs.org. Currently, our documentation is out-of-date, and won't update until we fix it.

**Comment by stggh** [comment]
Do you plan to [fix](https://github.com/PyAbel/PyAbel/issues/193#issuecomment-278486773) this immediately, or in my `circularize_image` PR?

**Comment by DanHickstein** [comment]
I think that I just succeeded in fixing this by down-sampling the example image used in `example_linbasex.py` from 1024x1024 to 512x512.

I can make a PR, unless you fear that will screw up your future PR.

**Comment by stggh** [comment]
Make a PR. I cannot see a few trivial changes inhibiting my one. ;-)

**Comment by DanHickstein** [comment]
The docs are now building fine! http://readthedocs.org/projects/pyabel/builds/

Declaring victory and closing this issue.
