### ISSUE TITLE
Unable to install "Setup.py"

### ISSUE THREAD

**Issue by nomihaq** [PyAbel/PyAbel#199]
Dear Sir, 
I am unable to install the Setup.py. I am using'Enthought Canopy'. I found the following error

IOError                                   Traceback (most recent call last)
C:\Users\200TW\PyAbel-master\setup.py in <module>()
     42 # see https://stackoverflow.com/questions/458550/standard-way-to-embed-version-into-python-package
     43 VERSIONFILE="abel/_version.py"
---> 44 verstrline = open(VERSIONFILE, "rt").read()
     45 VSRE = r"^__version__ = ['\"]([^'\"]*)['\"]"
     46 mo = re.search(VSRE, verstrline, re.M)

IOError: [Errno 2] No such file or directory: 'abel/_version.py' 

Please help me for the above issue. 

Kind regards, 

Nomi Haq

**Comment by stggh** [comment]
Sorry, about the installation problem. Unfortunately, I am not familiar with `PyAbel` installation for Windows systems. However, just to check, you are running:    `python setup.py install` from inside the `PyAbel-master` directory?

**Comment by DanHickstein** [comment]
That problem is strange. `abel/_version.py` should be present in any version of PyAbel that you downloaded.

How are you trying to install PyAbel? 

If you just want to use PyAbel, rather than hack at the source code, then the install using pip is probably the easiest. Just type this on the command line:
```
pip install PyAbel
```

**Comment by DanHickstein** [comment]
I'm going to close this Issue, since it seems like it has been resolved. We can re-open if that's not the case.
