### ISSUE TITLE
Happy New Year Challenge: Colorized Abel Transform Equation!

### ISSUE THREAD

**Issue by DanHickstein** [PyAbel/PyAbel#203]
I recently read this article about colorized math equations. 
https://betterexplained.com/articles/colorized-math-equations/

I was impressed with their colorized version of the Fourier transform:

![image](https://user-images.githubusercontent.com/1107796/34469361-4c4b76bc-eeda-11e7-9abd-171b0ef45c88.png)

I attempted some thing similar for the forward and inverse Abel transforms. What do you think about the following? ([gist for latex code](https://gist.github.com/DanHickstein/03105bf4ba33b929247492eb2e1fbe9f))

![colorized copy](https://user-images.githubusercontent.com/1107796/34469348-25f425b8-eeda-11e7-939b-37ca07047cf7.png)

Can you do better? Seems like a helpful addition to the PyAbel documentation, or perhaps the forthcoming PyAbel paper (should any journal tolerate such pastel awesomeness :) ).

**Comment by stggh** [comment]
IMO the colorization is too excessive, it may disadvantage persons with color blindness, while the corresponding text could simply reference the appropriate math:

> To reconstruct the 3D object, <math>f(r, z)</math>, add together thin cylindrical shells ...

However, it has a certain **wow** factor, so I am open to the change ;-)

BTW, just out of interest, @DanHickstein how did you write the corresponding markup?

**Comment by stggh** [comment]
Having viewed the method, I am less favourable to the implementation. I can see the some advantages in colourizing online docs, but the LaTeX method prohibits this. Journals usually take the PDF manuscript and convert it to their in-house format, possibly stripping any coioured text.

**Comment by DanHickstein** [comment]
Well, I was more interested if anyone had an alternative one-or-two sentence high-level summary that describes the Abel transform equations. I found the Fourier-transform example to be a really interesting description, and probably really helpful for someone learning about the FT. 

I just took a first crack at describing the Abel transforms in terms of cylindrical shells, but I'm not sure if that's the way that everyone thinks about them. 

And yes, if we wanted to apply colored text to the online docs, we would color the text using markup in the relevant `.rst` file as opposed to latex. Latex was just a place to play with different colors. I adapted the code directly from the [original article](https://betterexplained.com/articles/colorized-math-equations/).

Those colors could probably be better optimized for the colorblind, but they are fairly distinguishable for simple Deuteranopia. (You can use [Color Oracle](http://colororacle.org/) to temporarily switch your display between the various versions of color-blindness.)

**Comment by stggh** [comment]
Sorry, I missed your key point. I interpret the forward Abel transform as the integrated intensity of the object along a line of sight (along the x-axis, for a given (y, z) position), which is [Eq (1)](https://github.com/PyAbel/PyAbel/issues/203#issue-285317487) in polar coordinates. Not easy to describe I agree. I like the [Pretzler](https://doi.org/10.1515/zna-1991-0715) terse approach, that provides no physical interpretation:
![screenshot-20180102145030-390x492](https://user-images.githubusercontent.com/10932229/34473908-8c39eb30-efcc-11e7-9df0-8b75ae917bdb.png)

Alternatively, [Eppink's Reconstruction methods](https://doi.org/10.1017/CBO9780511535437.004) provides a detailed description, but the description is not easy to summarize into only a few sentences.

**Comment by DanHickstein** [comment]
Hmmm, interesting. If only those equations has a little more color :). 

Okay, I can close this issue.
