### ISSUE TITLE
Circularization reference

### ISSUE THREAD

**Issue by DanHickstein** [PyAbel/PyAbel#210]
@stggh, I received an e-mail from a PyAbel user, saying that they found your circularization algorithm really useful for their research. So, good work on that! 

Am I correct in thinking that the method is basically what you describe in this paper: http://aip.scitation.org/doi/abs/10.1063/1.4981024

If so, you may want to include a reference to that paper in the `abel.tools.circularize_image` docstring. Both to get some citations for your paper, but also to let people know where they can get more information on the method/approach.

**Comment by stggh** [comment]
I appreciate the positive feedback, while also acknowledging the team effort to make the method available.

The algorithm is a simplified version, linear radial scaling vs angle, of what is described in the paper, however, the citation is relevant, and I will include it in the docs.

**Comment by DanHickstein** [comment]
This will be addressed by #211, so closing this issue.
