### ISSUE TITLE
Make direct operate on a "odd" grid

### ISSUE THREAD

**Issue by DanHickstein** [PyAbel/PyAbel#213]
While thinking about #211, where we are realizing the the Hansen-Law algorithm operates on an "even" grid (see #39 for grid explanation), I realized that the Direct method also defaults to an "even" grid if the `r` parameter is not specified.

This is because of the factor of 0.5 in [line 51](https://github.com/PyAbel/PyAbel/blob/master/abel/direct.py#L51) of direct.py:
```python
r = (np.arange(n) + 0.5)*dr
```
I think that we can change the grid be be "odd" if we just remove the factor of 0.5. Here is a comparison of the direct inverse transform to an analytical gaussian (assuming an "odd" grid). Left is the current behavior, right is the behavior with the factor of 0.5 removed, which is way better: 
![image](https://user-images.githubusercontent.com/1107796/37357151-45708ac0-26ad-11e8-84e0-e664e0c1fa18.png)

**Comment by DhrubajyotiDas** [comment]
I'm pretty surprised by how sensitive these transforms are to an even/odd grid.

**Comment by stggh** [comment]
@DanHickstein you are correct!

For curveA `profile3`:
```python
n = 101
f = abel.tools.analytical.TransformPair(n=n, profile=3)
f.r[0] = 1.0e-16   # profile3 requires 0 < r <= 1
 :
dr = abel.direct.direct_transform(f.abel, r=f.r)
dr[0] = dr[1]  # rig first value
```
![a](https://user-images.githubusercontent.com/10932229/37372971-d8c49436-2768-11e8-87ff-cdd85945f0e3.png)

**Comment by stggh** [comment]
Apart from `direct` grid not appearing to like `r[0] = 0`
Set to `1.0e-16` in this example:

```python
n = 1001
n2 = n//2
name = 'dribinski'

source = abel.tools.analytical.SampleImage(n, name=name).image
half = source[:, n2:]

halfshift = interpolation.shift(half, (0, -1/2))

# proj = abel.hansenlaw.hansenlaw_transform(halfshift, direction='forward')
proj = abel.direct.direct_transform(half, direction='forward')

projshift = interpolation.shift(proj, (0, -1/2))

hl = abel.hansenlaw.hansenlaw_transform(projshift)
di = abel.direct.direct_transform(proj)

plt.plot(half[n2], label='source')
plt.plot(hl[n2], label='hansenlaw')
plt.plot(di[n2], label='direct')
plt.axis(xmin=0, xmax=60, ymin=0)
```
![recycle2](https://user-images.githubusercontent.com/10932229/37374348-d1aa1df0-276e-11e8-83e1-a4016d5aabb8.png)

@DanHickstein's change is good. `hansenlaw` still favours -1/2 pixel (grid) shift.

Note, not yet sure whether `hansenlaw` shift needs to be `(-1/2, -1/2)` or `(0, -1/2)` until radial profile tests.

**Comment by stggh** [comment]
@DanHickstein you should generate a PR for the code bug-fix for `direct`. 

There may be an issue/special case for `f(r=0)`, which also maps to the transform `out[0]`?
line 51+:
```python
        r = np.arange(n)*dr    # +0.5 factor removed, see #213
        r[0] = 1.0e-16  # otherwise method may fail
```

**Comment by DanHickstein** [comment]
This was incorporated in #214.
