### ISSUE TITLE
Last call for 0.8.0 release!

### ISSUE THREAD

**Issue by DanHickstein** [PyAbel/PyAbel#220]
We haven't released a new version of PyAbel on PyPI in a very long time. We've also closed all of the issues related to version 0.8. (except for #216 and #218, which are addressed by #219). 

So, I think that we are ready to increment the version (https://github.com/PyAbel/PyAbel/pull/219) and make a new release. But, I thought that I should make sure that nobody else had any changes that they wanted to make before we make the next release.

**Comment by stggh** [comment]
I am good for the increment.

**Comment by DanHickstein** [comment]
Okay, looks like we are good to v0.8!
