### ISSUE TITLE
Mention that the BASEX function size has a 1/e full-width of 2 pixels

### ISSUE THREAD

**Issue by DanHickstein** [PyAbel/PyAbel#223]
Somewhere in the docs, we should mention that the basex functions have a 1/e half-width of 1 pixels, or a full-width of 2 pixels. This probably causes a small amount of smoothing to the input image, and should be mentioned somewhere.

**Comment by DanHickstein** [comment]
So, we can say that the 1/e^2 full width is 2 pixels?

**Comment by MikhailRyazanov** [comment]
Say where? :–)

Although the [1/_e_<sup>2</sup> width](https://en.wikipedia.org/wiki/Beam_diameter#1/e2_width) is used for Gaussian beams in optics, I do not think that it is a good way to characterize the basis functions (~the resolution). FWHM is probably a much more familiar and less shape-dependent characteristic.

And since the new code works with any `sigma` values, the 1/_e_<sup>2</sup> width is really "2 _σ_ pixels".

**Comment by DanHickstein** [comment]
I was just thinking that we should mention something about the width of the basis functions in the BASEX docstring. Actually, the docstring still says that nbf must be set to zero. This has been fixed, right?

**Comment by DanHickstein** [comment]
yeah, that looks good. But isn't the FWHM of a Gaussian function 2.35*sigma? We are using a different definition of the gaussian, so we might want to explicitly state that the FWHM is 1.18*sigma.

**Comment by MikhailRyazanov** [comment]
FWHM ≈ 2.35 SD. "Normal" Gaussian is defined as exp[−<i>x</i><sup>2</sup>/(2<i>σ<sup>2</sup></i>)], such that its SD = _σ_. But we have exp[−2<i>x</i><sup>2</sup>/<i>σ<sup>2</sup></i>], so _σ_ here is a "width parameter", and SD = _σ_/2. And actually this "width parameter" is for the basis functions themselves, which are _Gaussian-like_ for _k_ &Gt; 1.

We should say all this in the method documentation, but probably not in the code.

**Comment by DanHickstein** [comment]
Yeah, it seems like a good place to mention this is in the docstring under the sigma parameter, right? I guess I'm fine to mention it wherever, but since we are using a non-standard definition for sigma, then we should just indicate this somewhere that people can see it.

**Comment by MikhailRyazanov** [comment]
#241 should address the `sigma` questions. “How it works” has a reference to the basis-functions definition, and I have added to “PyAbel improvements” the explicit expression for their approximate form and how their widths and spacing are related to the `sigma` parameter. There is also a picture in “BASEX: computational details / Intensity correction”.

I suppose that people will read the method documentation before using the code, so mentioning these details in the docstring (which describes the _programming interface_) is unnecessary.

**Comment by DanHickstein** [comment]
Explaining this in the docs in fine with me! I think we can close this issue, since your #241 addresses it to my satisfaction.
