### ISSUE TITLE
linbasex intensity scaling

### ISSUE THREAD

**Issue by stggh** [PyAbel/PyAbel#224]
`linbasex` intensity scaling is incorrect, it does not agree with the other methods, and as @DanHickstein has found appears to be dependent on the number of Legendre polynomials orders.

**Comment by DanHickstein** [comment]
> The required scaling factor is 1/2r

Okay, problem solved! Nice work!

> I have pushed the 1/2r factor, linbasex.py line 267, and set the default smoothing to zero, in the current PyAbel PR #232.

Great, some motivation for us to merge #232 :)

> linbasex transform alignment, relative to the other methods

That's annoying that there is this small shift. Can you subtract the 2D transform (say linbasex versus three-point) so that we can see if the shift is symmetric, or just in horizontal?

**Comment by stggh** [comment]
I am looking into the `linbasex` code, which, I must admit I never fully understood during the transfer process of Thomas Geber's jupyter notebook code :-(. However, now it is starting to make sense. It looks possible to switch to `1/2`-image transforms, and associated basis calculations. In the process I hope to track down any subpixel offset issues. Although, my track record for this, with other methods (`hansenlaw`) is not good ;-)

**Comment by DanHickstein** [comment]
Sounds exciting! Changing to half-image transforms sounds like a good step, and a better understanding (and comments!) of the code should help.

**Comment by DanHickstein** [comment]
So, it looks like the intensity scaling was fixed in #232. @stggh, should we close this ancient issue?

**Comment by stggh** [comment]
Hi @DanHickstein and @MikhailRyazanov, happy New Year. I am travelling at the moment, domestic, in South Australia until Jan 11. 

Yes, it is fine to close this issue.

**Comment by DanHickstein** [comment]
Great! Thanks for letting me know. 

I hope that you are having great fun on your travels!
