### ISSUE TITLE
`hedp.math.abel` direct and inverse Abel implementation

### ISSUE THREAD

**Issue by rth** [PyAbel/PyAbel#23]
Move  the  [hedp.math.abel](https://github.com/luli/hedp/blob/master/hedp/math/abel.py) implementation  to PyAbel .  Still thinking what names would be appropriate.

**Comment by DanHickstein** [comment]
Yes, this is a great idea and very useful to have the forward Abel transform for testing thing out. Since this is a "direct" numerical implementation of the analytical formula, should it live in ``abel.direct.???``

**Comment by DanHickstein** [comment]
I'm excited to see this implemented in PyAbel. How does it compare to the more sophisticated methods? Just way more noise along the center?

**Comment by DanHickstein** [comment]
I think that we can close this issue, since the direct implementation is now included. I made a separate issue (https://github.com/PyAbel/PyAbel/issues/58) to look into the difference between the Python and Cython results.
