### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by DanHickstein** [PyAbel/PyAbel#237]
I noticed that the Readme still says that PyAbel required "PyAbel requires Python 2.7 or 3.3-3.5.". Clearly this hasn't been updated in a while.

Also, we might want to update the image with something more interesting, like Fig. 1 from the upcoming paper.

**Comment by stggh** [comment]
*python version*
  Good point. IMO it would be nice to drop 2.7 (to save baggage) and move to 3.6+. We may then use f-strings for formatting.

*image*
  Depends on "not published elsewhere" journal requirements.

Can PR #235 be merged? I would like to:
 (1) Change `three_point` to Oliver Haas' #229 [version](https://github.com/oliverhaas/PyAbel) 
 (2) Update the docs in `linbasex` (although, I have not yet started this process ...)

**Comment by DanHickstein** [comment]
Reading through some [journal policies](https://aip.scitation.org/rsi/info/policies), I would think that including a figure in the PyAbel readme would be acceptable, because the PyAbel github site is not peer reviewed and not copyrighted, so doesn't constitute prior publication. I'd like to include our image in the readme:

![pyabel14labels](https://user-images.githubusercontent.com/1107796/48970223-1b477b80-efc7-11e8-9feb-c614d6cadab6.png)

**Comment by DanHickstein** [comment]
Okay, these update have been made in #238! :)  Closing this issue.
