### ISSUE TITLE
Cite paper in README.rst

### ISSUE THREAD

**Issue by DanHickstein** [PyAbel/PyAbel#250]
Now that our paper is on the ArXiv, we should include a link in the readme and suggest that people cite it: https://arxiv.org/abs/1902.09007

I suggest that we keep the Zenodo link on there too, since it provides a way to cite the exact version of PyAbel that is used and it will keep up to date in the future as more people contribute.

**Comment by MikhailRyazanov** [comment]
Now we should cite the “real” RSI article too. Even Google Scholar already knows about it.

**Comment by DanHickstein** [comment]
#262 has the RSI reference. Closing this.
