### ISSUE TITLE
Upload PyAbel to PyPi

### ISSUE THREAD

**Issue by rth** [PyAbel/PyAbel#26]
At some point in the future it would be nice to [upload](https://python-packaging-user-guide.readthedocs.org/en/latest/distributing/#uploading-your-project-to-pypi) PyAbel on PyPi, so it can be simply installed with,
     
    pip install abel

**Comment by DanHickstein** [comment]
Agreed. Once we are done with the major changes and have something that works reliably, we should upload to PyPi. We should be able to do this fairly soon.

**Comment by DanHickstein** [comment]
Should we do this sooner rather than later in order to save the name "abel" for our project? It would be a shame to have somebody else steal the best name!

**Comment by rth** [comment]
I agree, it would be a shame to start looking for a new name, again...  For now we can probably upload the last stable release. @DanHickstein  would you have time to do that? I think uploading a [Python wheel](http://pythonwheels.com/) is good practice, although someone would need to spend time looking into it and I'm not sure if that's useful in our case.  Otherwise just a plain `tar.gz` will do great.

**Comment by DanHickstein** [comment]
I finally got around to trying this. I think that I was successful!  (Though it listed it as 0.7.0, and really it's more like 0.6.x, but close enough for a first try I suppose.)

https://pypi.python.org/pypi/PyAbel/0.7.0

**Comment by rth** [comment]
Great, thanks for doing this! 

I can confirm that `pip install PyAbel` now works. So if you want we could indicate this in the readme as the preferred method of installation (and leave the `python setup.py develop` line for people wanting to play with the code).

We'll have to figure out what kind of description it would need as it does not seem to like Markdown in `README.md` so much, but it's a start! Version 0.7.0 is fine (it must take the version from `setup.py`), it's more a `0.7.0-alpha` but not a `0.6.x` since there were backward incompatible changes from `0.6.0`, I think  (see http://semver.org/).

**Comment by DanHickstein** [comment]
Yes, I feel good having released PyAbel into the wild! :)

semver.org gives us extra flexibility when we are in version 0:
```Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.```

Release 1.0 is scary:

```Version 1.0.0 defines the public API. The way in which the version number is incremented after this release is dependent on this public API and how it changes.```

And yes, we should probably leave the version in setup.py (which gets it from ``abel/_version.py``) as, for example, ``0.7.0-alpha`` until we are ready for the true release. 

I think that the work-around for the README.md issue is here: https://coderwall.com/p/qawuyq/use-markdown-readme-s-in-python-modules

**Comment by stggh** [comment]
pip install also works on Ubuntu 15.10.  Nice work.

There appears to be no `examples` directory?
>locate abel | grep hansen
>/usr/local/lib/python2.7/dist-packages/abel/hansenlaw.py 
> cd /usr/local/lib/python2.7/dist-packages/abel
>ls
>analytical.py   benchmark.py   hansenlaw.py   io.py    math.pyc   _version.py
>analytical.pyc  benchmark.pyc  hansenlaw.pyc  io.pyc   tests      _version.pyc
>basex.py        direct.py      __init__.py    lib      tools.py
>basex.pyc       direct.pyc     __init__.pyc   math.py  tools.pyc

**Comment by rth** [comment]
@stggh  Yes, that's normal. `pip` essentially downloads the package and runs `python setup.py install`, since examples is not part of the PyAbel Python package (i.e. it cannot be imported as `abel.examples` ) it is not installed. That's the usual behaviour, say when one installs `matplotlib` the [`example/` folder](https://github.com/matplotlib/matplotlib) is not installed, and the user is simply invited to check it out if he is interested.

**Comment by DanHickstein** [comment]
I suppose that this makes it more important to point users to the examples directory on the github page from the readme and/or the wiki.

**Comment by rth** [comment]
Closing this issue as PyAbel was uploaded to PyPi by @DanHickstein .
