### ISSUE TITLE
Center/origin consistency

### ISSUE THREAD

**Issue by MikhailRyazanov** [PyAbel/PyAbel#263]
Let's discuss the issue raised in https://github.com/PyAbel/PyAbel/pull/257#issuecomment-505319466 about the conventions related to image coordinates. There are actually two problems:
1. Some places use “origin” and some use “center” to refer to the same thing, and some use “center” to refer to different things.
2. Some places use the (row, column) convention, as for matrix indices, counting from the upper left corner, while some use (_x_, _y_) — in the opposite order and counting from the _bottom_ left corner.

### `center`

[README.rst](https://github.com/PyAbel/PyAbel/blob/master/README.rst)
uses “center” and “adopts the "television" convention, where IM[0,0] refers to the upper left corner of the image”.

[abel/transform.py](https://github.com/PyAbel/PyAbel/blob/master/abel/transform.py)
`Transform` uses `center` more as a verb (how/where _to center_ the image) and the (row, column) convention:
https://github.com/PyAbel/PyAbel/blob/a5d4f11615957d46145f2e3a42725f16783cb56b/abel/transform.py#L130-L136

[abel/tools/center.py](https://github.com/PyAbel/PyAbel/blob/master/abel/tools/center.py)
`find_center()` uses `center` for several different things: the parameter actually selects the _method_, and in
https://github.com/PyAbel/PyAbel/blob/a5d4f11615957d46145f2e3a42725f16783cb56b/abel/tools/center.py#L30-L31
one instance means the geometric center of the matrix, while the other means the symmetry axis/plane location.
The result is in the (row, column) format.
(And, by the way, the `square` parameter is not used and probably should be deleted.)

`center_image()` — same as in `Transform` above, with the same problems as in `find_center()`.

`set_center()` uses the `center` parameter for coordinates in the (row, column) format.

`find_center_by_...()` are called from `find_center()` and use the same conventions. Except that
https://github.com/PyAbel/PyAbel/blob/a5d4f11615957d46145f2e3a42725f16783cb56b/abel/tools/center.py#L318-L322
returns (col, row) instead of (row, col) — apparently a **bug**.

[abel/tools/circularize.py](https://github.com/PyAbel/PyAbel/blob/master/abel/tools/circularize.py)
`circularize_image()` uses the `center` parameter to select the _method_ or to pass the coordinates as (row, column).

### `origin`
[abel/tools/circularize.py](https://github.com/PyAbel/PyAbel/blob/master/abel/tools/circularize.py)
`circularize` internally uses `origin` as (_x_, _y_) from bottom left:
https://github.com/PyAbel/PyAbel/blob/a5d4f11615957d46145f2e3a42725f16783cb56b/abel/tools/circularize.py#L212-L220
which might be confusing and is probably unnecessary, since afterwards this is swapped again:
https://github.com/PyAbel/PyAbel/blob/a5d4f11615957d46145f2e3a42725f16783cb56b/abel/tools/circularize.py#L235-L236

[abel/tools/polar.py](https://github.com/PyAbel/PyAbel/blob/master/abel/tools/polar.py)
`reproject_image_into_polar()` and `index_coords()` use `origin` as “a tuple of (x0, y0) relative to the bottom-left image corner” and “center” for the geometric center of the matrix.

[abel/tools/vmi.py](https://github.com/PyAbel/PyAbel/blob/master/abel/tools/vmi.py)
`angular_integration()` has the `origin` parameter defined as
https://github.com/PyAbel/PyAbel/blob/a5d4f11615957d46145f2e3a42725f16783cb56b/abel/tools/vmi.py#L31-L33
but then uses it as
https://github.com/PyAbel/PyAbel/blob/a5d4f11615957d46145f2e3a42725f16783cb56b/abel/tools/vmi.py#L62-L63
while `abel.tools.polar.reproject_image_into_polar()` (see above) actually expects (_x_, _y_) instead of (row, column), although indeed from the bottom left corner. So this is also a **bug**, either in the documentation or in the code.

`Distributions` and associated functions use `origin` in the (row, column) format and “center” for the geometric center of the matrix.

### Other considerations
[`scipy.ndimage.center_of_mass()`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.center_of_mass.html) returns coordinates as matrix indices, that is, (row, column) for 2D images.

[`matplotlib.pyplot.imshow()`](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.imshow.html) uses the `origin` parameter to select the vertical-axis orientation, which, I think, is a poor name choice (the actual origin (0, 0) can be put anywhere using the `extent` parameter). However, its default value corresponds to PyAbel image orientation, so it does not need to be used explicitly. Otherwise, “center” in Matplotlib means the plot center.

Using `coord = (row, col)` allows to write `IM[coord]` to access `IM[row, col]`.

## Proposal
1. Use the matrix (row, column) convention everywhere.
2. Use the word “origin” for the coordinates of the center/axis of symmetry.
3. Use the word “center” for the geometric center of the matrix and as a verb for “centering” an image (that is, bringing its “origin” to its “center”).
4. Maybe rename `center` to `method` in some `...center...` functions. However, some of them also accept coordinates, which are definitely not a “method”, so maybe use some other word?

**Comment by stggh** [comment]
A nice synopsis. I agree with all of your proposal points. Good work.

`method=(a, b)` is the "use the coordinates method".

**Comment by DanHickstein** [comment]
@MikhailRyazanov, thanks for the incredible analysis!

I agree that we should fix these bugs and make things clearer.

1. I agree that we should use (row, column) everywhere.
2. The mathematical definition of "origin" is "a fixed point from which coordinates are measured, as where axes intersect." So, I think that it's use is appropriate. We are trying to define where the mathematical (0,0) point lies within the (potentially) arbitrarily located matrix. So, "origin" seems appropriate. (So does "center" in my opinion, but origin also seems fine.)
3. I'm a little confused about what you mean by the "geometric center" of the matrix. Are you referring to the (rows//2, cols//2) element of the matrix and the "center" of the matrix? I think that I agree with you here, I just need an example of your proposed usage.
4. In some of the centering functions, we are basically overloading the "center" keyword to support both the (rows, cols) origin location as well as selecting one of the automatic centering methods. In my opinion, the direct entering of the origin is the primary usage, so I would likely leave this keyword as "center" (or, in your proposal, switch to "origin") and not change it to "method", since, in my opinion, directly entering the origin is the most likely behavior. 

Anyway, I want to see these changes made - you are on the right track.

**Comment by MikhailRyazanov** [comment]
@DanHickstein,

2. Well, technically, “origin” refers to the coordinate system, not to the distribution itself. But since we define our Abel transforms in a specific coordinate system, linked to the symmetry elements of the distribution, this correspondence is obviously implied. The only problem with “center” is that, as I mentioned, this word by itself is ambiguous, so we either need to always say “center of ...” or chose another word. Since everybody seems to agree with “origin”, let's then use it.
3. Yes, the middle row and column. “Middle” is another word, but I'm not sure that we can say “the middle of the matrix/image”...
4. What about renaming `find_center()` to `find_origin()` and its argument `center` to `method` (it is described as “this determines how the <s>center</s> origin should be found” and does not take coordinates)? Then in `center_image()` and `Transform` we can rename `center` to `origin` — it takes either the origin coordinates or how to find the origin. I mean, both `origin=(123, 234)` and `origin="com"` would make sense.

If needed, we can maintain backwards compatibility until, say, v0.9, by making aliases for renamed functions and adding old parameter names at the end of function signatures (such that calls with positional arguments continue to work without problems, but calls with named arguments raise a `DeprecationWarning` and use values from the old parameters).

Is anybody willing to work at least on the bugs (2 are mentioned above, but maybe there are more ­— I did not look very carefully) and converting everything to (row, column)? I guess that people who wrote the code understand it better than I do. I currently have a more or less nicely working pBasex-like method, for which I would like to have this “center”/“origin” consistency settled, but I do not have enough free time to work on both this issue and the new method.

**Comment by stggh** [comment]
I will be in France for the next two weeks.  I am happy to look at this on my return, after 23rd.  There is also a separate issue for `linbasex`, the transforms do not align if the smoothing is turned off.

**Comment by MikhailRyazanov** [comment]
Since #267 that addressed all the mentioned problems is already merged, I'm closing this issue.

**Comment by DanHickstein** [comment]
Awesome! Well done Mikhaikl!
