### ISSUE TITLE
Enable use of up/down asymmetric images

### ISSUE THREAD

**Issue by DhrubajyotiDas** [PyAbel/PyAbel#27]
To summarize some of the discussion which already took place in https://github.com/PyAbel/PyAbel/issues/14, currently PyAbel presupposes the `raw_data` being transformed has up/down symmetry, i.e., `f(r,-z) = f(r,z)`. This is mostly because in photoelectron spectroscopy, images are theoretically up/down symmetric, and so a lot of reconstruction algorithms make this approximation in order to gain better signal-to-noise. 

The underlying BASEX algorithm does not require the `raw_data` being transformed to have up/down asymmetry. The only requisite symmetry is the lateral `f(-r) = f(r)` condition, which is common to all Abel inversion algorithms. This symmetry condition is a feature of many experimental data sets, such as images of coflow and counterflow flames, or even in photoelectron spectroscopy images, where hot spots on the detector might break up/down symmetry. Therefore it would be useful to enhance PyAbel to perform in the more general no-up-down-symmetry situation.

My fork of PyAbel, [PyroBASEX](https://github.com/DhrubajyotiDas/pyroBASEX) has already made the changes to the basis-set generation and implementation codes to account for this situation. The overall changes can be summrized as: `n` has been decomposed into `n_horz` and `n_vert`, and the relevant `nbf_horz` and `nbf_vert` basis functions are generated for each direction independently. The basis functions in the vertical direction do not need to be forward-transformed, and therefore their calculation is very quick. 

As far as incorporating the code changes into PyAbel goes, most of it ought to be straightforward. To preserve code legibility in PyAbel, it might be useful to have two separate internal basis-set generation routines. From the end-user's perspective, a `vertical_symmetry=<True, False, or unspecified>` will need to be added to whatever function call is being made to do the transform. Additionally, the format of the specification of the `center` of the raw data will need to be updated to handle a vector in addition to a tuple. 

One user-interface concept is the one discussed in https://github.com/PyAbel/PyAbel/issues/14

* `vertical_symmetry=True` -> Use PyAbel code
* `vertical_symmetry=False` or `unspecified` -> Use pyroBASEX code

Examples

1)  `n=500` -> Use pyroBASEX, `n_horz, n_vert = 500,500`
2)  `n=500, vertical_symmetry=True` -> Use PyAbel as usual
3)  `n=(500,500), vertical_symmetry=True` -> Same as above, convert `n` from tuple to integer `n=500`
4)  `n=(500,500)` -> Same as 1)
5) `n=(500,498)` -> Use pyroBASEX, `n_horz, n_vert = 500,498`
6) `n=(500,498), vertical_symmetry=True` -> Enlarge `raw_data` to `(500,500)`, then proceed as 3)

**Comment by rth** [comment]
This looks great! A minor comment could be that for point 6) after the transform is performed, the padded zeros are removed to get the orginal shape of `raw_data`.

**Comment by DhrubajyotiDas** [comment]
Agreed. 

Another situation that just came to mind - what if `raw_data` is bigger than the user-specified values of `n`? Do we crop `raw_data` centered around `center` to make a new shape with dimensions equal to `n`?

**Comment by rth** [comment]
I agree, that would be consistent with the way it works now.

**Comment by DanHickstein** [comment]
I'm excited about including the asymmetric option, and now that @rth has made the major user interface changes, I think that we are good to move forward with this.

I would think that it would be safer to make decisions about the symmetric versus asymmetric transform based solely on the ``vertical_symmetry`` keyword. Having the transform function act differently based on the tuple versus the integer arguments for ``n`` is subtle and might be confusing. Is there any problem with just using ``vertical_symmetry`` and throwing an error if ``n`` does not match? 

Currently raw data is cropped if it's too large, which seems like what most users would want. We could consider a warning if the image is being clipped and suggest that the user select a larger basis set. For now I would say to just clip the image.

**Comment by DhrubajyotiDas** [comment]
With PR #54, BASEX can now handle images that do not have up/down symmetry. This issue has been resolved.

**Comment by DanHickstein** [comment]
Great work on this @DhrubajyotiDas!
