### ISSUE TITLE
Discretization of the grid for the Abel transform

### ISSUE THREAD

**Issue by sancarv1** [PyAbel/PyAbel#272]
I am working with the Abel method to treat images from the combustion process; the image resolution is 1024x1024 pixels and the method selected was BASEX, I split the image in two thus the input size image for the BASEX method is 1024X512. I would like to ask  the following questions:

![image](https://user-images.githubusercontent.com/61046956/75020061-45217380-5492-11ea-8e54-7134246fa325.png)

1- How is the discretization of the grid for the Abel transform of these images (case A or Case B)?

2- do you think I have to transform this even image size to odd image size (add a fake central row, as an average of the neighbor rows, then remove it after the processing)? If I decide to do this, how would spatial discretization be (case A or Case B)?

**Comment by DanHickstein** [comment]
Hi @sancarv1! Thanks for your questions.

1) PyAbel uses case B (odd full-width images). https://github.com/PyAbel/PyAbel/blob/master/README.rst#conventions

2) When you are talking about a half-image (your 1024x512 image), then the number of pixels can be even or odd. It's only when we are talking about the full-width image that it matters if the number of pixels is even or odd. Are you certain that your experiment places the center of symmetry exactly between the center-most pixels? The simplest thing to do is probably to just use the `abel.Transform` class and use of of the automatic centering functions. Or, you can manually set the center to be between two pixels.

**Comment by sancarv1** [comment]
Thank you for your reply.

You are right, my experiments are not located in the image center; it is displaced. Furthermore, they aren't symmetrical for this reason;  I split the image in two and analyze each one side separately. My question now is:

1-I have to add a fake central row to each side, as an average of the neighbor rows, then remove it after the processing.

**Comment by sancarv1** [comment]
> Hi @sancarv1! Thanks for your questions.
> 
> 1. PyAbel uses case B (odd full-width images). https://github.com/PyAbel/PyAbel/blob/master/README.rst#conventions
> 2. When you are talking about a half-image (your 1024x512 image), then the number of pixels can be even or odd. It's only when we are talking about the full-width image that it matters if the number of pixels is even or odd. Are you certain that your experiment places the center of symmetry exactly between the center-most pixels? The simplest thing to do is probably to just use the `abel.Transform` class and use of of the automatic centering functions. Or, you can manually set the center to be between two pixels.



> Hi @sancarv1! Thanks for your questions.
> 
> 1. PyAbel uses case B (odd full-width images). https://github.com/PyAbel/PyAbel/blob/master/README.rst#conventions
> 2. When you are talking about a half-image (your 1024x512 image), then the number of pixels can be even or odd. It's only when we are talking about the full-width image that it matters if the number of pixels is even or odd. Are you certain that your experiment places the center of symmetry exactly between the center-most pixels? The simplest thing to do is probably to just use the `abel.Transform` class and use of of the automatic centering functions. Or, you can manually set the center to be between two pixels.

Thank you for your reply.

You are right, my experiments are not located in the image center; it is displaced. Furthermore, they aren't symmetrical for this reason; I split the image in two and analyze each one side separately. My question now is:

1-I have to add a fake central row to each side, as an average of the neighbor rows, then remove it after the processing.

**Comment by sancarv1** [comment]
> Hi @sancarv1! Thanks for your questions.
> 
> 1. PyAbel uses case B (odd full-width images). https://github.com/PyAbel/PyAbel/blob/master/README.rst#conventions
> 2. When you are talking about a half-image (your 1024x512 image), then the number of pixels can be even or odd. It's only when we are talking about the full-width image that it matters if the number of pixels is even or odd. Are you certain that your experiment places the center of symmetry exactly between the center-most pixels? The simplest thing to do is probably to just use the `abel.Transform` class and use of of the automatic centering functions. Or, you can manually set the center to be between two pixels.

Thank you for your reply.

You are right, my experiments are not located in the image center; it is displaced. Furthermore, they aren't symmetrical for this reason; I split the image in two and analyze each one side separately. My question now is:

1-I have to add a fake central row to each side, as an average of the neighbor rows, then remove it after the processing.

**Comment by DanHickstein** [comment]
> You are right, my experiments are not located in the image center; it is displaced. 
So, why not just re-center the image so that the center of symmetry is at the true center?

>  I split the image in two and analyze each one side separately
If you use [`abel.Transform`](https://pyabel.readthedocs.io/en/latest/abel.html#module-abel.transform), the two sides are transformed separately by default.

If you would like, you could post an example image and I could provide an example of how you might recenter the image and analyze both sides. I think that PyAbel already has the functionality you need built into the high-level `abel.Tranform` class and you probably don't need to deal with the low-level transform functions directly.

**Comment by sancarv1** [comment]
> > You are right, my experiments are not located in the image center; it is displaced.
> > So, why not just re-center the image so that the center of symmetry is at the true center?
> 
> > I split the image in two and analyze each one side separately
> > If you use [`abel.Transform`](https://pyabel.readthedocs.io/en/latest/abel.html#module-abel.transform), the two sides are transformed separately by default.
> 
> If you would like, you could post an example image and I could provide an example of how you might recenter the image and analyze both sides. I think that PyAbel already has the functionality you need built into the high-level `abel.Tranform` class and you probably don't need to deal with the low-level transform functions directly.

Thank you so much for your help, as you can see, the image resolution is (1024X1024) but the axis is not located at the half of the image, the axis is located at (:, 464). Moreover,  the image is not symmetric. Finally,  I want to apply the Basex method (direction= inverse).

![image](https://user-images.githubusercontent.com/61046956/75240257-576a1d00-57c4-11ea-95f4-4cddc6a91bc3.png)

**Comment by DanHickstein** [comment]
Hi @sancarv1,

Your data looks interesting. If you want to post the raw image (or e-mail it to me at danhickstein@gmail.com) I can show you in detail how you can do the inverse transform. 

But, I would suggest that you do something like this:

```python
inverse_abel = abel.Transform(original_image, origin=(512, 464), symmetry_axis=None, 
                              direction='inverse', method='basex').transform
```

That will shift the image so that the center is at column 464. Also, I included `symmetry_axis=None` to make it explicit that you are transforming the left and the right sides of the image separately and re-combining them into a single image, which is what you want. Note that this text can be omitted since `symmetry_axis=None` is the default behavior.

**Comment by DanHickstein** [comment]
@sancarv1 sent me the raw data via e-mail, and wrote: 

> Thank you so much for your help and your time. Attached you can find the raw data, and the other hand, I would ask you if could do the same with the following function (Currently, I am using it to transform my images):

> abel.basex.basex_transform(KL_Rslice, sigma = 8, reg = V_reg,  correction=True, basis_dir=None, dr=1, verbose=True, direction=u'inverse')

> Or I have to use that function that you suggest to me to transform the whole image in one step. 

The `abel.Transform` class lets you re-center the image, split the image into two halves, complete the abel transform, and stitch the image back together in one step. So, it seems like the more convenient option for you. You can, of course, enable or disable these behaviors as you like.

Here is the script that I used to transform your image:

```python
import numpy as np
import matplotlib.pyplot as plt
import scipy.io
import abel

# convert from matlab to .txt
# data_dict = scipy.io.loadmat('KL.mat')
# original_image = data_dict['KL']
# np.savetxt('KL.txt', original_image)

original_image = np.loadtxt('KL.txt')

center_col = 464

fig, axs = plt.subplots(1, 2, figsize=(8,4))
axs[0].set_title('Original image')
axs[0].imshow(original_image)
axs[0].axvline(center_col, ls='dashed', color='w')

inverse_abel = abel.Transform(original_image, origin=(512, center_col), symmetry_axis=None, direction='inverse', method='basex', transform_options=dict(sigma=8)).transform

axs[1].set_title('Inverse Abel Transform')
axs[1].imshow(inverse_abel, clim=(0, 0.0015))

plt.show()
```
and here is the result:
![transform](https://user-images.githubusercontent.com/1107796/75413871-07827780-58e4-11ea-92b5-8768b007d7e4.png)

[Here is a [gist with the raw data](https://gist.github.com/DanHickstein/6d5a4f97c57f3d1b1e1da825da500954), converted to .txt from matlab format.]

Is there a reason that you want to call the basex function directly? Of course, you can call it if you want. Here, you can check out the code for what the `abel.Transform` class is doing: https://github.com/PyAbel/PyAbel/blob/master/abel/transform.py#L402

Coming back to your original question, I don't think that you need to worry about adding an extra column due to any discretization effects. I would expect that the uncertainty in the center position in your data is on the order of a few pixels, so I'd expect that you can safely ignore the sub-pixel effects.

**Comment by sancarv1** [comment]
> @sancarv1 sent me the raw data via e-mail, and wrote:
> 
> > Thank you so much for your help and your time. Attached you can find the raw data, and the other hand, I would ask you if could do the same with the following function (Currently, I am using it to transform my images):
> 
> > abel.basex.basex_transform(KL_Rslice, sigma = 8, reg = V_reg,  correction=True, basis_dir=None, dr=1, verbose=True, direction=u'inverse')
> 
> > Or I have to use that function that you suggest to me to transform the whole image in one step.
> 
> The `abel.Transform` class lets you re-center the image, split the image into two halves, complete the abel transform, and stitch the image back together in one step. So, it seems like the more convenient option for you. You can, of course, enable or disable these behaviors as you like.
> 
> Here is the script that I used to transform your image:
> 
> ```python
> import numpy as np
> import matplotlib.pyplot as plt
> import scipy.io
> import abel
> 
> # convert from matlab to .txt
> # data_dict = scipy.io.loadmat('KL.mat')
> # original_image = data_dict['KL']
> # np.savetxt('KL.txt', original_image)
> 
> original_image = np.loadtxt('KL.txt')
> 
> center_col = 464
> 
> fig, axs = plt.subplots(1, 2, figsize=(8,4))
> axs[0].set_title('Original image')
> axs[0].imshow(original_image)
> axs[0].axvline(center_col, ls='dashed', color='w')
> 
> inverse_abel = abel.Transform(original_image, origin=(512, center_col), symmetry_axis=None, direction='inverse', method='basex', transform_options=dict(sigma=8)).transform
> 
> axs[1].set_title('Inverse Abel Transform')
> axs[1].imshow(inverse_abel, clim=(0, 0.0015))
> 
> plt.show()
> ```
> 
> and here is the result:
> ![transform](https://user-images.githubusercontent.com/1107796/75413871-07827780-58e4-11ea-92b5-8768b007d7e4.png)
> 
> [Here is a [gist with the raw data](https://gist.github.com/DanHickstein/6d5a4f97c57f3d1b1e1da825da500954), converted to .txt from matlab format.]
> 
> Is there a reason that you want to call the basex function directly? Of course, you can call it if you want. Here, you can check out the code for what the `abel.Transform` class is doing: https://github.com/PyAbel/PyAbel/blob/master/abel/transform.py#L402
> 
> Coming back to your original question, I don't think that you need to worry about adding an extra column due to any discretization effects. I would expect that the uncertainty in the center position in your data is on the order of a few pixels, so I'd expect that you can safely ignore the sub-pixel effects.

Hi DanHickstein.

Thank you for your time, the results look very good and  I can safely ignore the sub-pixel effects. Finally, I would ask you again about the discretization of the grid for your inverse Abel transform respect to the axis ( this is even image size).

**Comment by DanHickstein** [comment]
Hi @sancarv1,

The discretization of the pixel grid *is* is sub-pixel effect. Basically you are considering the difference between your center being located at 464 or 464.5. For your data, I would argue that you only can determine the center to within a few pixels, so the difference between an "even" or "odd" grid makes no difference. 

While we (the PyAbel developers) have spent a lot of time worrying about whether the first pixels is x=0 (odd) or x=0.5 (even), this detail is of little interest for 99% of users of the Abel transform. And, we have already taken this detail into account via the centering algorithms and the way that the `abel.Transform` method takes care of splitting the image into quadrants and combining them after the transform. So, almost all users shouldn't need to worry about details like the pixel grid.

**Comment by sancarv1** [comment]
> Hi @sancarv1,
> 
> The discretization of the pixel grid _is_ is sub-pixel effect. Basically you are considering the difference between your center being located at 464 or 464.5. For your data, I would argue that you only can determine the center to within a few pixels, so the difference between an "even" or "odd" grid makes no difference.
> 
> While we (the PyAbel developers) have spent a lot of time worrying about whether the first pixels is x=0 (odd) or x=0.5 (even), this detail is of little interest for 99% of users of the Abel transform. And, we have already taken this detail into account via the centering algorithms and the way that the `abel.Transform` method takes care of splitting the image into quadrants and combining them after the transform. So, almost all users shouldn't need to worry about details like the pixel grid.



> @sancarv1 sent me the raw data via e-mail, and wrote:
> 
> > Thank you so much for your help and your time. Attached you can find the raw data, and the other hand, I would ask you if could do the same with the following function (Currently, I am using it to transform my images):
> 
> > abel.basex.basex_transform(KL_Rslice, sigma = 8, reg = V_reg,  correction=True, basis_dir=None, dr=1, verbose=True, direction=u'inverse')
> 
> > Or I have to use that function that you suggest to me to transform the whole image in one step.
> 
> The `abel.Transform` class lets you re-center the image, split the image into two halves, complete the abel transform, and stitch the image back together in one step. So, it seems like the more convenient option for you. You can, of course, enable or disable these behaviors as you like.
> 
> Here is the script that I used to transform your image:
> 
> ```python
> import numpy as np
> import matplotlib.pyplot as plt
> import scipy.io
> import abel
> 
> # convert from matlab to .txt
> # data_dict = scipy.io.loadmat('KL.mat')
> # original_image = data_dict['KL']
> # np.savetxt('KL.txt', original_image)
> 
> original_image = np.loadtxt('KL.txt')
> 
> center_col = 464
> 
> fig, axs = plt.subplots(1, 2, figsize=(8,4))
> axs[0].set_title('Original image')
> axs[0].imshow(original_image)
> axs[0].axvline(center_col, ls='dashed', color='w')
> 
> inverse_abel = abel.Transform(original_image, origin=(512, center_col), symmetry_axis=None, direction='inverse', method='basex', transform_options=dict(sigma=8)).transform
> 
> axs[1].set_title('Inverse Abel Transform')
> axs[1].imshow(inverse_abel, clim=(0, 0.0015))
> 
> plt.show()
> ```
> 
> and here is the result:
> ![transform](https://user-images.githubusercontent.com/1107796/75413871-07827780-58e4-11ea-92b5-8768b007d7e4.png)
> 
> [Here is a [gist with the raw data](https://gist.github.com/DanHickstein/6d5a4f97c57f3d1b1e1da825da500954), converted to .txt from matlab format.]
> 
> Is there a reason that you want to call the basex function directly? Of course, you can call it if you want. Here, you can check out the code for what the `abel.Transform` class is doing: https://github.com/PyAbel/PyAbel/blob/master/abel/transform.py#L402
> 
> Coming back to your original question, I don't think that you need to worry about adding an extra column due to any discretization effects. I would expect that the uncertainty in the center position in your data is on the order of a few pixels, so I'd expect that you can safely ignore the sub-pixel effects.

Hi Dan Hickstein,

I am trying to use the following script:

inverse_abel = abel.Transform(original_image, origin=(512, center_col), symmetry_axis=None, direction='inverse', method='basex', transform_options=dict(sigma=8)).transform

But, I got this error:

*** TypeError: __init__() got an unexpected keyword argument 'origin'

I am using the PyAbel 0.8.3. Would you have any idea about this error?

**Comment by DanHickstein** [comment]
Hi @sancarv1,

We changed the keyword from `center` to `origin` very recently. So, you can simply use the `center` keyword.

**Comment by DanHickstein** [comment]
Hi @sancarv1,

Did you get everything working? I'd like to close this issue unless you have other questions.

Thanks!

**Comment by sancarv1** [comment]
> Hi @sancarv1,
> 
> Did you get everything working? I'd like to close this issue unless you have other questions.
> 
> Thanks!

Hi @DanHickstein,

Everything is working, you can close this issue.

Thank you so much for your help.

Best wishes.

**Comment by DanHickstein** [comment]
Excellent - glad everything is working for you!

Please feel free to open another issue if you have any more questions or suggestions.
