### ISSUE TITLE
GUI example without "bases" directory

### ISSUE THREAD

**Issue by MikhailRyazanov** [PyAbel/PyAbel#275]
Our GUI example (`example_GUI.py`) has a hard-coded `'bases'` directory for saving/loading basis sets. It is present in the default installation, but if a user runs this example from some other directory, it fails quite confusingly: some errors are printed to the console, but the GUI itself says
```
<whatever> Abel transform:
```
and nothing else happens; even worse, for `basex` it says
```
basex: first time calculation of the basis functions may take a while ...
```
and that “a while” takes _forever_ if the user does not pay attention to the console (which might be even hidden by the GUI window)...

We should treat this situation more reasonably, but I don know exactly how:

1. Just create the directory if it does not exist.
2. If it does not exist, show a clearly noticeable error in the GUI.
3. If it does not exist, ask the user whether to create it.
4. If it does not exist, add a warning to `self.text` and use `basis_dir=None` (that is, run without saving/loading).

The problem with all these variants is that some methods do not need `basis_dir`, so they run just fine without `bases`, and there is no reason to bother the user about it.

P.S. I'm opening a separate issue instead of commenting in #247, since this is a minor, but annoying flaw. Solving it now is easier than making a new “good” GUI, but its solution can be reused there later.

**Comment by stggh** [comment]
A good find. I favour solution 4. since I imagine the main user case would be just to run the example. In its present form not much analysis can be done or saved.

**Comment by MikhailRyazanov** [comment]
Then something like
```
dir = 'bases'
if not os.path.isdir(dir):
    dir = None
    self.text.insert(... some warning message ...)

...Transform(... basis_dir=dir ...)
```
can be a reasonable solution. It does not check that the directory is writable (which is, again, not always needed), but at least avoids the most likely problem.

**Comment by stggh** [comment]
Yes, looks good.

**Comment by DanHickstein** [comment]
I would have gone with option #1, since I think that the example_GUI might be the way that some users primarily use PyAbel. But, in its current state, I expect the example_GUI is probably used as just an example. So, options 1 and 4 are both acceptable to me. When we make the GUI awesome, it should certainly create it's own directory and save basis sets there for future reuse. If you implement option 4, please include a comment in the code so that we remember to switch to creating the directory.

**Comment by DanHickstein** [comment]
Oh, and thanks for catching this!!

**Comment by MikhailRyazanov** [comment]
OK, done in #277.
