### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by DanHickstein** [PyAbel/PyAbel#292]
We haven't released a new version since last summer. Probably time to release another one, since we've made many improvements and bug-fixes.

I can release v0.8.4 in a few days, unless there are objections.

**Comment by MikhailRyazanov** [comment]
I'm going to do a PR for #276, and then it will be indeed good time to release.

**Comment by DanHickstein** [comment]
Sounds good. I can hold off until that gets merged.

**Comment by MikhailRyazanov** [comment]
I'm done, so go ahead!

It's probably also good time to review README and CONTRIBUTING again and make final edits if needed.

Important things not to forget:
1. Change “Unreleased” in the CHANGELOG to the new version and date.
2. Mention in the release notes the `center` → `origin` change and that (row, column) is now used everywhere.

**Comment by MikhailRyazanov** [comment]
... and about reviewing README...
I think, the methods list (https://github.com/PyAbel/PyAbel/blame/master/README.rst#L32-L48) should be unindented because currently GitHub [renders it](https://github.com/PyAbel/PyAbel/blob/master/README.rst#transform-methods) as a quote (I did correct this problem in CONTRIBUTING, but overlooked it in README).

**Comment by DanHickstein** [comment]
Huzzah, we released v0.8.4! (our first release in over 2 years, oops!)

https://github.com/PyAbel/PyAbel/releases
https://pypi.org/project/PyAbel/

**Comment by MikhailRyazanov** [comment]
Thanks, @DanHickstein!
I think, the idea of copying the changelog entry is great. I have reformatted it slightly in the release description — hopefully, this wouldn't break anything...

**Comment by MikhailRyazanov** [comment]
@DanHickstein, this can be closed now, I guess?

**Comment by DanHickstein** [comment]
Yup! Thanks :)
