### ISSUE TITLE
Need a help to save the output file 

### ISSUE THREAD

**Issue by kfxnightmare2** [PyAbel/PyAbel#301]
In Example: Hansen–Law xenon i want to save the  output_text 
i ran the code and i seems to be working properly and i was able to save the output plot
is there way to save this dat file

**Comment by DanHickstein** [comment]
Hi there! Are you basically trying to save a text file of the transformed image?

You can try adding something like:

```python
np.savetxt('abel_transform.txt', recon)
```

towards the end of the example script.

Here is a modified example script that saves the Abel transformed image as a text file using the line above:

https://gist.github.com/DanHickstein/1a63ac94621027784603ec59ce636854

**Comment by DanHickstein** [comment]
I think that this issue has been addressed, so closing this issue.
