### ISSUE TITLE
Inverse Abel's transform with already-integrated data

### ISSUE THREAD

**Issue by spinang** [PyAbel/PyAbel#304]
I have been working on a plasma physics-based experiment and dealing with some flux recordings arranged as a matrix of n observations (rows) and m channels (columns). Starting from each row, which consists of m line integrals along pre-defined lines of sight, whose spatial orientation is known in terms of polar coordinates (radius and angle), I would use the PyAbel package to reconstruct the original, spatial 2D profile from these line integrals. Is it possible?

Just to give you an idea, this is a piece of code I wrote from scratch:

```python
from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt
import os
import abel
# Upload data
rootDirectory = Path(os.path.dirname(os.path.realpath(__file__))).parent
shot          = '42830'
fileName      = '\Shot_' + shot + '_Ordered_By_Impact_Parameter_Filtered_68_Channels.csv'
fullPath      = str(rootDirectory) + '\Results\Files' + fileName
wholeData     = np.loadtxt(fullPath, delimiter = ",")
nRows, nCols  = np.shape(wholeData)
# Mean by columns
nSamples     = 10000
if nSamples > nRows:
    nSamples = 500
selectedData = wholeData[0:nSamples,]
inputData    = np.mean(selectedData, axis = 0)
# Run the inversion
outputData = abel.direct.direct_transform(inputData, direction = "inverse", correction = True)
# Visualisation
plt.plot(outputData)
plt.show()
```

Apart from trivial operations for data loading and selection (I do not want to use all the rows momentarily, therefore I decide to pick just a reduced number of rows and average them so that inputData is the 1D input vector for the algorithm), I do not know whether the transformation is properly executed. Consider that the 1D array that the transformation outputs ought to be "rotated" around its axis to create a surface.

If you may help to figure this out, I would really appreciate (so far, I have not found anything useful in the documentation, but that will be just my fault). Thanks in advance!

**Comment by DanHickstein** [comment]
Hi @spinang!

I'm a little confused about exactly what your data corresponds to. Is there a previous paper that shows how the data is collected, or can you provide a drawing or something? Is the experiment indeed taking a projection of a 3D object as shown in this figure: https://user-images.githubusercontent.com/1107796/48970223-1b477b80-efc7-11e8-9feb-c614d6cadab6.png It sounds like the data is perhaps recorded in polar coordinates instead of cartesian, which would differ slightly from that figure.

For your example code, we would need the data file to really play with it. If it's okay with you, perhaps you can upload that too so that we can run your example. You could use a [Github Gist  ](https://user-images.githubusercontent.com/1107796/48970223-1b477b80-efc7-11e8-9feb-c614d6cadab6.png) to upload the file and then include the link here. Or, if you'd rather not share your experimental data, prepare some sort of basic example that we can look at.

**Comment by spinang** [comment]
Hello @DanHickstein, thanks for replying me so soon.
I am sorry if my comment was unclear, let me try to explain it better. As far as I understood, to perform the inverse Abel's transform the package relies on 2D or even 1D profiles, such as Gaussian curves as shown in many examples throughout the documentation. The problem I have been trying to solve is slightly different, because the data I have at disposal are ALREADY line integrals through an unknown, spatial profile I have to rebuild. To help you to understand, I have reported a picture that shows the scenario of my interest:
![Screenshot 2020-09-24 180858](https://user-images.githubusercontent.com/11614831/94171090-1e487700-fe91-11ea-875d-ecb8fc398bc0.png)
Each chord is a line projection fully identified by an angle and a radius (or impact parameter) and each column within my data set is essentially a chord (i.e., each of the m columns). Thereby, each pair (row, column) determines the value of a line integral at a given time, for a given chord. What I would like to do is to feed these rows into the algorithm for Abel's inversion and obtain the spatial profile again or, at least, a planar representation that ought to be symmetrically "rotated" around its axis to get the final surface. I am sorry I cannot provide you the data, because they are reserved for ongoing research purposes at the moment.

Please let me know if there are further details you need and I will try to give you them at the earliest opportunity.

**Comment by stggh** [comment]
@spinang note in the `PyAbel` example image, the 3D distribution has cylindrical symmetry. The 2D projection is the integrated intensity through the 3D distribution along the x-axis. i.e. each pixel of the 2D projection is similar to the chord measurement that you describe. 

![image](https://user-images.githubusercontent.com/10932229/94207448-fc8bd600-ff0a-11ea-8acf-3e9ec8cce860.png)

Where is the cylindrical symmetry axis of your distribution? Are your measurements relative to a fixed position of the symmetry axis?

**Comment by DanHickstein** [comment]
@spinang, 

Does your object have cylindrical or spherical symmetry? At least cylindrical symmetry is a requirement of the Abel transform. 

Also, for each time, you say that you have many chords (projections at a specific radius and angle). In our typical situation, we also have projections, but they are all at the same angle and at various, evenly spaced radii.

**Comment by DanHickstein** [comment]
Hi @spinang, I hope that you found a solution to your problem. I'm going to close this issue for now for bookkeeping purposes. If you'd like to continue the discussion, just post here and I'll re-open the issue, or start a new Issue with a new question. I hope you are enjoying using PyAbel!
