### ISSUE TITLE
Update testing

### ISSUE THREAD

**Issue by MikhailRyazanov** [PyAbel/PyAbel#307]
We probably need to include the recently released Python 3.9 in the unit tests. And also make some clean-up there. For example, this:
https://github.com/PyAbel/PyAbel/blob/afc54ee18c50e68bd55700ce9b0e0ac0f07aadd8/.travis.yml#L5-L12
apparently tests _only_ Python 3.8, but does so _twice_.

And do we really need 32-bit tests for Windows Miniconda3?
https://github.com/PyAbel/PyAbel/blob/afc54ee18c50e68bd55700ce9b0e0ac0f07aadd8/appveyor.yml#L16-L27
Maybe they can be removed? (It [seems](https://docs.conda.io/en/latest/miniconda.html) that Miniconda with Python 3.9 is not available yet, so it should be added later...)

**Comment by DanHickstein** [comment]
You can never be too certain that your software works on Py3.8 - always good to test twice :). 

But yes, you're right, probably we can swap one of those for a 3.9 test.

And I think that you're correct that most people using Py3 are on 64-bit. Maybe some people need 32-bit to interface with legacy hardware drivers? I feel like I've run into this issue before. But, I'm fine to drop all but one of the 32-bit test (Py 2.7) in the interest of faster appveyor builds and less complication.

**Comment by MikhailRyazanov** [comment]
Yes, keeping the 32-bit Python 2.7 is useful for legacy stuff. I'm not sure that 32-bit drivers would have Python 3 interfaces, but we can leave one test just in case and remove another.

By the way, Ubuntu Xenial is rather old (released 2016-04-21, its support will end in half a year), it might be also a good idea to use the [latest LTS release](https://releases.ubuntu.com) (Focal Fossa) at least for Python 3.9.

Would you do the updates? I could, but the testing of this testing :–) might require deeper interaction with Travis and AppVeyor (I don't know what they have available and how it is called)...

**Comment by DanHickstein** [comment]
I opened #309 to update the testing.
