### ISSUE TITLE
Jacobian for angular_integration

### ISSUE THREAD

**Issue by Turin508** [PyAbel/PyAbel#312]
I think that the Jacobian provided when converting from Cartesian to polar coordinates should always be true in the function call below. The option provided to the function abel.tools.vmi.angular_integration would then differentiate between the Jacobian for the integration of a 3D object in spherical coordinates (r^2\sin\theta), and the integration of a 2D object in polar coordinates (r).

https://github.com/PyAbel/PyAbel/blob/7bc6672ec3b6e56ba7146f37a8aa5bdd9883d7b0/abel/tools/vmi.py#L64-L65

As a test, I have simulated data using the following code:

```
import numpy as np

image_data = np.zeros([324,324]).astype('int')
for i in range(10):
	radii = np.random.rand(10000) * 100
	theta = np.random.rand(10000) * 2 * np.pi
	np.add.at(image_data, (np.rint(161.5 + (radii * np.cos(theta))).astype('int'),\
            np.rint(161.5 + (radii * np.sin(theta))).astype('int')), 1)
```

Briefly, the code generates a 324x324 image, with an isotropic distribution of uniform intensity between a radius of 0 and 100. It follows that the radial distribution of the image should have a radial distribution with a uniform distribution. However, running the following code does not give the correct result with Jacobian=Tue or Jacobian=False:

```
import matplotlib.pyplot as plt

radius, intensity = abel.tools.vmi.angular_integration(image_data, Jacobian=True)
intensity = intensity / np.sum(intensity)

plt.figure()
plt.plot(radius, intensity, label='Jacobian = True')

radius, intensity = abel.tools.vmi.angular_integration(image_data, Jacobian=False)
intensity = intensity / np.sum(intensity)

plt.plot(radius, intensity, label='Jacobian = False')

plt.legend()
plt.show()
```
The (normalised) radial distributions obtained are shown below.

![image](https://user-images.githubusercontent.com/43828594/107031130-9b71ea00-67a9-11eb-8d9d-7e792a15c25c.png)

If instead I make a copy of the angular_integration function, and change the Jacobian=Jacobian on line 65 to Jacobian=True, and call the function with `angular_integration(image_data, Jacobian=False)`, I instead get the expected result.

![image](https://user-images.githubusercontent.com/43828594/107031531-3c60a500-67aa-11eb-9a8a-54ea33a0f669.png)

**Comment by stggh** [comment]
@Turin508 - thanks for an excellent description of the issue, example code, and resolution!

`polar.py` applies the Jacobian  <math>&times;r</math>, line 95:
```python
    if Jacobian:
        output *= r_i[:, np.newaxis]
```
and `vmi.py` <math>&times;r sin&theta;</math>, line 70:
```python
   if Jacobian:  # × r sinθ
        polarIM *= R * np.abs(np.sin(T))
```

> I think that the Jacobian provided when converting from Cartesian to polar coordinates should always be true in the function call below. The option provided to the function abel.tools.vmi.angular_integration would then differentiate between the Jacobian for the integration of a 3D object in spherical coordinates (r^2\sin\theta), and the integration of a 2D object in polar coordinates (r).

I agree.

**Comment by DanHickstein** [comment]
This is a good discussion! Yes, I think that I agree that the `abel.vmi.angular_integration` function is missing the capability to properly apply the Jacobian for 2D images. VMI images are 3D, so I believe this is what we are targeting.

I think that it would be a nice idea to include this case as well.

But, I think that applying no Jacobian at all is also an interesting case. Basically, it amounts to taking the average intensity at a given radius. Kinda like a line-out across the center of the image.

So, we have three cases:

"3D", image is slide through 3D object, jacobian is r^2 * sin(theta)
"2D", image is just a 2D image, jacobian is r * sin(theta)
"1D", we want a line of the 2D image, jacobian is 1

**Comment by stggh** [comment]
Thanks for the clear explanation @DanHickstein.

So, a change for the variable `Jacobian` from `bool` to `str` (`1D`, `2D`, `3D`)?

**Comment by DanHickstein** [comment]
Yeah, that's kinda what I was thinking. I could see the simplicity argument of just keeping it as a bool and only implementing the 3D and 2D cases....

**Comment by MikhailRyazanov** [comment]
@DanHickstein, for averaging we in fact have
https://github.com/PyAbel/PyAbel/blob/7bc6672ec3b6e56ba7146f37a8aa5bdd9883d7b0/abel/tools/vmi.py#L79
So I would say that a more sensible approach is to have `angular_integration()` for integration and `average_radial_intensity()` for averaging, but both of them must have a reasonably named “dimensionality” argument to distinguish between treating the data as just a 2D image (using ∫r dθ for integration and ∫dθ / 2π for averaging) and as a slice of a 3D distribution (using ∫2π r sin θ dθ for integration and  ∫2π r sin θ dθ / 4π for averaging). That way we can straighten the logic and keep backward compatibility by declaring `Jacobian` deprecated.

**Comment by MikhailRyazanov** [comment]
Well, I've checked (see #318) how all this currently behaves and should say that `angular_integration` is in fact wrong in both cases:
* For `Jacobian=True`, it misses a factor of π. For example, for an image filled with “1”, it returns 4r<sup>2</sup> instead of 4πr<sup>2</sup>.
* For `Jacobian=False`, as reported here, misses a factor of r. That is, instead of integrating, it returns the average (over polar angles) multiplied by 2π.

I was trying to do what is described in my previous comment, but realized that it would be impossible to maintain backward compatibility for `angular_integration()` called without its `Jacobian` argument (the default use case). Another possibility is to leave `angular_integration()` as is and deprecate it entirely, adding correctly implemented `angular_integration_3D()` and `angular_integration_2D()` instead. So @DanHickstein and @stggh, what do you think? Is making `angular_integration()` produce correct results more important than keeping it backward compatible?

**Comment by DanHickstein** [comment]
> Another possibility is to leave angular_integration() as is and deprecate it entirely, adding correctly implemented angular_integration_3D() and angular_integration_2D()

I think that this is the way forward. It clearly communicates to users that a change has been made, but doesn't break their previous code.

**Comment by stggh** [comment]
@MikhailRyazanov it good that a person of your intellectual calibre is on the `PyAbel` case, to track down these errors. 

I agree, with the new function names, and with the depreciation of the old version functions.

**Comment by MikhailRyazanov** [comment]
@Turin508, could you please the new functions from PR #319 to make sure that they do what you expect?
(You can just replace the `abel/tools/vmi.py` file in your installed PyAbel with [this one](https://github.com/MikhailRyazanov/PyAbel/blob/tools.vmi/abel/tools/vmi.py); click “Raw” there to get the file itself.)

**Comment by Turin508** [comment]
@MikhailRyazanov the new functions behave as I would expect. Thank you for your efforts in fixing the issue.

Whilst running the tests, I found that if the image (IM) provided to the functions has an integer datatype, the following error is raised (using NumPy 1.19.5):

```
Traceback (most recent call last):
  File "temp.py", line 15, in <module>
    radius, intensity = angular_integration_2D(image_data)
  File "temp.py", line 95, in angular_integration_2D
    return radial_intensity('int2D', IM, origin=origin, dr=dr, dt=dt)
  File "vmi.py", line 69, in radial_intensity
    polarIM *= R
numpy.core._exceptions.UFuncTypeError: Cannot cast ufunc 'multiply' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'
```

Here are three potential solutions:

1. The user could be required to provide IM with the float datatype
2. IM could be set as type float at some point prior to multiplying by R on line 69
3. polarIM *= R could be replaced with polarIM = polarIM * R

**Comment by DanHickstein** [comment]
I like #3. Lots of users are going to be suppling integer images since they are loading data from a camera. We're going to take their int data and silently return float data, but I think that this is unlikely to cause an issue for the majority of users.

**Comment by MikhailRyazanov** [comment]
@Turin508, @DanHickstein, the actual problem was that `reproject_image_into_polar()` was conserving the type of the array. This really makes no sense for integers anyway (it is supposed to do interpolation), so I've made it always return `float` data (hopefully, a reasonable choice). Now all the affected functions should work correctly with integer data, but please recheck again, just in case.

**Comment by Turin508** [comment]
@MikhailRyazanov that seems to do the trick, and I prefer your solution than those I listed above. Having now looked at the scipy.ndimage.map_coordinates documentation, I would agree that having a float output is a reasonable choice.

**Comment by MikhailRyazanov** [comment]
Thank you! I'll wait for @stggh's review and then merge #319.

**Comment by MikhailRyazanov** [comment]
OK, PR #319 is now merged, so this issue seems to be solved.
