### ISSUE TITLE
Example code and writeup for single row transform?

### ISSUE THREAD

**Issue by jwbrooks0** [PyAbel/PyAbel#313]
Hello,

I'm trying to use your library to perform an Able inverse transform on a single row of data.  When I try your transform function, I get the error "ValueError: Data must be 2-dimensional.   To transform a single row use the individual transform function."  However, I don't know what it means by using "the individual transform function". Does this mean I need to call each of your sub function methods individually?   Is there a writeup or sample code somewhere to do this?  Thanks for any help you're willing to provide.  

Here is an example dataset to play with (I just generated an undersampled Gaussian pulse).  
data = np.array([3.72665317e-06, 2.98114854e-05, 1.97402198e-04, 1.08199208e-03,
       4.90907774e-03, 1.84365420e-02, 5.73142686e-02, 1.47485652e-01,
       3.14152498e-01, 5.53904627e-01, 8.08412832e-01, 9.76641408e-01,
       9.76654147e-01, 8.08444466e-01, 5.53940752e-01, 3.14181183e-01,
       1.47502966e-01, 5.73224925e-02, 1.84396685e-02, 4.91003830e-03,
       1.08223203e-03, 1.97451125e-04, 2.98196522e-05, 3.72777133e-06])

**Comment by stggh** [comment]
Hi John, thanks for playing with PyAbel.  

As the error message states you should use the individual transform methods for transforming 1D data,
      e.g.  `trans = abel.dasch.three_point_transform(data)`

See the [docs](https://pyabel.readthedocs.io/en/latest/abel.html#module-abel.dasch) for each of the alternative transform functions.

However, your data set also needs to be in the correct form for PyAbel:
(1) the right side of a symmetric function 
(2) an odd number of sample points

Here is an example:
```python
import abel
import numpy as np
import matplotlib.pyplot as plt

def gauss(r, r0, sigma):
    return np.exp(-(r-r0)**2/sigma**2)

c2 = 51  # an odd-number of points
sigma = c2/5   # 1/e-width of the Gaussian
r = np.arange(c2)

# 1-D Gaussian function ------------------
data = gauss(r, 0, sigma)

# Abel transform using the three_point method ---------
trans = abel.dasch.three_point_transform(data)

# plot ------------------
ratio_1d = np.sqrt(np.pi)*sigma   # intensity scaling

plt.plot(data, label='1D Gaussian')
plt.plot(trans*ratio_1d, label=r'transform $\times \sqrt{\pi} \sigma$')
plt.legend()

plt.show()

```
![image](https://user-images.githubusercontent.com/10932229/112226044-c349de00-8c81-11eb-8e1a-dd41adcd5f13.png)

Feel free to ask more questions.

**Comment by DanHickstein** [comment]
Hi @jwbrooks0!

There are also a few more examples in the PyAbel examples folder dealing with 1D functions:
* https://github.com/PyAbel/PyAbel/blob/master/examples/example_direct_gaussian.py
* https://github.com/PyAbel/PyAbel/blob/master/examples/example_basex_gaussian.py

@stggh, for the individual transform methods, I believe that the number of points can be any number (even or odd). It's only when we are talking about the full-width (symmetric) image do we say that PyAbel "requires" an odd number of pixels for the image width. When using the individual transform methods, it's only important to realize that the first pixel corresponds to x=0, not x=0.5. Of course, this is a tiny effect in most situations where data is adequately sampled.

But yes, important to point out that, when using the individual transform methods, you shouldn't be providing them with the full (symmetric) gaussian function, but only the right side.

**Comment by stggh** [comment]
@DanHickstein
> it's only important to realize that the first pixel corresponds to x=0

Yes, you are correct.

**Comment by jwbrooks0** [comment]
Perfect!  Thank you both very much.
