### ISSUE TITLE
Remove rebase info in Contributing.rst

### ISSUE THREAD

**Issue by DanHickstein** [PyAbel/PyAbel#317]
In middle of our [CONTRIBUTING.rst](https://github.com/PyAbel/PyAbel/blob/master/CONTRIBUTING.rst) file, we have a section titled "BEFORE MERGING": https://github.com/PyAbel/PyAbel/blob/master/CONTRIBUTING.rst#before-merging

In this section, we provide information about how to rebase a PR. I've always struggled to rebase my PRs, and I guess the advantage is that the PR ends up getting merged with only a single commit. For the past year or so, GitHub has changed the "Merge" button to provide options to either (1) squash and merge, (2) create a merge commit, or (3) rebase and merge. I think that the squash and merge option makes it pretty easy to reduce any PR to a single commit while pressing the merge button.

![image](https://user-images.githubusercontent.com/1107796/113807094-b8328b80-9720-11eb-9f58-d841d5d0c676.png)

So, two questions:

1) Should "squash and merge" be our default merging behavior? It seems that others have concluded that this is the best practice: https://rietta.com/blog/github-merge-types/

2) If we are squashing and merging, then we don't need to ask contributors to endure the pain of rebasing their PRs and we can also remove that section from CONTRIBUTING.rst.

**Comment by MikhailRyazanov** [comment]
I'm almost sure that we don't want automatic squashing, as this combines all changes into a single commit, thus losing all history of incremental changes, which might be sometimes important in retrospective analysis. I mean, for repositories with thousands of pull requests, squashing might be desirable to keep the history clean (without intermediate edits), but this is not our case, and if we ever get a PR with every single letter as separate commits, :–) we can ask the author to combine them in a more appropriate way manually...

Regarding rebasing, the reason for doing it is explained in the first paragraph of the mentioned “See [this wiki](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request) for more information.” Basically, it ensures that there will be no merge conflicts and that the PR author can actually see and test the final results locally (which is better that only relying on our CI unit tests). In principle, it is not really required if the changes are completely unrelated (thus rebasing is just desirable, not strictly required), but recommending it doesn't harm in any case.

**Comment by DanHickstein** [comment]
Okay, what you are saying makes sense. I think that big projects like suashing so that they can have one commit per PR and the summary message for that commit will relate to the mission of the whole PR, and not just be whatever the last commit happens to be, like "fixed those typos". 

But yes, I think that you are right that we can keep everything the way it is for now.
