### ISSUE TITLE
IMPORTANT: cleaned up git repository 

### ISSUE THREAD

**Issue by rth** [PyAbel/PyAbel#32]
As discussed in the the issue #20 , and PR #28  I have cleaned up git history to remove large files. This was done cloning the parent `PyAbel/PyAbel` repo, identifying unused large files in the history, and cleaning them up with  [BGF repo cleaner](https://rtyley.github.io/bfg-repo-cleaner/), then pushing back the changes. This worked well and allowed to reduce the size of the repo from ~60MB to 11MB at present.

The problem is that the **forks still have those large files in [the history](https://github.com/PyAbel/PyAbel/network)** and if we merge a PR from one of those forks to `PyAbel/PyAbel`, this will reintroduce the large files in the git history again. 

The simplest solution (if you don't have any changes pending in your fork) is as follows  [from BGF manual],
> At this point, you're ready for everyone to ditch their old copies of the repo and do fresh clones of the nice, new pristine data. It's best to delete all old clones, as they'll have dirty history that you don't want to risk pushing back into your newly cleaned repo. 

So personally I will remove my fork on github, delete local clones, then fork again and make a fresh clone, since I don't have any significant changes at present. @DanHickstein maybe that would also work for you.

Alternatively, as indicated by the [github guide to delete sensitive data](https://help.github.com/articles/remove-sensitive-data/), 
>Tell your collaborators to [rebase](https://git-scm.com/book/en/v2/Git-Branching-Rebasing), not merge, any branches they created off of your old (tainted) repository history. One merge commit could reintroduce some or all of the tainted history that you just went to the trouble of purging.

So this could maybe work for @DhrubajyotiDas (although it might be difficult because there was so many changes) ? I mean, I don't know which way you would prefer to work #27, but just please take this issue under consideration. Or maybe you can perform the same cleaning operation as was done on the parent PyAbel (see below)? Or do another fork (don't know if one can have multiple forks under different names)? Not sure what's best here.

Thanks,

The exact procedure to clean files from the history I used is given below,

0.  Clone the repo with the `--mirror` option,
       
        git clone --mirror git@github.com:PyAbel/PyAbel.git
1. [Identify large files](http://blog.jessitron.com/2013/08/finding-and-removing-large-files-in-git.html)
2. This produces the following list,

        24024497 BASEX/data/basex_basis_1000x1000.npy
        24024451 basisALL.npy
        24024451 BASEX/data/basex_basis_1000x1000_all.npy
        16016417 BASEX/data/basex_basis_1000_orig.npy
        16016417 BASEX/data/basex_basis_1000_500_orig.npy
        16016383 examples/basex_basis_1001_500.npy
        14628900 additional_files/original_matlab_implementation.zip
        8016817 examples/basex_basis_501_250.npy
        8010002 additional_files/basis1000pr_1.txt
        8010002 additional_files/basis1000_1.txt
        8008080 basis1000.npy
        8008080 additional_files/basis1000.npy
        5763040 examples/data/Xenon_800_nm.raw
        5763040 example_data/Xenon_800_nm.raw
        2881656 examples/data/Xenon_800_nm.tif
        2881656 example_data/Xenon_800_nm.tif
        1289378 basex/data/ascii/dan_basis1000pr_1.bst.gz
        1289378 abel/data/ascii/dan_basis1000pr_1.bst.gz
        1289378 BASEX/data/ascii/dan_basis1000pr_1.bst.gz
        1267472 basex/data/ascii/original_basis1000pr_1.txt.gz
        1267472 abel/data/ascii/original_basis1000pr_1.txt.gz
        1267472 BASEX/data/ascii/original_basis1000pr_1.txt.gz
3. So the executed command were,

        java -jar bfg.jar --delete-files basex_basis_1000x1000.npy PyAbel.git
        java -jar bfg.jar --delete-files basisALL.npy PyAbel.git
        java -jar bfg.jar --delete-files basex_basis_1000x1000_all.npy PyAbel.git
        java -jar bfg.jar --delete-files basex_basis_1000_orig.npy PyAbel.git
        java -jar bfg.jar --delete-files basex_basis_1000_500_orig.npy PyAbel.git
        java -jar bfg.jar --delete-files basex_basis_1001_500.npy PyAbel.git
        java -jar bfg.jar --delete-files original_matlab_implementation.zip PyAbel.git
        java -jar bfg.jar --delete-files basis1000pr_1.txt PyAbel.git
        java -jar bfg.jar --delete-files basis1000_1.txt PyAbel.git
        java -jar bfg.jar --delete-files basis1000.npy PyAbel.git
        java -jar bfg.jar --delete-files Xenon_800_nm.raw PyAbel.git
        java -jar bfg.jar --delete-files Xenon_800_nm.tif PyAbel.git
        java -jar bfg.jar --delete-files dan_basis1000pr_1.bst.gz PyAbel.git
        java -jar bfg.jar --delete-files dan_basis1000_1.bst.gz PyAbel.git
        java -jar bfg.jar --delete-files original_basis1000pr_1.txt.gz PyAbel.git
        java -jar bfg.jar --delete-files original_basis1000_1.txt.gz PyAbel.git
4. Then, 

        cd PyAbel.git
        git reflog expire --expire=now --all && git gc --prune=now --aggressive
5.  Finally pushing back the changes. This resulted in a few errors related to pull requests discussed [here](https://github.com/rtyley/bfg-repo-cleaner/issues/36) but it doesn't look like it's critical. And the repo is much smaller now.

        rth@byzance PyAbel.git % git push                                                                                                                   [master] 
        Counting objects: 458, done.
        Delta compression using up to 4 threads.
        Compressing objects: 100% (179/179), done.
        Writing objects: 100% (458/458), 5.62 MiB | 5.00 MiB/s, done.
        Total 458 (delta 271), reused 458 (delta 271)
        To git@github.com:PyAbel/PyAbel.git
         + b54ef31...0a9c093 master -> master (forced update)
         ! [remote rejected] refs/pull/10/head -> refs/pull/10/head (deny updating a hidden ref)
         ! [remote rejected] refs/pull/13/head -> refs/pull/13/head (deny updating a hidden ref)
         ! [remote rejected] refs/pull/15/head -> refs/pull/15/head (deny updating a hidden ref)
         ! [remote rejected] refs/pull/16/head -> refs/pull/16/head (deny updating a hidden ref)
         ! [remote rejected] refs/pull/17/head -> refs/pull/17/head (deny updating a hidden ref)
         ! [remote rejected] refs/pull/2/head -> refs/pull/2/head (deny updating a hidden ref)
         ! [remote rejected] refs/pull/21/head -> refs/pull/21/head (deny updating a hidden ref)
         ! [remote rejected] refs/pull/22/head -> refs/pull/22/head (deny updating a hidden ref)
         ! [remote rejected] refs/pull/28/head -> refs/pull/28/head (deny updating a hidden ref)
         ! [remote rejected] refs/pull/29/head -> refs/pull/29/head (deny updating a hidden ref)
         ! [remote rejected] refs/pull/3/head -> refs/pull/3/head (deny updating a hidden ref)
         ! [remote rejected] refs/pull/31/head -> refs/pull/31/head (deny updating a hidden ref)
         ! [remote rejected] refs/pull/5/head -> refs/pull/5/head (deny updating a hidden ref)
         ! [remote rejected] refs/pull/7/head -> refs/pull/7/head (deny updating a hidden ref)
        error: failed to push some refs to 'git@github.com:PyAbel/PyAbel.git'

**Comment by DhrubajyotiDas** [comment]
I think I'm going to fork PyAbel once again, and manually make the changes necessary to deal with https://github.com/PyAbel/PyAbel/issues/27. I won't touch pyroBASEX. Would that be an acceptable approach to make sure the repo's history does not get contaminated?

**Comment by rth** [comment]
@DhrubajyotiDas It adding a new fork worked, it would have been nice and probably the best approach I think, but it looks like it doesn't. So there might be a few alternatives
 
  1. With a different branch on pyroBASEX:
      1.  Create and switch to a new branch from your master
      2.  Checkout to the first commit on in the git history. This is the only commit that is now the same on your master and on PyAbel/PyAbel (as you can see on [the network graph](https://github.com/PyAbel/PyAbel/network))
      3. Fetch upstream from PyAbel/PyAbel and [rebase](https://stackoverflow.com/a/7244456)
      4. Then do commits only from this branch. The network graph can then be used that everything worked correctly. 

2. Alternatively, in settings of pyroBASEX, you should be able to unlink it from PyAbel, so it would become a standalone repo. Then you would probably be able to fork PyAbel. I have no guarantee, but it would make sens. The only think is unlinking is non reversible, so can't go back if it doesn't work. There should be some documentation about it somewhere.

3. Delete pyroBASEX from github and fork again as you mentioned.

**Comment by DanHickstein** [comment]
I had no outstanding changes, so I deleted and reforked. The download was much faster than usual, so I'm already enjoying our new, smaller repo :)
