### ISSUE TITLE
Default basis_dir for PyAbel

### ISSUE THREAD

**Issue by MikhailRyazanov** [PyAbel/PyAbel#325]
Continuing [this discussion](https://github.com/PyAbel/PyAbel/issues/247#issuecomment-478345872):
> Regarding where to store the basis sets: this is an issue for both the GUI and the command-line-interface usage of PyAbel. While we could find a solution that works only for the GUI, I think that this might be an opportunity to fix it globally. Currently, we are saving the basis sets in the current working directory, which litters the users computer with basis sets and most users will likely end up re-generating basis sets needlessly. Saving them in a single user-accessible directory provides a straightforward way for users of both the GUI and the CLI to manage their basis sets.

and #321...

I've looked closer at [appdirs](https://github.com/ActiveState/appdirs) and OS-specific recommendations and thought that we can do something like this:
* Add several new functions to `abel.transform`:
   * `set_basis_dir(...)` to set the default directory for basis files.
   * `get_basis_dir()` to get the currently set default directory for basis files.
   * `default_basis_dir()` to get the system-dependent cache directory suitable for storing basis sets.
* `get_basis_dir()` will be also used internally by all transform methods if no explicit `basis_dir` parameter is given to them, so the user can set the preferred directory (using `set_basis_dir(...)`) once in the program and then do any transforms without worrying about this.
* If `set_basis_dir(...)` was not called explicitly, the value of `default_basis_dir()` will be used. (Later, if we add some global configuration, this could be also altered there.)
* Add `basis_dir_cleanup(...)` utility functions to all transform methods for removing corresponding files (like `cache_cleanup()` currently works for RAM) and `abel.transform.basis_dir_cleanup(..., method='all')` for removing basis files for all or some methods.

This way we can keep all the basis files in one (and appropriate) place, and they can be easily removed when needed.
There are apparently no hooks in Python's distutils/setuptools/whatever that can be used for automatic removal of caches upon module deinstallation, but we can add to README a recommendation to run
```python
import abel
abel.transform.basis_dir_cleanup(method='all')
```
before uninstalling.

Here is a draft: [Default basis_dir for PyAbel](https://gist.github.com/MikhailRyazanov/beaa5d150a8f26c4159964c66b55c740).
Partially tested, but without “cleanup”.

Let's discuss, and if this look good, I'll prepare a PR...

**Comment by DanHickstein** [comment]
Great work Mikhail! I think that this is the right approach. 

I'm still concerned about what happens when we update the transform functions in a way that breaks backwards compatibility with the basis files. As I wrote in https://github.com/PyAbel/PyAbel/issues/247#issuecomment-478345872:

> what happens if a user upgrades their PyAbel after we have implemented a change that breaks backwards compatibility of the basis set files? Should the basis sets be saved with PyAbel version information? Should PyAbel check the "modified" datetime of the basis set file and ensure that this time came after the modified datetime of the <method>.py file?

**Comment by MikhailRyazanov** [comment]
Yes, versioning is still a concern, but somewhat less important (if I remember correctly, we had only one format change in the past ~2 years) and not closely coupled with this issue, so we should be able address it separately. There is already #261 to remind us. :–)

**Comment by MikhailRyazanov** [comment]
OK, I'm closing this as resolved. If somebody discovers any problems, please open a new issue!

**Comment by DanHickstein** [comment]
Awesome! Thanks so much for this Mikhail!
