### ISSUE TITLE
TravisCI testing: test MacOS on Python 3

### ISSUE THREAD

**Issue by DanHickstein** [PyAbel/PyAbel#330]
In #323, we enabled testing on MacOS. But, it's currently only Python 2.7, and it would be good to test on Python 3. 

Also, while we are doing this, we should remove the Windows testing on Travis since AppVeyor does this faster.

**Comment by MikhailRyazanov** [comment]
In light of #365, we are more likely to get macOS test using GitHub Actions than on Travis... :–)

**Comment by DanHickstein** [comment]
Seems accurate. We can probably close this issue in favor of the larger changes to the CI testing. Clearly we'd like Linux, Mac, and Windows tests with the latest Python versions.
