### ISSUE TITLE
Releasing v0.8.5 soon

### ISSUE THREAD

**Issue by DanHickstein** [PyAbel/PyAbel#332]
We had a request from the [SCICO](https://github.com/lanl/scico) project to release a new version of PyAbel with the latest features. This seems like a great time for a release anyway, since we don't have any outstanding pull-requests, and we've incorporated lots of new goodies since v0.8.4 was released. 

Any objections if @MikhailRyazanov and I release v0.8.5?

**Comment by stggh** [comment]
None from me. Go for it.

**Comment by MikhailRyazanov** [comment]
OK:
- [x] [RDT](https://pyabel.readthedocs.io/en/v0.8.5/changelog_link.html)
- [x] [PyPI](https://pypi.org/project/PyAbel/0.8.5/)
- [x] [Zenodo](https://zenodo.org/record/5888391)
- [ ] Conda?

**Comment by DanHickstein** [comment]
For Travis, I think that only one of the builds successfully uploads to PyPi, and the rest fail because there is already a pyabel v0.8.5 on PyPi. (Or, at least that's what I think is going on. The error message is unhelpful, but I recall seeing it before.) We are indeed on PyPi: https://pypi.org/project/PyAbel/

![image](https://user-images.githubusercontent.com/1107796/150560601-637eed72-15f2-4b64-84ca-47dd86284df9.png)

I honestly have no idea how the conda-forge thing works. I thought that maybe it automatically took the recent version...

**Comment by DanHickstein** [comment]
@rth: should the conda-forge repo automatically update after we make a release on PyPi?

**Comment by rth** [comment]
Yes, a PR will be made by a bot in https://github.com/conda-forge/pyabel-feedstock but you would need to check and merge it.

**Comment by DanHickstein** [comment]
Awesome, thanks!

I guess we should add this instruction to our release checklist in the contributing.rst.

**Comment by MikhailRyazanov** [comment]
@rth, the [conda PR](https://github.com/conda-forge/pyabel-feedstock/pull/20) has been indeed created and passes all tests! Is it possible to see the resulting files? I can see in the logs that the Cython library is now compiled with the new options, but it would be interesting to examine the actual packages before releasing them.

**Comment by rth** [comment]
You should see the log of `pip install` in the CI logs. It's also possible to add extra arguments to that command in `meta.yaml` for more verbosity.

**Comment by MikhailRyazanov** [comment]
I would like to see the conda *packages* built during the test. Or they are not saved at this stage?

**Comment by rth** [comment]
It doesn't look like they are. The `setup.py` looks good to me, I don't think there would be issues.

**Comment by MikhailRyazanov** [comment]
The previous version also looked OK, but was crashing on user's systems (#320). ;–) I also hope that now it should work fine but just wanted to make sure.

Anyway, if there is nothing else we can do, could you please merge that conda-forge PR? (I don't have write permissions there.)

**Comment by DanHickstein** [comment]
I have merge permission there, so I merged it. I don't seem to have admin permission, so I couldn't add @MikhailRyazanov to that repo. @rth, do you know how we can att @MikhailRyazanov?

**Comment by MikhailRyazanov** [comment]
Thanks, @DanHickstein! Now I see the v0.8.5 conda files: https://anaconda.org/conda-forge/pyabel/files.
I've downloaded the one that matches my system (`linux-64...py39`), and can confirm that it does work. And no [AVX-512 instructions](https://github.com/PyAbel/PyAbel/issues/320#issuecomment-993176595) inside this time.

**Comment by DanHickstein** [comment]
Okay, I think that I figured out how to add you as a maintainer on our confa-forge repo. 

https://conda-forge.org/docs/maintainer/updating_pkgs.html#updating-the-maintainer-list
https://github.com/conda-forge/pyabel-feedstock/issues/21
https://github.com/conda-forge/pyabel-feedstock/pull/22

**Comment by MikhailRyazanov** [comment]
OK, thanks! Let's see what happens when you merge that PR at  conda-forge/pyabel-feedstock...

**Comment by DanHickstein** [comment]
I merged the PR, so I think that you're a maintainer now. I'm not sure how to check if this is the case or not, save for making a  PR there and seeing if you have a "merge" button.

**Comment by MikhailRyazanov** [comment]
Hm, I didn't notice any changes immediately, but that bot sent me an invitation to join conda-forge, and after acceptin it, I can see now various editing tools, which didn't work before (they were telling me to fork the repository). So I guess, this indicates that it worked, thanks!

**Comment by DanHickstein** [comment]
Great! 

So, it looks like we now ticked all of the boxes and I'll close this Issue. (Please re-open if there are outstanding things that we didn't address yet.)

Thanks Mikhail!

**Comment by MikhailRyazanov** [comment]
Also got en email:
> You’ve been added to the "pyabel" team for the organization:
> "conda-forge"
> "pyabel" has 4 members and gives access to 1 "conda-forge" repository.

and can see myself among https://github.com/orgs/conda-forge/teams/pyabel/members.

**Comment by DanHickstein** [comment]
Excellent! You are now a member of a very prestigious club with many perks. Your shipment of celebratory champagne should be arriving by courier shortly ;).
