### ISSUE TITLE
SampleImage interface

### ISSUE THREAD

**Issue by MikhailRyazanov** [PyAbel/PyAbel#337]
I'm working on generalizing “spherical polynomials”, which are used for the rBasex basis, to any radial degree and making them available to end users. One useful application is to provide an independent Abel transform of our “sample images” (``abel.tools.analytical.SampleImage``): the Gaussians can be approximated by splines with any desired accuracy, which are then transformed analytically.

This needs some modification to the ``SampleImage`` interface, but this interface is currently in fact not consistent with the ``BaseAnalytical`` interface, from which it inherits. So let's discuss how to improve it.

Here is what ``BaseAnalytical`` says:
```
This is the base class for functions that have a known Abel transform.
Every such class should expose the following public attributes:
  - self.r: vector of positions along the r axis
  - self.func: the values of the original function
                (same shape as self.r)
  - self.abel: the values of the Abel transform (same shape as self.r)
  - self.mask_valid: mask of the r interval where the function is
    well smoothed/well behaved (no known artefacts in the inverse
    Abel reconstuction), typically excluding the origin, the domain
    boundaries, and function discontinuities, that can be used for
    unit testing.
```
However, ``SampleImage`` currently does not implement anything except ``.r``, but at the same time has additional attributes ``.image`` and ``.name``.

So my first suggestion is to rename ``.image`` to ``.func``; then the Abel-transformed image would be naturally named ``.abel``. And ``.mask_valid`` probably should be added (trivially). For the transition period, we can use the [``@property``](https://docs.python.org/3/library/functions.html#property) mechanism for ``.image`` to print a deprecation warning and return ``.func``.

However, a problem here is that ``BaseAnalytical`` says that ``func.func`` has the “same shape as ``self.r``”. So we either need to make ``.r`` in ``SampleImage`` 2-dimensional (and describe it in ``BaseAnalytical`` as an “array” instead of “vector”) or somehow state that ``.r`` is a “row”, and each of ``.func``, ``.abel`` and ``.mask_valid`` are one or more “rows”.

Another question is whether we want to expose [``R`` and ``THETA``](https://github.com/PyAbel/PyAbel/blob/e7e6b57ea1c6d679d67b3d0da4b5af45488c6910/abel/tools/analytical.py#L486-L487) (the polar coordinates) in ``SampleImage`` as public attributes. And whether such ``R`` can in fact replace ``.r``. The latter would automatically make ``.r`` 2D and having “same shape”, but will break its meaning in terms of Abel transforms, so it's probably not a good idea.

I'm not sure that ``R`` and ``THETA`` are useful for end users at all. Plus, many people apparently use PyAbel for non-VMI data, for which such polar coordinates don't have much sense. I also guess that it might be a good idea to add some such sample images (“flame”-like or whatever, @DhrubajyotiDas probably can give some ideas). Then we'll either need to have two separate classes with different attributes, unless we just decide that any ``SampleImage`` doesn't need polar coordinates. So: could they be useful for anybody at all? Or just keep them as internal variables?

And two questions about parameters:
```python
SampleImage(n=361, name='dribinski', sigma=2, temperature=200)
```
1. Maybe we should capitalize ``'Dribinski'``, but quietly accept both variants?
2. I would really like to make ``sigma`` absolute (in pixels, independent of ``n``), but with the defaults reproducing its current behavior (scaling the default value proportionally to the image size). Now it works very non-intuitively, depending on ``n`` *and* ``name`` in an incorrectly documented way. Can this break something? Can this be done better?

**Comment by stggh** [comment]
Thanks for the discussion @MikhailRyazanov. 

`BaseAnalytical` is a 1D class of functions function, that has an analytical Abel transform, while at the moment, `SampleImage` simply provides a 2D image (.func), with no analytical Abel transform (that has been coded).

> rename .image to .func

fine.

>  Or just keep them (R and THETA) as internal variables

Yes, internal. They are not much use for perfect "sample" images.

> capitalize 'Dribinski'

But, then also `dasch`, `hansenlaw`, `bordas`?

**Comment by MikhailRyazanov** [comment]
> `BaseAnalytical` is a 1D class of functions

Well, currently it doesn't say so. :–)

> `SampleImage` simply provides a 2D image (.func), with no analytical Abel transform (that has been coded).

And this was a part of the problem. Basically, `isinstance(SampleImage(), BaseAnalytical)` returns `True`, but `SampleImage` does not satisfy formal requirements for classes inherited from `BaseAnalytical`, neither the [Liskov substitution principle](https://en.wikipedia.org/wiki/Liskov_substitution_principle). A simple solution would be to make it a completely separate class, not inherited from `BaseAnalytical`. However, since now I'm going to implement the analytical Abel transform for `SampleImage`, they can be reconciled, and the question is *how* to do so better.

> But, then also `dasch`, `hansenlaw`, `bordas`?

Hm, these are, as I understand, mainly module names and thus follow Python naming conventions. We probably shouldn't use `Hansen–Law` as a module name. :–) However, it might be reasonable to accept `Transform(IM, method='Hansen-Law')`, for example.
