### ISSUE TITLE
Offline HTML

### ISSUE THREAD

**Issue by MikhailRyazanov** [PyAbel/PyAbel#347]
Offline PDF documentation is now available (#343), but while working on that I was also considering how to build offline HTML documentation properly. I've got rid of most dependences on external images (hosted inside our GitHub issues), but two “online” images  still remain: the “cover” image (3D Object ⇄ 2D Projection), used in README and in “Comparison”, and the output of “Example of use” from README.

The cover image is, frankly, not essential and takes >2 MB (~1/4 of the whole PDF file, by the way!), although it looks appealing. So I've made an attempt to redraw it in SVG (~10 kB and also convertible to ~30 kB PDF for LaTeX):
![cover](https://user-images.githubusercontent.com/12854133/159374600-e0664792-c4c3-4f1a-995e-79bcc75c63dc.svg)
(This is also a test that GitHub now supports SVG images!)
I guess, due to its small size, it can now be included in the repository. I don't know, however, what is the proper way to use it simultaneously in
* README at GitHub
* README in the built documentation
* README at PyPI

Searching the internet shows that this is *not straightforward*. Does anybody know how to do so?

And the image in README example perhaps needs to be updated (it has an old Matplotlib appearance). I guess, we can easily include a script to generate it for offline documentation. But should we then just refresh the online image for GitHub/PyPI or maybe we can instead link to the generated image at RTD?

**Comment by stggh** [comment]
Nice! What software did you use to generate the figure? 

Sorry, no idea(s) on the "proper way", any `LaTeX` processing appears to require .svg conversion.

**Comment by MikhailRyazanov** [comment]
Oy vey! According to “Images” and “Relative links” [here](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax), GitHub can use images from the repository, and this [works](https://github.com/MikhailRyazanov/PyAbel/tree/offline#readme) indeed. However, PyPI doesn't understand this (see a [recent report](https://www.reddit.com/r/learnpython/comments/psoqy7/image_doesnt_render_in_readmemd_on_testpypiorg/) ~6 months ago) and apparently is not going to in any foreseeable future. I guess, the only viable solution would be to do it in two steps: first, merge the image into master, and then change its path to the corresponding `github...raw` URL. This has [obvious drawbacks](https://github.com/StochSS/GillesPy2/issues/213#issue-488308286), but hopefully after that we'll not need to modify this image often or at all...

**Comment by MikhailRyazanov** [comment]
And for the example figure: what about changing the colormap to `'ocean_r'`?
![ocean_r](https://user-images.githubusercontent.com/12854133/159595384-f948ead0-fdce-4b40-b392-a9f74c428dcb.png)
This is plotted even without `clim` and still makes more structure visible.

Another variant with even better contrast is `'jet_r'`:
![jet_r](https://user-images.githubusercontent.com/12854133/159595550-92f24358-f47e-4eab-8f75-de86c22e0459.png)
but isn't it too harsh?

**Comment by stggh** [comment]
`ocean_r` looks the best IMO, but I believe the default `viridis` should be illustrated, as otherwise there may be user confusion  as to why their example does not reproduce the same output.

**Comment by stggh** [comment]
Oh, that works!

**Comment by MikhailRyazanov** [comment]
OK, see the results on [GitHub](https://github.com/MikhailRyazanov/PyAbel/tree/offline#readme) and [RTD](https://pyabel--348.org.readthedocs.build/en/348/readme_link.html)!

**Comment by DanHickstein** [comment]
This all looks awesome. Regarding the "example of use" figure, I suppose we could modify the example so that the intensity of the outer rings is better matched to the inner rings. Obviously the Abel transform changes this ratio, but we could start with an image that has a ratio of intensities that looks better with whatever colormap we choose.

**Comment by MikhailRyazanov** [comment]
I think, we can add the artificial image from the [Lin-BASEX article](https://doi.org/10.1063/1.4793404) (Fig. 3 / Table I) to our `SampleImage` and use it as an example. It seems to have a more uniform intensity distribution (and would also provide some test data with 4th-order anisotropy, which is useful by itself). A problem is, however, that the article doesn't list exact intensities, only mentioning that “The number of counts ... in each sphere varies between 160 000 and 320 000.” Maybe Thomas Gerber could help us again — if he can recall the details. :–) Or I can try to fit them trying to match the plotted projection...

(For the colormap, this “ocean” has a nice property that it kind of resembles the bluish color of the “overview” image.)

**Comment by MikhailRyazanov** [comment]
After some pondering, I've realized that “each sphere varies between 160 000 and 320 000” corresponds to total intensity 4πr<sup>2</sup> I(r) = 160 000 × β<sub>0</sub>, with β<sub>0</sub> (varying between 1 and 2) from the table. Here is the recreated image (with Poissonian noise and the same colormap `terrain_r` as in the article):
![linbasex](https://user-images.githubusercontent.com/12854133/161453172-75b7f9cb-ad91-4ab5-9d6a-a4cafe59d781.png)
Looks very similar to Fig. 3, and the projection matches well. So I'm planning to add it to `SampleImage` in a separate PR later.

It still doesn't look great with the default colormap:
![linbasex](https://user-images.githubusercontent.com/12854133/161453273-87da6c31-214a-44c5-a3f2-5ce522eca278.svg)
but is quite reasonable with `ocean_r`:
![linbasex_ocean](https://user-images.githubusercontent.com/12854133/161453307-88587dbe-5082-4ccc-82ee-0a0fa29bb9e7.svg)

**Comment by MikhailRyazanov** [comment]
OK, closing as done (in #348, #349, #352).
