### ISSUE TITLE
Add lin-BASEX artificial image to SampleImage

### ISSUE THREAD

**Issue by MikhailRyazanov** [PyAbel/PyAbel#351]
It was mentioned in #347 that our default `dribinski` sample image has a very large dynamic range, which causes some problems with its visualization. I can add that the other image, `Ominus` is rather boring, :–) and most features in `O2` are also faint and poorly visible.

At the same time, the article describing the `linbasex` method includes another test image, with a more reasonable dynamic range and, in addition, with features having higher-order anisotropies. I was able to reproduce it:
![linbasex](https://user-images.githubusercontent.com/12854133/161453172-75b7f9cb-ad91-4ab5-9d6a-a4cafe59d781.png)
and its forward/inverse Abel transforms indeed look interesting:
![linbasex_ocean](https://user-images.githubusercontent.com/12854133/161453307-88587dbe-5082-4ccc-82ee-0a0fa29bb9e7.svg)

So I think, it would be worth adding it to `tools.analytical.SampleImage` (and perhaps using in the README example).
I don't know, however, how to name it:
* `gerber` by the first author's surname, like it is done for `dribinski`?
* `linbasex`, and also rename `dribinski` to `basex` (leaving an alias)? We don't really know that these images were developed by these particular persons (the respective articles have 7 and 4 authors), and our users probably associate corresponding articles with the methods rather than with their first authors.

**Comment by DanHickstein** [comment]
Awesome! I think that image looks quite nice.

I'd say that we either call it "gerber" or some generic name like "sample1". Calling it the same name as a transform method could be quite confusing.

**Comment by MikhailRyazanov** [comment]
OK, then I'll just add it as `gerber` (to be consistent with `dribinski`).

Do you also want to use it in the README example?

**Comment by DanHickstein** [comment]
>OK, then I'll just add it as gerber (to be consistent with dribinski).
Great!

>Do you also want to use it in the README example?
That sounds good to me!

**Comment by MikhailRyazanov** [comment]
Done in #352.
