### ISSUE TITLE
UnboundLocalError: local variable 'scale' referenced before assignment

### ISSUE THREAD

**Issue by adammaj1** [PyAbel/PyAbel#354]
Hi

I want to run ffirst example
```
python3 ./p.py
Traceback (most recent call last):
  File "/home/a/Dokumenty/mandelbrot_planes/log/python/abel/./p.py", line 2, in <module>
    original = abel.tools.analytical.SampleImage(name='Gerber').func
  File "/home/a/.local/lib/python3.10/site-packages/abel/tools/analytical.py", line 486, in __init__
    X, Y = np.meshgrid(self.r*scale, self.r*scale)
UnboundLocalError: local variable 'scale' referenced before assignment
```

What is wrong ? 

My settings
Ubuntu 22.04 LTS
```

python3 -V
Python 3.10.4

 pip install PyAbel
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: PyAbel in ./.local/lib/python3.10/site-packages (0.8.5)
Requirement already satisfied: setuptools>=16.0 in /usr/lib/python3/dist-packages (from PyAbel) (59.6.0)
Requirement already satisfied: scipy>=0.14 in /usr/lib/python3/dist-packages (from PyAbel) (1.8.0)
Requirement already satisfied: numpy>=1.6 in /usr/lib/python3/dist-packages (from PyAbel) (1.21.5)
Requirement already satisfied: six>=1.10.0 in /usr/lib/python3/dist-packages (from PyAbel) (1.16.0)
```

TIA
Adam

**Comment by MikhailRyazanov** [comment]
I guess, you are trying the example from out development version (called “[latest](https://pyabel.readthedocs.io/en/latest/)” on Read the Docs) but using the “[stable](https://pyabel.readthedocs.io/en/stable/)” PyAbel version [from PyPI](https://pypi.org/project/PyAbel/) — this is what `pip` installs. If you want to use what you see here, in GitHub master branch, you need to install it manually (using `git` or from the ZIP file, click the green button “Code” on the [home page](https://github.com/PyAbel/PyAbel)).

If it's not essential to use that particular sample image, then just use the default (`original = abel.tools.analytical.SampleImage().func`, without `name=...`), it should work.

**Comment by MikhailRyazanov** [comment]
@DanHickstein, @stggh, this makes me think that we need to tweak the README further, such that instead of

> Note: This readme is best viewed as part of the [PyAbel Documentation](https://pyabel.readthedocs.io/en/latest/readme_link.html).

always pointing to “latest”, it should _on PyPI_ point to “stable”:

> Note: This readme is best viewed as part of the [PyAbel Documentation](https://pyabel.readthedocs.io/en/stable/readme_link.html).

I don't know, however, how to make RST distinguish between GitHub and PyPI...

**Comment by MikhailRyazanov** [comment]
Now this should work with the new PyAbel version (0.9.0), and the links are made version-specific, so such ploblems hopefully will not reoccur...
