### ISSUE TITLE
Granular Resolution

### ISSUE THREAD

**Issue by ctchavez6** [PyAbel/PyAbel#358]
![newplot(7)](https://user-images.githubusercontent.com/86802224/188239150-48fb3549-fd48-4820-824b-a74bf3cea470.png)
Hi,

I have a csv ~1000x1000 cells that I would like to transform. With the code I am running now it accepts image files. So i convert my csv into an image first and then into the CV.imread...:
```
src = cv.imread(cv.samples.findFile(filename), cv.IMREAD_COLOR)
kernel = np.ones((10,10),np.float32)/100
dst = cv.filter2D(src,-1,kernel)
src_gray = cv.cvtColor(dst, cv.COLOR_BGR2GRAY)  # converts to grayscale
```
then I do the transforms. 

Can I transform the data directly from a csv?

The data is from a plasma jet projection taken by an interferometer, so I use the inverse transform to recreate the profile. The first plot is the raw data in PNG form which is granular. The second plot is the inverse transform. The third plot is the forward transform performed on the second plot.
Thanks for the help.
Cameron

**Comment by DanHickstein** [comment]
You can load a csv directly into a numpy array. There are a few ways to do it, but I like using 

data = np.loadtxt(‘file.csv’, delimiter=‘,’)

see if that works for you.

**Comment by DanHickstein** [comment]
I'm closing this. Feel free to reopen if further discussion is needed.
