### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by MikhailRyazanov** [PyAbel/PyAbel#361]
@DanHickstein [suggests](https://github.com/PyAbel/PyAbel/pull/360#issuecomment-1320478412) releasing “v0.9.0”. I think, this makes sense, as we have a lot of changes since v0.8.0. My next plans are to work on a new, more usable GUI. I already have some mockup, but there were too many distractions so far. However, working on it in v0.9.x looks reasonable, and when it's done, we can probably release v1.0.

One concern, however, is that I've done some modifications in #360 that might have not very predictable effects on the release process. So I'd suggest first releasing `v0.9.0rc1` (it should be considered a “pre-release” for `v0.9.0`, according to [PEP 440](https://peps.python.org/pep-0440/)), and if everything goes well, and nobody complains within a week or two, then make the actual `v0.9.0` release.

**Comment by DanHickstein** [comment]
Sounds good to me! Looking forward to seeing the new GUI.

**Comment by MikhailRyazanov** [comment]
Hmm. Some problems _were_ discovered.

The most important is that changing the directory where tests are run (see 840eebd9 and [why](https://github.com/PyAbel/PyAbel/pull/357#issuecomment-1224964696)) broke PyPI deployment because Travis apparently tries to continue it from where the test finished, without restoring the path. I guess, this would be easy to repair with `pushd`/`popd`, but since everybody seems to be unhappy with Travis now, maybe we should instead try switching to PyPI deployment using GitHub Actions, as suggested in #365?

Another strange thing is that Read the Docs did not built anything for the new `v0.9.0rc1` tag until I've manually activated a build for it. I don't remember that we had this problem before. Is it related to marking this as a “pre-release” on GitHub? Or that the tag format is “strange”?

So currently we don have the new release here (OK), on Zenodo (OK), and RTD (manually triggered), but not packages on PyPI (due to an error in Travis config) and no conda packages (I guess, because of no PyPI).

Any thoughts on further actions?

**Comment by DanHickstein** [comment]
> maybe we should instead try switching to PyPI deployment using GitHub Actions, as suggested in https://github.com/PyAbel/PyAbel/issues/365?

Fine with me. I won't have time to work much on this during this week, but if you have interest, then I think that it's the correct thing to do. (at least numpy and scipy have taken this approach)

> Another strange thing is that Read the Docs did not built anything for the new v0.9.0rc1 tag until I've manually activated a build for it. 

I'll look into the rtd settings...

> Any thoughts on further actions?

Getting the PyPi deployment working again seems like the priority.

**Comment by MikhailRyazanov** [comment]
> Getting the PyPi deployment working again seems like the priority.

Obviously. :–) But should I just correct `.travis.yml`, or should we try GitHub Actions? Let's see what @rth replies...

**Comment by DanHickstein** [comment]
Oh, I'd say you can just correct travis.yml for now, get v0.9.0 out the door, and then we can switch to GitHub actions whenever is convenient. 

Also, I'm not quite sure how RTD decides to build a new release. v0.9.0rc1 is now listed as an "active version". I'm not sure how to add v0.9 as an active version to make sure that all new releases are automatically built.

**Comment by MikhailRyazanov** [comment]
Now, after #367 Travis builds the package but [fails](https://app.travis-ci.com/github/PyAbel/PyAbel/jobs/590561392#L1115-L1116) to upload it to PyPI:
```
1049 Uploading distributions to https://upload.pypi.org/legacy/
1050 Uploading PyAbel-0.9.0rc2-cp311-cp311-linux_x86_64.whl
1051 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 583.6/583.6 kB • 00:00 • 6.1 MB/s
1052 WARNING  Error during upload. Retry with the --verbose option for more details. 
1053 ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
1054          Binary wheel 'PyAbel-0.9.0rc2-cp311-cp311-linux_x86_64.whl' has an     
1055          unsupported platform tag 'linux_x86_64'.                               
```
Apparently, PyPI doesn't like such wheels and thus _everything_ fails...

I guess, the only option now is to use source-only `distributions: sdist` without `bdist_wheel` (this seems to be what Travis was [doing](https://app.travis-ci.com/github/PyAbel/PyAbel/jobs/556543048) before _by default_ — although the config [had](https://github.com/PyAbel/PyAbel/blob/cd66e2a942e1474001dad53361ac5442c6f4e3d2/.travis.yml#L35) the same `distributions: sdist bdist_wheel`, it was in a wrong section and thus ignored).

**Comment by rth** [comment]
Yeah, the way to go is to use cibuildwheel to make manylinux wheels that are portable across different linux distributions (unlike linux_x86_64 wheels which are not). Or just not build wheels for Linux and let people build them locally.

Sorry I won't be able to help much on this.

**Comment by rth** [comment]
For Github Actions copy-pasting the few lines from https://cibuildwheel.readthedocs.io/en/stable/setup/#github-actions should just work and build correct wheels for MacOS Linux and Windows  I think. One thing to change there is to only run it on tags maybe instead of every commit. 

There is also a Travis CI example below on the same page, but a bit less useful as it's Linux only.

**Comment by MikhailRyazanov** [comment]
Thanks, @rth! We'll then try this after the v0.9.0 release.

@DanHickstein and @stggh, now it seems to work as expected so far...

PyPI [has](https://pypi.org/project/PyAbel/0.9.0rc3/) the new version (marked as a pre-release, so it's not shown by default and must be selected from the list), as far as I can tell, now with all version-specific links pointing to corresponding GitHub and RTD versions. Please double-check.

I'm still waiting for conda (will it automatically build pre-release packages?), but hopefully there will be no surprises, as nothing related to it has changed.

**Comment by DanHickstein** [comment]
Yeah, looks good on PyPi! 

Conda Forge is something of a mystery to me. I would not assume that it will build the pre-release. If it looks good on PyPi, I think we should go ahead and release.

**Comment by MikhailRyazanov** [comment]
OK, I've created #369.

My guess about conda and RTD is that they automatically trigger the build when the “latest” version is updated, but since these “rc” pre-releases were not marked as “latest”, nothing was happening.

**Comment by MikhailRyazanov** [comment]
Everything seems to be fine now.

PyPI, RDT and Zenodo show version v0.9.0 as the current latest/stable.

All conda packages were also built. I've checked “linux-64” for Python 3.10, and it looks fine. If anybody can also check something for Windows and macOS, it would be great.

**Comment by MikhailRyazanov** [comment]
On RTD, I've made ...rc1 and ...rc2 “inactive”, since they shouldn't be referenced from anywhere, while ...rc3 still “active” (it's referenced from the PyPI pre-release) but “hidden” (no need to show it for any other purposes, as it's the same as the final version).

**Comment by MikhailRyazanov** [comment]
Since in more than a week nobody reported any problems with the new release, I suppose, we can declare is successful. :–)

**Comment by DanHickstein** [comment]
Yes, a success for sure! Thanks for getting the new release out into the world.
