### ISSUE TITLE
Asymmetry

### ISSUE THREAD

**Issue by ctchavez6** [PyAbel/PyAbel#370]
Hello,

I am using the basex inverse and forward transform. The input that I am using is not perfectly symmetric and I am wondering how it treats the transform. You may be able to see my data from previous “issues” I have posted here. Does it treat the left and right hand side separately? How does the transformation deal with asymmetry?

Thanks for your help,
Cameron

**Comment by DanHickstein** [comment]
Hi Cameron,

Check out the documentation for `abel.transform.Transform` class, especially the `symmetry_axis` and `use_quadrants` keywords: https://pyabel.readthedocs.io/en/latest/abel.html#module-abel.transform

By default, that function will perform the abel transform separately on each quadrant of the image (so, left and right are treated separately) but you can change the behavior to whatever you want.

Fundamentally, the individual abel transform methods work only on the "right side" of the image.

Let me know if that answers your questions.

**Comment by ctchavez6** [comment]
Yes that's exactly what i was looking for thank you.

**Comment by DanHickstein** [comment]
Great! I’m going to close this issue then. Feel free to start a new one (or reopen this one) if more questions arise.
