### ISSUE TITLE
Final entry of 'direct' inverse transform of a 1D array is always zero?

### ISSUE THREAD

**Issue by DavidT3** [PyAbel/PyAbel#385]
Hi,

I'm using your module to enable inverse-abel deprojections of surface brightness profiles for astrophysical objects in my module - I let the user choose between most of the implementations you provide, but I've just noticed that the 'direct' transform (whether I use dr, or pass a spatial mesh (radii in my case), I end up with the final element of the output array being zero.

I am using the python implementation.

And a test data set would be:

`dr = 42.22897612626319`

`vals = array([0.05380597, 0.03950476, 0.02695798, 0.02092113, 0.01460821,
       0.01132293, 0.00891306, 0.00671739, 0.00609382, 0.00533249,
       0.00420262, 0.0041189 , 0.0038018 , 0.00354966, 0.0036527 ,
       0.00417479, 0.00426684, 0.00354484, 0.00393238, 0.00360251,
       0.00338861])`

`rads = array([ 21.11448806,  63.34346419, 105.57244032, 147.80141644,
       190.03039257, 232.25936869, 274.48834482, 316.71732095,
       358.94629707, 401.1752732 , 443.40424933, 485.63322545,
       527.86220158, 570.0911777 , 612.32015383, 654.54912996,
       696.77810608, 739.00708221, 781.23605834, 823.46503446,
       865.69401059])`

`direct_transform(vals, r=rads, backend='python', correction=True)`

or 

`direct_transform(vals, dr=dr, backend='python')`

Am I a) being stupid and misunderstanding something? b) using this wrong? c) or is this an expected behaviour for this function?

Cheers,
David

**Comment by MikhailRyazanov** [comment]
The outer point in the “direct” method currently has fixed zero intensity, see #217. In principle, it doesn't need to, but (from [documentation](https://pyabel.readthedocs.io/en/latest/transform_methods/comparison.html#math)):
> Note that the forward and inverse Abel transforms are defined on the whole space, with infinite integration limits, but in reality, experimental data are limited to finite ranges of _r_ or _y_. Thus the intensity distributions _f_ and _F_ **must be zero outside these ranges**, otherwise the transforms cannot be performed correctly. In other words, only localized objects can be transformed, and the object must be contained entirely within the image frame. **If the image has any background, it must be subtracted before applying the transform, such that the image intensity goes to zero near the edge** (however, the **[Direct](https://pyabel.readthedocs.io/en/latest/transform_methods/direct.html)** and [Hansen–Law](https://pyabel.readthedocs.io/en/latest/transform_methods/hansenlaw.html) methods **effectively disregard a constant background**).

There was also some useful discussion in #306.

If your data ends exactly at the edge, just pad it with a zero.

**Comment by DavidT3** [comment]
Ahh, sorry I missed that in the documentation - thank you very much!
