### ISSUE TITLE
Some questions about quantified analysis with rBasex

### ISSUE THREAD

**Issue by xiaoyuleiba** [PyAbel/PyAbel#386]
Hello, recently I'm doing some analysis of PECD. But before that, now I'm analyzing my data to quantify its energy characteristic, under linear polarization. The inverse Abel transformed image shows that rBasex is the most suitable method for my results. 

## Issue Description

**LinBasex** always gives $\beta_0 (\text{max})=1$, and $\beta_2$ is also in a range of -1 ~ 2, that is what they should be. However, **rBasex** gives results like $0<\beta_0<1200$, and $-50\leq\beta_2<100$. With regard to the numerical values, something like $\beta_0\times\beta_2$ or $\beta_0\times\text{LPECD}$ will not be reliable anymore.

But when I apply `abel.tools.vmi.radial_integration` to the transformed images, it always gives **reasonable** $\beta_2$ of the radial range around $\beta_0$ peaks, so I believe the algorithm producing transformed image behind **rBasex** works as we expected. 

## Question
  
So my question is, is there any keywords or something to set **rBasex** gives ranges of $\beta_n$ like what **LinBasex** gives?

Is there a way to adjust **rBasex** parameters to obtain $\beta_n$ ranges similar to those from **LinBasex**? Are there any keywords or specific settings that might help normalize these ranges?

By the way, I found that **LinBasex** also gives some strange $\beta_n$ under extreme conditions, like PECD without Permalloy's protection (It's on its way, but, still on its way. That is actually my bad, PyAbel really did its best).

Thank you very much for your assistance!

---

<figure>
  <img src="https://github.com/user-attachments/assets/e18e8e71-7e40-404d-b024-b792286f2b5b" width="200"/>
  <img src="">
</figure>

**Fig. 1: Original VMI**

<figure>
  <img src="https://github.com/user-attachments/assets/2308e262-69e1-49c5-a973-ebcccbf47da0" width="200"/>

  <img src="https://github.com/user-attachments/assets/fd158fa8-9935-4a1d-93e2-1e3243ab397e" width="300"/>

  <img src="https://github.com/user-attachments/assets/523a42ae-c7a2-48ab-a9a1-484a2dcc22de" width="300"/>
</figure>

**Fig. 2-1: Inverse Abel transformed image with LinBasex  
Fig. 2-2: $\beta_2$ plot of inverse Abel transformed image with LinBasex  
Fig. 2-3: Average** $\beta_2$ **around each PES peak (given by** `abel.tools.vmi.radial_integration` **)**

<figure>
  <img src="https://github.com/user-attachments/assets/180c528b-1242-4229-b677-d6f5f6c93958" width="200"/>

  <img src="https://github.com/user-attachments/assets/a5ab5654-dc3e-494f-ae00-096c8f1030b2" width="300"/>

  <img src="https://github.com/user-attachments/assets/0e25cdfe-af0d-4598-8edb-076f85c3d383" width="300"/>
</figure>

**Fig. 3: Same as Fig. 2, but under rBasex**

---
My code:
```python
roiabel = abel.Transform(roi,
    origin='image_center',
    method='linbasex',
    transform_options=dict(
        legendre_orders= [0,2],
        clip=2
        ),
    center_options=dict(
    square=True,
    odd_size=True
        ),
    symmetry_axis=0,
    symmetrize_method='average'
)
```
```python
roiabel = abel.Transform( np.rot90(roi,k=3),
    origin='image_center',
    method='rbasex',
    transform_options=dict(
        order = 2
    ),
    center_options=dict(
        square=True,
        odd_size=True
    ),
    symmetry_axis=0,
    symmetrize_method='average'
)
```

**Comment by MikhailRyazanov** [comment]
β₂ _should_ be in the range [−1, 2] _only_ when the distribution is a positive combination of cos² and sin² angular terms and nothing else. The experimental data is always noisy, and that noise doesn't follow such assumptions, so there is no surprise that in the areas dominated by the noise you see “crazy” β₂ values. If you limit the vertical plot axis to the physically meaningful β₂ range and plot the intensity and the anisotropy parameter on the same horizontal axis (radius), you should see reasonable β₂ values _at the intensity peaks_, but perhaps something meaningless in the areas with no signal (which shouldn't really bother anybody).

Another possibility, if you are sure that the signal obeys the positivity assumption and has only 0th and 2nd Legendre orders, is to use `reg='pos'`, which imposes the positivity restriction, in this case equivalent to −1 ⩽ β₂ ⩽ 2, so you'll get physically meaningful values everywhere, even in the areas without any usable signal.

**Comment by xiaoyuleiba** [comment]
> β₂ _should_ be in the range [−1, 2] _only_ when the distribution is a positive combination of cos² and sin² angular terms and nothing else. The experimental data is always noisy, and that noise doesn't follow such assumptions, so there is no surprise that in the areas dominated by the noise you see “crazy” β₂ values. If you limit the vertical plot axis to the physically meaningful β₂ range and plot the intensity and the anisotropy parameter on the same horizontal axis (radius), you should see reasonable β₂ values _at the intensity peaks_, but perhaps something meaningless in the areas with no signal (which shouldn't really bother anybody).
> 
> Another possibility, if you are sure that the signal obeys the positivity assumption and has only 0th and 2nd Legendre orders, is to use `reg='pos'`, which imposes the positivity restriction on the distribution, in this case equivalent to −1 ⩽ β₂ ⩽ 2, so you'll get physically meaningful values everywhere, even in the areas without any usable signal.

Thanks, I appreciate it. With a weight of $\beta_0$, $\beta_0\times\beta_2$ plot does make sense. 

However, just like what Fig. 6 shows in https://doi.org/10.1063/1.4982614, in PECD those odd $\beta_n$ of areas where $\beta_0\approx0$, also matters.  
Only $\beta_n$ around where $\beta_0\gg0$ are valid, is not persuasive enough, both for **rBasex** and PECD. And this is what I am analyzing and want to analyze with PyAbel.

**Comment by MikhailRyazanov** [comment]
That article uses Legendre coefficients $c_n$ (absolute intensities of the angular harmonics), not anisotropy parameters $\beta_n$ (fractional contributions of the harmonics). By definition, $\beta_n \equiv c_n/c_0,$ so $\beta_0 \equiv 1$ always, and $\beta_n$ for $n > 0$ make no sense where $c_0 = 0$.

If you need the Legendre coefficients, they are available in rBasex results (`distr`) as [`harmonics()`](https://pyabel.readthedocs.io/en/latest/abel.html#abel.tools.vmi.Distributions.Results.harmonics).

**Comment by xiaoyuleiba** [comment]
Thank you. Now I know all of these are my misunderstanding, my bad.
