### ISSUE TITLE
Request for clarification surrounding symmetry axis

### ISSUE THREAD

**Issue by David1one** [PyAbel/PyAbel#388]
I wish to ask for clarification surrounding the definition of the symmetry axis for an abel transform.

For my application, I wish to define a symmetry axis that is centred on the image, and vertical. Such an example is in Issue #341. 

But it is also possible to define a symmetry axis centred on the image, but perpendicular to the plane of the image, such as in the [Hansen-Law example](https://pyabel.readthedocs.io/en/latest/example_hansenlaw.html) in the docs.

It's not clear to me why the first example and the second example have symmetry axes pointing in different directions. How do I know which way the symmetry axis points?

**Comment by MikhailRyazanov** [comment]
There is a “Note that the Abel transform is always performed around the vertical axis.” in https://pyabel.readthedocs.io/en/latest/abel.html#abel.transform.Transform, but this question is still raised from time to time, so I've already prepared a README update

> **Image orientation:** The cylindrical symmetry axis in PyAbel is always **vertical**; if your data is instead symmetric around the horizontal axis, the image must be transposed or rotated by 90° before applying any Abel transform (and then back, to recover the original orientation). PyAbel adopts the "television" convention, ...

but didn't have time to submit it yet. Hopefully, will be done soon.

(And by the way, the cylindrical axis for the Abel transform must be _in the plane_ of the image; “perpendicular to the plane of the image” doesn't work.)

**Comment by stggh** [comment]
Yes, the `PyAbel` transform is always with respect to the vertical axis. The symmetry axis parameter refers to (any) image (data) symmetry. This information allows some image quadrants to be combined,  improving signal to noise, before the transform is evaluated. e.g. for velocity-map imaging of photoelectrons, from a linearly polarized laser source, all the image data may be co-added and the image transformed as a single quadrant.

**Comment by MikhailRyazanov** [comment]
@David1one, please take a look at the updated [“Conventions: Image orientation”](https://pyabel.readthedocs.io/en/latest/readme_link.html#conventions) section and at the ``symmetry_axis`` parameter description in [``abel.Transform``](https://pyabel.readthedocs.io/en/latest/abel.html#abel.transform.Transform). Are they sufficiently clear now?

**Comment by David1one** [comment]
@MikhailRyazanov thank you for the clarifications and the README updates, I think it is much clearer now.
