### ISSUE TITLE
Absolute scaling of the inverse abel transform with BASEX

### ISSUE THREAD

**Issue by rth** [PyAbel/PyAbel#4]
Hi Dan, 

I'm interested in the absoute scaling of the output of the BASEX algorithm: so when we process some physical signal, I'm trying to make sure that we to obtaint the correctly scaled inverse abel transform.

This uses the pyBASEX v0.3 (i.e. before the pull request). 

For instance, if we take a  gaussian signal `f(r) = exp(-r**2)` the forward Abel tranform is given analytically by  `F(r) = pi**0.5*f(r)`, so if we were to apply the BASEX algorithm to `F(r)` function it should yield exactly `f(r)`. Now when I'm doing this I obtain the plot below,

![figure_1](https://cloud.githubusercontent.com/assets/630936/7442144/72e5b9ee-f104-11e4-8e35-ab3e4f2039a1.png)

The code to make this figure is given in the following [gist](https://gist.github.com/rth/416280215353196c97b1) (and it uses pyBASEX v0.3, before the pull request)

So it looks really good, but for  a constant  scaling factor of approximatily `8.86` . I already scaled the BASEX output by `1/dx`  where `dx = 0.02` is my pixel size  which should be the only necessary scaling I belive.  So I'm a bit confused about about the `8.86` scaling factor. I suppose it should be some combination of `dx`, `N=1001`, and maybe `pi` to some power, but up to now I was not able to find which one. Would you have any ideas about it?

Thanks,

**Comment by DanHickstein** [comment]
Dear Roman,

I have notice this discrepancy before, but I have not tried to figure out
where it is coming from. It would be great if the BASEX reconstruction
could match up with the analytical inverse abel. I think that the same
problem exists with the compiled C version of the BASEX software that most
people use.

Hopefully you can figure out what is going on, otherwise it's probably a
good idea to just include a scaling factor (as you suggest) to get it to
match up.

Thanks,

Dan


On Sat, May 2, 2015 at 12:10 PM, Roman Yurchak <notifications@github.com>
wrote:

> Hi Dan,
>
> I'm interested in the absoute scaling of the output of the BASEX
> algorithm: so when we process some physical signal, I'm trying to make sure
> that we to obtaint the correctly scaled inverse abel transform.
>
> This uses the pyBASEX v0.3 (i.e. before the pull request).
>
> For instance, if we take a gaussian signal f(r) = exp(-r**2) the forward
> Abel tranform is given analytically by F(r) = pi**0.5*f(r), so if we were
> to apply the BASEX algorithm to F(r) function it should yield exactly f(r).
> Now when I'm doing this I obtain the plot below,
>
> [image: figure_1]
> <https://cloud.githubusercontent.com/assets/630936/7442144/72e5b9ee-f104-11e4-8e35-ab3e4f2039a1.png>
>
> The code to make this figure is given in the following gist
> <https://gist.github.com/rth/416280215353196c97b1> (and it uses pyBASEX
> v0.3, before the pull request)
>
> So it looks really good, but for a constant scaling factor of
> approximatily 8.86 . I already scaled the BASEX output by 1/dx where dx =
> 0.02 is my pixel size which should be the only necessary scaling I
> belive. So I'm a bit confused about about the 8.86 scaling factor. I
> suppose it should be some combination of dx, N=1001, and maybe pi to some
> power, but up to now I was not able to find which one. Would you have any
> ideas about it?
>
> Thanks,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DanHickstein/pyBASEX/issues/4>.
>



-- 
Daniel D. Hickstein
DanHickstein@gmail.com
Phone: 301 787 1853

**Comment by rth** [comment]
Hmm, that's good to know. I'll try to look into that. Thanks for your response!

**Comment by DanHickstein** [comment]
Following up on this, should we just go ahead and include the scaling factor?

**Comment by rth** [comment]
I think including a scaling factor is fine. The only problem is to understand at least roughly where does this factor comes from, as simply adding a magical number doesn't sound ideal. Sorry about the delay, I can look further into it this week.

**Comment by DanHickstein** [comment]
Yeah, it would be nice to understand where this comes from. It probably indicates some misunderstanding of the mathemagics. For now, I would say that we should just include the magic number, but I would appreciate any efforts to get to the bottom of this. 

A long time ago, Hanna Reisler (BASEX comes from her group) suggested that we send out an announcement on the [Molecular Dynamics mailing list] (https://www.jiscmail.ac.uk/cgi-bin/webadmin?A0=MOLECULAR-DYNAMICS-NEWS), letting people know about the python implementation of BASEX. I was thinking about sending out this announcement this week, but I thought that I should clean up the code first. So, if you have a little bit of time in the next few days, any additional documentation and code clean-up efforts would be very appreciated. Especially for the bits of the code that you developed, like the basis set generation functions.

**Comment by rth** [comment]
Well, I have finished my PhD a few weeks ago, so I have a bit more free time now, I'll look into that.

**Comment by DanHickstein** [comment]
Congratulations on finishing your PhD!
