### ISSUE TITLE
Last call for Version 0.6

### ISSUE THREAD

**Issue by DanHickstein** [PyAbel/PyAbel#40]
Is there anything else that we need to do to release version 0.6?

I am making a few changes to the comments - basically removing some of the old text that no longer makes sense.

Also, I think that we should rename the examples to clearly indicate that they are examples for the basex transform. ``example_gaussian.py`` would become ``example_basex_gaussian.py``. Does this present a problem?

**Comment by rth** [comment]
As far as I'm concerned we are good to go. I changed a bit my opinion with respect to [my last comment about BASEX and even images](https://github.com/PyAbel/PyAbel/issues/34#issuecomment-160684430), I think it is a wider problem that would arise for all implementation as discussed in  issue #39  and we could address it under v0.7. 

If we see the objective of v0.6 is to release a complete working version of BASEX, before merging other implementations, well the matlab based  BASEX implementation we have was originally designed to work with odd images. We can cleanly address the even case in v0.7, I don't think that it's that urgent.

Renaming the examples would make sens.

**Comment by DanHickstein** [comment]
Awesome. One other thing that I noticed: calc_speeds currently takes two arguments: ``im``, the image, and ``n``, the size of the array to be returned. I cannot really imagine a situation where a user would want to array to be different than the minimum radial coordinate. For example, if they have a ``500x500`` image, then radial coordinate should run from 0 to 249 (length=250). I modified the calc_speeds to take just one argument and modified basex.py accordingly.

**Comment by rth** [comment]
@DanHickstein Ok, if that's all I guess we can go ahead and create [a release on github](https://help.github.com/articles/creating-releases/) for v0.6. Then make a single commit on  PyAbel/PyAbe master (without PR)  with the version bump to v0.7.

**Comment by DanHickstein** [comment]
Okay, I made a v0.6.0 release. Now quite sure how to do the 0.7 bump... 

Also, I think that we forgot to update the __verison__.py file before that release. My github skills are lacking... :)

**Comment by rth** [comment]
Nice! Thanks everybody!

**Comment by rth** [comment]
@DanHickstein  No that's fine, we should update it after the release, otherwise that release would install as v0.7....

**Comment by DanHickstein** [comment]
Well, the version was set at 0.5.1. What should I make it now? 0.7? Or do we just make it 0.6.1 until we are done...

**Comment by rth** [comment]
Aww yes, I see what you mean, I missed that too. Don't think it's an issue.. 

 I don't know, I would say `0.7` (which is effectively `0.7-dev`) and would become `0.7` stable when we make the next release?

**Comment by DanHickstein** [comment]
Done!

**Comment by DanHickstein** [comment]
Now we have our work cut out for us, implementing these new transforms and changing the function names. :)

**Comment by rth** [comment]
Yes, thanks again everybody for contributions and discussions!
