### ISSUE TITLE
Compatibility with numpy 1.10.1

### ISSUE THREAD

**Issue by DanHickstein** [PyAbel/PyAbel#51]
Numpy 1.10 apparently has stricter rules for casting floats as integers:
https://github.com/scikit-learn/scikit-learn/issues/5397

This causes an error with PyAbel as well, specifically for the ``example_hansenlaw.py``.

I think that we just need to specifically cast the numbers to the correct types, but I think I recall there is something weird going on with a half-integer origin in the case of the hansen-law transform? @stggh 

Here is the output from trying to run the example:

```
Daniels-MacBook-Pro-3:examples danhickstein$ python example_hansenlaw.py
Loading data/O2-ANU1024.txt.bz2
image size 1024x1024
Performing Hansen and Law inverse Abel transform:
HL: Calculating inverse Abel transform:  image size 1024x1024
HL: Individual quadrants
HL: Calculating inverse Abel transform ...
0.29 seconds
Generating speed distribution ...
Traceback (most recent call last):
  File "example_hansenlaw.py", line 52, in <module>
    recon, speeds = iabel_hansenlaw (im,quad=(False,False,False,False),verbose=True)
  File "/Users/danhickstein/Documents/PyAbel-master/abel/hansenlaw.py", line 210, in iabel_hansenlaw
    speeds = calculate_speeds(recon,origin=image_centre)
  File "/Users/danhickstein/Documents/PyAbel-master/abel/tools.py", line 24, in calculate_speeds
    polarIM, ri, thetai = reproject_image_into_polar(IM,origin)
  File "/Users/danhickstein/Documents/PyAbel-master/abel/tools.py", line 145, in reproject_image_into_polar
    x, y = index_coords(data, origin=origin)
  File "/Users/danhickstein/Documents/PyAbel-master/abel/tools.py", line 179, in index_coords
    x -= origin_x
TypeError: Cannot cast ufunc subtract output from dtype('float64') to dtype('int64') with casting rule 'same_kind'
```

Thanks to @ellisje624 for pointing this out.

**Comment by stggh** [comment]
```np.meshgrid(np.arange(nx), np.arange(ny))``` returns integer numpy.arrays for nx, ny integer. 
A possible solution is to convert to float:
```
178,180c178
<     x, y = np.meshgrid(np.arange(nx), np.arange(ny))  # int numpy.array
<     x.astype(float)
<     y.astype(float)
---
>     x, y = np.meshgrid(np.arange(nx), np.arange(ny))
```

**Comment by DanHickstein** [comment]
So, I'm pretty sure that the previous behavior was that the ints were being cast to floats, so I think that we indeed just need to cast the ints to floats explicitly (as you mentioned). The behavior should be identical. 

I think that the following change is the most pleasing to the eye, since no new lines are required:

``x, y = np.meshgrid(np.arange(float(nx)), np.arange(float(ny)))``

**Comment by DanHickstein** [comment]
Fixed!
