### ISSUE TITLE
Implement Hansen-Law forward transform?

### ISSUE THREAD

**Issue by DanHickstein** [PyAbel/PyAbel#55]
Equation 15 of the Hansen and Law paper is the forward Abel transform, and is the analog to the inverse transform in equation 17, which we have implemented in ``abel.iabel_hansenlaw_transform``. The forward version has the potential to be a very efficient forward abel transform, so we should implement it when we get a chance. 

What do you think @stggh?

![image](https://cloud.githubusercontent.com/assets/1107796/11816563/324b8c26-a30e-11e5-9adf-0a68d45a2e46.png)
![image](https://cloud.githubusercontent.com/assets/1107796/11816570/39a37970-a30e-11e5-834c-e19706955f06.png)

**Comment by stggh** [comment]
pushed ```fabel_hasenlaw_transform``` and unit test.  The change from ```iabel...()``` is trivial, to ```Gamma``` and ```gp``` is now just the raw image.  The two functions could easily be combined into one. However, I have not decided on the best way to do this.  The unit tests need tightening.

**Comment by stggh** [comment]
@DanHickstein now combined into a single function/method. Unfortunately, this leaves psuedo ```f/iabel_ ``` function names in order to comply with the naming convention.  It would be nice to employ some sort of function decorator. Not yet  fully tested.

**Comment by DanHickstein** [comment]
Great work! That happened much faster than I expected! :)

If the algorithms are basically identical except for a minor switch, I think that it's fine to have one of the functions, say ``abel.iabel_hansenlaw`` be the "real function" and then have ``abel.fabel_hansenlaw`` just call ``abel.iabel_hansenlaw`` and pass along all of the arguments as well as switching the keyword ``transfrom_type`` from ``transform_type='inverse'`` to ``transform_type='forward'``. Alternatively, we could just call the main function ``abel.hansenlaw`` and have the iabel and fabel methods just call hansenlaw with either the forward or reverse keywords. 

Maybe @rth has an opinion on this.

**Comment by stggh** [comment]
@DanHickstein  I have examined the beautiful ```abel.direct.py``` python code of @rth and will implement the same naming scheme and boolean flag inverse=True/False.

At the moment I am revisiting my persistent nemesis, the output forward (inverse) amplitudes from HL. For the Gaussian function, using  adapted  code from ```test_direct.py/test_forward_direct_gaussian()``` the forward transform agreement is good, apart from scaling factors (in this case N=101, ref. Gauss. is ref.fun x &sigma;&Sqrt;&pi;):

![forward-direct-hansenlaw](https://cloud.githubusercontent.com/assets/10932229/11856538/a249b1ea-a4a5-11e5-812b-7fa8ef36e2ba.png)

**Comment by DhrubajyotiDas** [comment]
@stggh Just to add to the discussion, BASEX also suffers from a similar scaling anomaly (#4 and #17) . What we discovered was that the scaling factor (~1.1122) in BASEX was independent of the functions being inverted, so as a stop-gap, it was hardcoded as a correction. I don't know if we've made any progress since in figuring out where it comes from.

**Comment by stggh** [comment]
Thanks.

**Comment by DanHickstein** [comment]
@DhrubajyotiDas, as far as I know, we still have no idea why BASEX needs the scaling factor. 
@stggh, we found that the HL inverse transform also needs a scaling factor, correct? Did we decide if it's a constant factor and can be hard-coded as a correction?

**Comment by stggh** [comment]
This an interesting question. The amplitude of the transform actually depends on the function.
e.g. the Gaussian function has a &sigma;<sup>2</sup> dependence. This may be understood in terms of the HL derivative term ```gd```. It looks as though the ampitude transform may involve the function area.

**Comment by rth** [comment]
Sorry for not responding earlier. Great work for implementing the forward transform in HansenLaw! I am indeed excited to try this in practical applications! 

@stggh  Regarding the scaling factor in HansenLaw, wasn't it `pi/dr` from [your previous comment](https://github.com/PyAbel/PyAbel/pull/41#issuecomment-163433698), where `dr` is the pixel size (or `delta` as defined in that comment)? That doesn't work for the direct transform?  Also `np.gradient(img)` shouldn't it be normalized by dr (unless you do that somewhere later in the code)?

**Comment by stggh** [comment]
Yes, the scaling appears to be  &pi;/dr for the inverse transform and &pi; x dr for the forward transform. I was confused when testing functions  with ```dr < 1```, since my original code did not pass ```dr``` into the transform function. The gradient  normalization would account ```1/dr``` for the inverse Abel transform (an important observation, thanks). I am not sure about  the factor ```x dr``` required for the forward Abel transform, which has no gradient function. A little more checking, by me, is required.

**Comment by DanHickstein** [comment]
It works!
