### ISSUE TITLE
Implement "Onion Peeling" algorithm

### ISSUE THREAD

**Issue by DanHickstein** [PyAbel/PyAbel#56]
Professor Eric Wells from Augustana University has kindly provided a Matlab implementation of the Onion Peeling (also known as "back projection") algorithm described in his recent paper: 

http://scitation.aip.org/content/aip/journal/rsi/85/11/10.1063/1.4899267 

The algorithm actually originates from this [1996 RSI paper by Bordas et al.](http://dx.doi.org/10.1063/1.1147044), so we should cite both papers in the code and the documentation. 

He said that we could port his algorithm to Python and incorporate it into the PyAbel package if we wish. I tested the Matlab implementation, and it provided sub-second transform times for 1000x1000 pixel images and the results seem to be high-quality. 

I uploaded the matlab code here: https://github.com/PyAbel/PyAbelLegacy/tree/master/onion_peeling

In the future, we should incorporate this into the PyAbel package. 

EDIT: This "onion peeling" method is distinct from the "polar onion peeling" method discussed in https://github.com/PyAbel/PyAbel/issues/30. Polar onion peeling uses a basis set of fairly broad legendre polynomials and cannot resolve very small angular features (I think), whereas the onion peeling algorithm does not require a basis set.

**Comment by DanHickstein** [comment]
I got a preliminary port of this working. The results look pretty reasonable for the O2 test image. 

Inverse abel transform on left, original image on right
![image](https://cloud.githubusercontent.com/assets/1107796/11916956/7198671c-a694-11e5-8c1f-2c0e726b87ab.png)


The code is fairly short. Here is the full working example. I'm not 100% sure what's going on, but basically it's iterating over the column from outside to inside and subtracting the projection of each column from the inner columns. 

Here is the code:
```python
import numpy as np
import matplotlib.pyplot as plt
import time

def init_abel(xc,yc):
    # this seems like it could be vectorized pretty easily
    val1 = np.zeros((xc+1, xc+1))
    val2 = np.zeros((xc+1, yc+1))
    
    for ii in range(0,xc+1): 
        for jj in range(ii, xc+1):
            val1[ii,jj] = np.arcsin((ii+1)/float(jj+1))-np.arcsin((ii)/float(jj+1)) 

    for idist in range(0,xc+1):
        for jdist in range (0,yc+1): 
            val2[idist,jdist] = np.sqrt((idist+1)**2+(jdist+1)**2)/(idist+1)

    return val1,val2


def iabel_onion_peeling(IM,sym_lr=False,sym_ud=False):
    # %%% Abel-inversion algorithm from: Rev. Sci. Instrum. 67, 2257 (1996).
    # %%% info about this implementation:  Rallis et al., Rev. Sci. Instrum. 85, 113105 (2014)
    
    # works only on the left side of an image.
    # i.e., for IM[i,j], the radial coordinate (r) increases with increasing j
    h,w = np.shape(IM)
    
    if w%2==1:  raise ValueError('Image width must be even')

    if np.any(IM<0):
        print 'Image cannot have negative values, setting negative values to zero'
        IM[IM<0] = 0 # cannot have negative values

    # calculate val1 and val2, which are 2D arrays of what appear to be scaling factors
    val1,val2 = init_abel(w,h) 
    
    abel_arr = IM*0 # initialize 2D array for final transform
    rest_arr = IM   # initialize 2D array that will be manipulated during the transform
    vect = np.zeros(h) # initialize a 1D array that is temorarily used to store scaling factors
        
    
    for col_index in range(0,w): # iterate over the columns (x-values) in the slice space 
    
        if col_index%100 == 0: print col_index
        
        idist = w - col_index # this is basically the x-coordinate. or "distance in i direction", I guess
        rest_col = rest_arr[:,col_index]  # a 1D column. This is the piece of the onion we are on.
        normfac  = 1 / val1[idist,idist]
        
        for i in range(0,idist)[::-1]: 
            ic = w - i - 1 
            rest_arr[:,ic] =  rest_arr[:,ic] - rest_col * normfac * val1[i,idist]
            rest_arr[:,ic][rest_arr[:,ic]<0] = 0
            
        for row_index in range(0,h): #for row_index =1:ymax
            jdist = h - row_index
            vect[row_index] = val2[idist,jdist]
        
        abel_arr[:,col_index] = normfac * rest_col * vect.transpose()
    
    return abel_arr

data = np.loadtxt('O2-ANU1024.txt')
h,w  = np.shape(data)
data = data[:h/2]
left = data[:,0:w/2]

result = iabel_onion_peeling(left)
data[:,0:w/2] = result*.2
plt.imshow(data,clim=(0,np.max(data)))

plt.savefig('OnionPeeling.png',dpi=100)

plt.show()
```

**Comment by stggh** [comment]
@DanHickstein great work, your code looks compact and neat.

**Comment by stggh** [comment]
Here is a very **rough** comparison of the 4 inversion methods (direct, onion, hansenlaw, basex) for the O2- data. 
I may not be driving ```iabel_direct()``` correctly, as the speed distribution is similar to that expected from a raw image?

![all](https://cloud.githubusercontent.com/assets/10932229/11923582/de0559c6-a7f9-11e5-8559-21410cde5e7e.png)

NB The apparent image (quadrant) noise is sensitive to the normalization. I choose a point [h2-20:h2,140:160].max()   ~v'=3 on the centre-line  (It may have been better to average)

code:  examples/example_all_O2.py    in my fork

timing on Macbook pro 2.4GHz i5
direct inverse ...
                    0.3 sec
onion inverse ...
                   22.3 sec
hansen law inverse ...
                   0.6 sec
basex inverse ...
                   0.6 sec

**Comment by DanHickstein** [comment]
The Onion Peeling Matlab implementation is sub-second runtime, so I'm not sure why the Python version is so much slower. 

Also, I don't think that the result of the Onion Peeling in correct for object that are not spherical. For example, if I pass a cylindrical gaussian, the result varies in the vertical direction, which is not correct:

Original on right, transform on left:
![image](https://cloud.githubusercontent.com/assets/1107796/11938065/0ed49712-a7bc-11e5-9bc4-f7fb65b288a1.png)

This has something to do with the ``val2`` matrix, which has some dependence on the vertical coordinate. I think that the original authors are assuming VMI images, which have circular features...

**Comment by rth** [comment]
@DanHickstein Great work for implementing this! We can add it under `onion_peeling.py` or something similar..

@stggh Nice comparison! The problem with `iabel_direct` is that it need an array on the interval `[0, r]` on the last axis, unlike HansenLaw that take in an array between `[r, 0]`. Here is the fixed example in a  [gist](https://gist.github.com/rth/6826ef00b7463dd2f469). The results are very similar to HansenLaw & Basex although with a stronger amplification of the noise on the axis I think.
![test](https://cloud.githubusercontent.com/assets/630936/11938710/f6f17f00-a81c-11e5-8cf0-9afdd2761a0b.png)

 It is interesting  that Onion Peeling produces slightly different (smoother?) results as compared to other 3. For the speed well we can always spend time on optimizing this more if needed. Also, Matlab uses a [JIT compiler]( https://hips.seas.harvard.edu/blog/2013/05/13/jit-compilation-in-matlab/) (which would be similar to PyPy in Python), so I guess  it is normal that it is faster in some cases. 
@DanHickstein Yes, but a "cylindrical Gaussian" does have a up/down symmetry so it should work both with transforms that have a spherical symmetry and those that do not, shouldn't it?

**Comment by stggh** [comment]
Excellent.  We should choose a common image/data orientation for ```(f/a)abel_xxx_transform()```.

**Comment by DanHickstein** [comment]
@rth, good point about the JIT compiler! Once we have reliable results from the algorithm, we can try some tricks to speed it up. 

And yes, you are right, it **should** work for a cylindrical gaussian. I am confused why it doesn't. I spent some time trying to figure this out last night, but I still don't quite understand what's going on. The matlab program produces the same result. I've pasted some example code below. The left and right sides of the image should be identical, but they are not.

Also, thanks for sending the link to the paper, it looks really cool, but might take me a few days to digest :). 

@stggh, yes, we should chose a standard orientation for the ``(f/i)abel_xxx_transform()`` methods. It's not too important, since people will most likely be passing a whole image to the ``(f/i)abel_xxx()`` methods, but there is no reason why each "transform" method should not take a standard format. The current convention (taking the "left" side of the image), makes sense from an algorithmic viewpoint (i.e., many of the methods iterate from outside to inside), but I think that having r=0 at low index (i.e., taking the right side of the image) will make more sense to most users. 

Code to test the onion peeling method with a "cylindrical gaussian" function: 

```python
import numpy as np
import matplotlib.pyplot as plt


def init_abel(xc,yc):
    val1 = np.zeros((xc+1, xc+1))
    val2 = np.zeros((xc+1, yc+1))
    
    for ii in range(0,xc+1): 
        for jj in range(ii, xc+1):
            val1[ii,jj] = np.arcsin((ii+1)/float(jj+1))-np.arcsin((ii)/float(jj+1)) 

    for idist in range(0,xc+1):
        for jdist in range (0,yc+1): 
            val2[idist,jdist] = np.sqrt((idist+1)**2+(jdist)**2)/(idist+1)

    return val1,val2
    

def iabel_onion_peeling(IM,sym_lr=False,sym_ud=False):
    # %%% Abel-inversion algorithm from: Rev. Sci. Instrum. 67, 2257 (1996).
    # %%% info about this implementation:  Rallis et al., Rev. Sci. Instrum. 85, 113105 (2014)
    
    # works only on the left side of an image.
    # i.e., for IM[i,j], the radial coordinate (r) increases with increasing j
    h,w = np.shape(IM)
    
    if w%2==1:  raise ValueError('Image width must be even')

    if np.any(IM<0):
        print 'Image cannot have negative values, setting negative values to zero'
        IM[IM<0] = 0 

    # calculate val1 and val2: 2D arrays of what appear to be scaling factors
    val1,val2 = init_abel(w,h) 
    
    abel_arr = IM*0    # initialize 2D array for final transform
    rest_arr = IM      # initialize 2D array that will be manipulated during the transform
    vect = np.zeros(h) # initialize a 1D array that is temorarily used to store scaling factors
    
    for col_index in range(0,w): # iterate over the columns (x-values) in the slice space         
        idist = w - col_index # this is basically the x-coordinate. or "distance in i direction", I guess
        rest_col = rest_arr[:,col_index]  # a 1D column. This is the piece of the onion we are on.
        normfac  = 1 / val1[idist,idist]
        
        for i in range(0,idist)[::-1]: 
            ic = w - i - 1 
            rest_arr[:,ic] =  rest_arr[:,ic] - rest_col * normfac * val1[i,idist]
            rest_arr[:,ic][rest_arr[:,ic]<0] = 0
            
        for row_index in range(0,h): #for row_index =1:ymax
            jdist = h - row_index
            jdist = np.abs(h - row_index)
            vect[row_index] = val2[idist,jdist]
        
        abel_arr[:,col_index] = normfac * rest_col * vect.transpose()
        
    return abel_arr

r = np.linspace(-10,10,512)
height = 512
sigma  = 3
A0     = 1
orig =                          A0 * np.exp(-r**2/sigma**2)  # analytical gaussian
proj = sigma * np.sqrt(np.pi) * A0 * np.exp(-r**2/sigma**2) # analytical projection

PROJ = np.tile(proj, (height, 1))
ORIG = np.tile(orig, (height, 1))

h,w = np.shape(PROJ)
left = np.copy(PROJ[:,0:w/2])

result = iabel_onion_peeling(left)
ORIG[:,0:w/2] = result*0.05
plt.imshow(ORIG)
plt.show()
```

left is onion-peeling transform, right is analytical. 
![image](https://cloud.githubusercontent.com/assets/1107796/11983235/1ff4bcac-a956-11e5-9ba0-da4657818192.png)

**Comment by stggh** [comment]
@rth  @DanHickstein  ```but I think that having r=0 at low index (i.e., taking the right side of the image) will make more sense to most users. ```  I agree. In particular, the anisotropy analysis (angular distribution) makes more sense when pictured using the top-right quadrant. I will make the change to the ```hansenlaw``` code.

**Comment by DhrubajyotiDas** [comment]
@DanHickstein @rth regarding the Dasch 1992 paper linked above - I'm currently working on porting the 3-point-Abel inversion technique, developed in that paper, to Python. Students in Prof. Marshall Long's group here at Yale have been using a matlab implementation of that algorithm for quite some time, and I was independently interested in porting it to Python. There are a few typos and other issues in the original paper that need to be handled carefully, so I'll open a new issue to discuss those once the holidays are past. 

Happy holidays to everyone!

**Comment by DanHickstein** [comment]
@DhrubajyotiDas, Yes! That would be great to have an implementation of the 3-point Abel inversion. I keep seeing it discussed in old papers as being a good option, but I have not heard of it being used until now. Feel free to open a brief "placeholder" issue and add more details later.

**Comment by ChrisRallis** [comment]
Hey, I'm the author of that MatLab code.   I didn't realize this projected existed until now.  I spent a lot of time profiling/optimizing it in MatLab for MatLab.  It's not written how I would write it in C or Python.  If there's something I could help with, please let me know.

**Comment by DanHickstein** [comment]
Hi @ChrisRallis, thanks for posting here! 

Any help that you are willing to provide here would be much appreciated! (And I hope that it's okay with you that we have incorporated you code in this way - please let me know if you'd like to see it presented/acknowledged in a certain way.)

Currently, I am struggling to understand exactly how the code operates, and why the transforms that it produces look strange for the "gaussian rod" example posted above. Perhaps you can provide some insight into this. If that involves some changes/re-writes to the code to make it perform better in Python -all the better!

**Comment by ChrisRallis** [comment]
Our back-projection relies on the forward projection from an electrostatic lens that's used in a VMI setup.  I think this is why the result from the gaussian rod has a spherical result.  It's been a while since I read the Bordas RSI paper, but that thoroughly explains the algorithm and assumptions.

**Comment by DanHickstein** [comment]
Yeah, I'm thinking that they are making some assumption specific to the VMI. The section where they discussthe reconstructions is titled: "III. IMAGE PROCESSING IN THE LIMIT OF LARGE
ENERGY RATIO"

In the limit of a large ratio between the extraction field and the electron KE, then I think that the VMI should just be an exact projection of the 3D image. Perhaps they are considering how the electrons are spreading out as they have higher momentum, and they are applying some Jacobian/correction factor due to this? 

Yes, I think that this might be the case judging from the discussion on P2261: 
![image](https://cloud.githubusercontent.com/assets/1107796/13863478/b2dda1b8-ec5f-11e5-91e6-791aaa55ea7b.png)

**Comment by stggh** [comment]
Welcome Chris.

As you may see from this comparison (`examples/example_all_O2.py`), VMI of O2- photodetachment, that there is not too much wrong with onion_peeling method (as coded by @DanHickstein):

![example_all_o2](https://cloud.githubusercontent.com/assets/10932229/13864209/c36ff532-ecf3-11e5-8dc1-d17813934b0c.png)

The `abel/onion.py` has been left behind in the PyAbel updates. I have hacked it slightly to work with the current PyAbel code see [onion_peeling.py](https://gist.github.com/stggh/0540663499c1812fc6ab)

```python
import numpy as np
import abel
import abel.onion_peeling  # had to load directly
import matplotlib.pyplot as plt
IM = np.loadtxt("data/O2-ANU1024.txt.bz2")
Q = abel.tools.symmetry.get_image_quadrants(IM)
AOQ = abel.onion_peeling.onion_peeling_transform(Q[0])
#Warning: abel.onion_peeling_transform() is in early testing and may not produce reasonable results
Qspeed = abel.tools.vmi.angular_integration(AOQ,origin=(0,0))
plt.plot(*Qspeed)
plt.savefig("Onion.png",dpi=100)
plt.show()
```
![onion](https://cloud.githubusercontent.com/assets/10932229/13864439/8f8fb1ec-ecf5-11e5-8117-2c35ac9c3910.png)

**Comment by DanHickstein** [comment]
@stggh, The problem that we are seeing with the onion peeling method is that the intensity as a function of y (the coordinate along the axis of symmetry) doesn't appear quite correct (well, maybe not incorrect, but not the same as the other transform methods.) 

Can you remake the example to show just a comparison of onion with one other transform method? (Say, HansenLaw). I think that we will see a big difference in the 1D speeds distribution.

**Comment by stggh** [comment]
Such a comparison is given in the comparative image above, but here is the one-on-one on a larger scale. NB The image is even, and so not strictly centered, and the speed distributions are normalized.
![hl-onion](https://cloud.githubusercontent.com/assets/10932229/13867143/5242e820-ed10-11e5-892b-d851bc58f15c.png)

If `axis=0` has excess intensity, then it may be better to compare (`axis=1`) slice profiles. I will look at this.  My naive interpretation is that insufficient intensity is un-peeled, i.e. some of the background intensity remains.

The code:
```python
# -*- coding: utf-8 -*-
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

import numpy as np
import abel
import abel.onion_peeling  # had to load directly
import matplotlib.pyplot as plt

# NB this image is even and so not correctly centered
IM = np.loadtxt("data/O2-ANU1024.txt.bz2")

Q = abel.tools.symmetry.get_image_quadrants(IM)
Q0 = Q[0].copy()

iOnionQ0 = abel.onion_peeling.onion_peeling_transform(Q[0])
Qradial, Qspeed = abel.tools.vmi.angular_integration(iOnionQ0,origin=(0,0))

iHLQ0 = abel.hansenlaw.hansenlaw_transform(Q0)
HLradial, HLspeed = abel.tools.vmi.angular_integration(iHLQ0,origin=(0,0))

plt.plot(HLradial, HLspeed/HLspeed[50:].max(), label="hansen-law")
plt.plot(Qradial, Qspeed/Qspeed[50:].max(), label="onion_peeling")
plt.title("Full quadrant speed distributions, normalized")
plt.axis(xmin=50, xmax=450, ymin=-0.2, ymax=1.2)
plt.legend(loc=0)
plt.savefig("HL-Onion.png",dpi=100)
plt.show()
```

**Comment by stggh** [comment]
Here is a 10 row slice from the bottom of the transformed `Q0` image quadrant (`iHLQ0` and `iOnionQ0`).

There is still a substantial background. Beautiful noise characteristics though! @ChrisRallis 

![hlo-10](https://cloud.githubusercontent.com/assets/10932229/13867337/14d3bec2-ed12-11e5-9f62-0ef7d2be888f.png)

**Comment by DanHickstein** [comment]
@stggh, We should not need to normalize the speed distributions between different transform methods if everything is working correctly. Those plots clearly show that there is disagreement between the two methods for the height of the peaks. The onion peeling contains some additional factor that makes the intensities lower at low y-values. The lack of noise at low radius is likely a result of this. (Though the noise looks low at higher values of radius as well, so the method still looks very promising.)

**Comment by stggh** [comment]
Sorry, I misinterpreted what you meant by y-values.  I think the loss off peak intensity may be another `x r` Jacobian factor. Of more concern to me is the extended tail (left side) for each band (transition) and the background. This looks similar to a speed distribution for raw projected image, rather than a transformed image.  You are right about there should be no need to normalize between transforms. I have not checked this fact in detail.

**Comment by DanHickstein** [comment]
> @stggh: I think the loss of peak intensity may be ... 1/r Jacobian factor.

We have a winner!!!  Dividing the intensity of the onion transform by `1/r` provides reasonably results for the cylindrical gaussian example. Interestingly, if I just divide by `r`, where `r = x**2 + y**2` and x and y run from 0->width or height, then there is still a small artifact near zero. However, if I make x and y start at 2, then everything works perfectly. 

Here are the results for an upper-right quadrant of the gaussian-rod example:

![figure_1](https://cloud.githubusercontent.com/assets/1107796/13882159/dc4e5c06-ece9-11e5-8a61-b6914f239481.png)

Here is the code (sorry, legacy spaghetti code, but you can easily incorporate the 1/r factor into the updated code):
https://gist.github.com/DanHickstein/ddcd8168e2210422b8d7

**Comment by stggh** [comment]
@DanHickstein excellent work. I would not have thought to apply the `1/r` factor to both axes.
Here is the test case that I re-ran, assuming I correctly coded the `1/R` factor:
![hl-onion](https://cloud.githubusercontent.com/assets/10932229/13890844/b271cf7c-eda1-11e5-8636-d84f69840e3d.png)
The transition (peak) intensities do indeed match. There remains a background intensity issue. 

It would be better to apply the Jacobian at the correct place within the `onion_peeling.py` code. I am not sure where though ...

I looked through your python code last night. AFAICT it mirrors the original MATLAB code, using some clever python techniques. Impressive. One minor difference (that appears to be of little consequence) is line 85:
```python
            val2[idist, jdist] = np.sqrt((idist+1)**2+(jdist+1)**2)/(idist+1)
```
 cf MATLAB code line 14 
```
 val2(idist,jdist)=sqrt(idist^2+(jdist-1)^2)/idist;
```
so I think the 2nd squared term should be `jdist**2` i.e. 
```python
           val2[idist, jdist] = np.sqrt((idist+1)**2+jdist**2)/(idist+1)
```

**Comment by stggh** [comment]
(I am more awake now) The speed distribution may be corrected using the Jacobian `1/r`.

I removed the tests in the onion code that keep the inversion positive. These may have related to conforming to integer image formats, a trap that the old `basex.exe` code had.  `>=0` values give the impression of better noise, but this is an illusion.

![hl-onion](https://cloud.githubusercontent.com/assets/10932229/13893220/c555ae74-edb0-11e5-84c6-b5b9a92ed2b7.png)

I believe this is about as good as the onion code can give.

**Comment by DanHickstein** [comment]
@stggh, that looks great! 

At one point I tried running the onion peeling algorithm with an odd image size (remove the lines that throw the error) and it seemed to work fine. It would be good if it could work with odd image sizes, because then it would match the rest of the transform methods.

Can you try running with an odd-sized image and see how the result compares? 

Also, we should time both the main function and the init_abel function. And see which one slows things down the most. 

I'm busy for the next few days, so if you have time to make the PR for onion_peeling, please feel free to do so!

**Comment by stggh** [comment]
I was just looking at the `even` image limitation. It's also not required (there is not much onion code left ;-)). Here is the test case for the dribinski sample image (`n=1000`). 


![hl-onion](https://cloud.githubusercontent.com/assets/10932229/13893637/6bf79d3e-edb4-11e5-82e9-ae747a457d2b.png)

code:
```python
# header stuff
:
IM = abel.tools.analytical.sample_image(n=1001)
fIM = abel.Transform(IM, direction="forward", method="hansenlaw").transform

Q = abel.tools.symmetry.get_image_quadrants(fIM)
Q0 = Q[0].copy()

iOnionQ0 = abel.onion_peeling.onion_peeling_transform(Q[0])

iHLQ0 = abel.hansenlaw.hansenlaw_transform(Q0)
HLradial, HLspeed = abel.tools.vmi.angular_integration(iHLQ0,origin=(0,0))

Qradial, Qspeed = abel.tools.vmi.angular_integration(iOnionQ0,origin=(0,0))
Qspeed[1:] /= Qradial[1:]
 :
# plot stuff
```

**Comment by DanHickstein** [comment]
Boom! It works for odd images too! Well that's just great. 

Sounds like PyAbel has gained a new transform method!

Can you still something at the top of onion_peeling.py to indicate that "This algorithm was adapted from the original Matlab implementation, which was created by Chris Rallis and Eric Wells of Augustana University." ...or, whatever acknowledgement that @ChrisRallis sees fit.

**Comment by stggh** [comment]
I added the edit (above) just as you messaged: 
> "I should qualify the odd/even. For an odd image, the quadrant Q0 is still even in width. Making IM odd in the O2- example, produces a very similar result to that given above."   

I believe that the even image requirement may not be necessary.

I will add the attribution.

A good piece of work @DanHickstein

**Comment by DanHickstein** [comment]
>"I should qualify the odd/even. For an odd image, the quadrant Q0 is still even in width. Making IM odd in the O2- example, produces a very similar result to that given above."

I am confused - typically we split an odd image to yield an odd quadrant, since this is what our transform methods want. I am confused that you are saying it's even....

Onion_peeling seems to work for both even and odd quadrants, right?

**Comment by stggh** [comment]
@DanHickstein 

1. one more Q concerning the installation `setup.py` script. 

  What must be added to make `onion_peel` available via `abel.` (sorry, about my terminology)?  At the moment it is not visible (on my systems) and may only be loaded via `import abel.onion_peeling`.

2.  Yes, the onion_peeling appears to work for both even and odd sizes.  

  I was cursorily looking at shapes.  An odd image gets split into two even halves, with quadrants padded.  eg. `w=3` gives two quadrants of size `w=2`.

  The O2- VMI has shape `(1024, 1024)`, after centering `(1024, 1023)`, and quadrant `(512, 512)`

  The `n=1001` dribinski image has `(1001, 1001)`, and quadrant `(501, 501)`
 
  Hmm, the `501` size does not appear right ... I'll investigate.

**Comment by DanHickstein** [comment]
@stggh 

1. You just need add something like:
```python
from . import onion_peeling
```
btw, are you sure we don't want to just call it "onion" or "op" to save some typing?

2. Wait a second, I thought that all of the transform methods demanded an odd-sized image, including HL. How is it running with an even-sized image?

**Comment by stggh** [comment]
We are exactly in typing phase, from above:

>Note the odd-image width is only a requirement to have the grid-center mid pixel. Each quadrant meets this criteria, even though it is even in size.

**Comment by DanHickstein** [comment]
> Edit: Note the odd-image width is only a requirement to have the grid-center mid pixel. Each quadrant meets this criteria, even though it is even in size.

Ah, yes, you are right. Rookie mistake, sorry. 

So, you may want to try comparing the OP method to HL (or analytical) with something that doesn't have very many pixels. Perhaps the gaussian analytical function. This should give us an idea if the method is designed to work with the center mid-pixel.

**Comment by stggh** [comment]
No worries. It is good that we think about these things. 

I will first put together the `onion.py` (happy to drop the 'peeling') PR and then check the other aspects.

**Comment by DanHickstein** [comment]
Awesome. I appreciate it!

**Comment by DanHickstein** [comment]
@stggh added not one, but two onion peeling algorithms! Closing this issue in celebration :)
