### ISSUE TITLE
Include only the asymmetric transform in BASEX?

### ISSUE THREAD

**Issue by DhrubajyotiDas** [PyAbel/PyAbel#65]
With PR #54, BASEX can invert line-of-sight images which do not possess up/down symmetry. As @DanHickstein mentioned [here](https://github.com/PyAbel/PyAbel/pull/54#issuecomment-167258811), this makes the code for the (original) symmetric BASEX transform somewhat redundant. An up/down symmetric inversion ought to be equivalent to taking an image, averaging the top and bottom halves, and passing it through the asymmetric inversion routine. It turns out that this is true, at least for a Gaussian function with some random noise, as can be seen here.

(VS and no VS refer to Vertical Symmetry)

```python

import numpy as np
import matplotlib.pyplot as plt
from abel.basex import BASEX
from abel.analytical import GaussianAnalytical

fig, axes = plt.subplots(nrows = 3, ncols = 3)
fig.set_size_inches(9,9)

axes[0,0].set_title('Original LOS signal')
axes[0,1].set_title('Noisy LOS signal')
axes[0,2].set_title("Up/down averaged LOS signal")
axes[1,0].set_title('Abel inverted signal')
axes[1,1].set_title('With VS')
axes[1,2].set_title('Without VS')

n = 101
n_vert = 51
r_max = 4
sigma = 1

ref = GaussianAnalytical(n, r_max, sigma)
raw_data = np.tile(ref.abel, (n_vert, 1))
noisy_raw_data = np.zeros_like(raw_data)
averaged_raw_data = np.zeros_like(raw_data)
for idx, row in enumerate(raw_data):
    noise = np.random.normal(0,1,n)
    noisy_raw_data[idx] = row + noise/100.0
    
rows = noisy_raw_data.shape[0]

for idx in range(rows):
    averaged_raw_data[idx] = 0.5*(noisy_raw_data[idx] + noisy_raw_data[rows - idx - 1])

recon_vs = BASEX(raw_data, center=(n//2,n_vert//2), n=[n_vert, n], 
                 basis_dir = './', dr = ref.dr, vertical_symmetry=True, verbose=False)

recon_no_vs = BASEX(raw_data, center=(n//2,n_vert//2), n=[n_vert, n], 
                    basis_dir = './', dr = ref.dr, vertical_symmetry=False, verbose=False)

noisyrecon_vs = BASEX(noisy_raw_data, center=(n//2,n_vert//2), n=[n_vert, n], 
                      basis_dir = './', dr = ref.dr, vertical_symmetry=True, verbose=False)

noisyrecon_no_vs = BASEX(noisy_raw_data, center=(n//2,n_vert//2), n=[n_vert, n],
                         basis_dir = './', dr = ref.dr, vertical_symmetry=False, verbose=False)

avgrecon_no_vs = BASEX(averaged_raw_data, center=(n//2,n_vert//2), n=[n_vert, n], 
                       basis_dir = './', dr = ref.dr, vertical_symmetry=False, verbose=False)

axes[0,0].imshow(raw_data, interpolation="None")
axes[0,1].imshow(noisy_raw_data, interpolation="None")
axes[0,2].imshow(averaged_raw_data, interpolation="None")

axes[1,0].imshow(recon_no_vs, interpolation="None")
axes[1,1].imshow(noisyrecon_vs[25:-25], interpolation="None")
axes[1,2].imshow(avgrecon_no_vs, interpolation="None")

axes[2,0].plot(ref.r, recon_vs[recon_vs.shape[0]//2+1], 'b', alpha = 0.5, lw = 1.5, label = "VS")
axes[2,0].plot(ref.r, recon_no_vs[recon_no_vs.shape[0]//2+1], 'r', alpha = 0.5, lw = 1.5, label = "No VS")
axes[2,0].set_title("Row %d" %(recon_no_vs.shape[0]//2+1))

axes[2,1].plot(noisyrecon_vs[25:-25,45], '-')
axes[2,1].set_title("Column 45")
axes[2,2].plot(avgrecon_no_vs[:,45], '-')
axes[2,2].set_title("Column 45")

for x in [0,1,2]: 
    axes[1,x].set_xticks([])
    axes[1,x].set_yticks([])
    axes[2,x].legend(loc = 0)

fig.tight_layout()
```

![symmetric vs avg asymmetric](https://cloud.githubusercontent.com/assets/6530840/12158982/a7052f22-b4ac-11e5-8829-3bbc1f68d72c.png)

I opened this issue to have a place to discuss the ramifications of a change like this, and make sure we are not losing out on anything essential by getting rid of the symmetric transform code. I'd love to get feedback from the rest of the team on this @rth @stggh @DanHickstein.

**Comment by DanHickstein** [comment]
My intuition is that averaging the top/bottom should be extremely similar, though not necessarily identical (as you found here). 

I think that we have a lot to gain by making BASEX work exactly like all of the other transform methods (right side of image*, no vertical symmetry required). There will be less user confusion and the code should be more streamlined if we can pre-process all of the images in the same way regardless of transform. 

Also, I like the idea of not having two sets of nearly identical code. Currently, if we want to improve the basis set generation algorithm, we need to do it twice, once for the symmetric case and once for the asymmetric case. 

I do feel sentimental about the "classic" symmetric BASEX method, but I cannot think of a convincing reason why it should be kept around. What does @rth think?

*Perhaps the horizontal symmetry is a separate discussion.

**Comment by rth** [comment]
I like this idea at the implementation level, because of all the arguments mentioned in @DanHickstein's comment above. I agree that intuitively averaging the up/bottom part should produce a very similar (although possibly not identical) result, and it's good that the tests with a Gaussian confirm it. 

Unifying the interface for different transforms would certainly improve user experience (and simplify development works for us). Since keeping only the asymmetrical transform goes in this direction, maybe we can go ahead with this? If we discover that we missed something with the symmetric BASEX transform, we can always recover it from the git history in the future.

**Comment by DanHickstein** [comment]
Awesome, so I think we are in agreement that BASEX should no longer have vertical symmetry. 

Next order of business: horizontal symmetry. @DhrubajyotiDas, is this indeed possible? Is it worth doing for the sake of standardizing BASEX with the rest of the transform methods?

**Comment by DhrubajyotiDas** [comment]
@DanHickstein I also think that standardizing BASEX to match the other transforms will be useful. Horizontal symmetry is doable in BASEX, in either the easy way or the hard way.

Assuming the raw data is just the first quadrant, i.e., the axis of symmetry is at the left edge of the image,

    |ABCD....

**Easy way**

Mirror the raw data,

    DCBA|ABCD

And pass that to BASEX as usual. This requires minimal coding, and some changes to the wrapper functions and `abel.tools` to do some preprocessing (mirroring, centering etc.) if the user indicates that the raw data is in "quadrant" form (possibly by either not specifying the `center` parameter, or setting `center = 0`). The BASEX output will be `dcba|abcd`, which will be cut in half and the final output will be `|abcd`.

**Hard (or Native) way**

The basis gets are currently generated on `-r_max` to `r_max`. The basis set generation code would need to be modified to calculate the basis sets on `0` to `r_max`. This would require some careful code rewriting. My first instinct is that lines [634](https://github.com/PyAbel/PyAbel/blob/master/abel/basex.py#L634) and [650](https://github.com/PyAbel/PyAbel/blob/master/abel/basex.py#L650) will need to be deleted, and `nbf` will be equal to the width of the image instead of `half the image + 1`. 

Since, I'm assuming, we will want to keep the original BASEX ability to handle images with both quadrants (`DCBA|ABCD`), the code for handling images with just one quadrant (`|ABCD....`) will be additive, and most likely include some code duplication. Given that we are planning on removing the symmetric case from the code because of code duplication, it doesn't make much sense to reintroduce new duplicates.

In my opinion, the easy way is the way to go. The time penalty for generating basis sets for the "doubled" `DCBA|ABCD` image is negligible because that's decided by the number of basis functions, and that is the same for processing `DCBA|ABCD` or `|ABCD`.

Thoughts?

**Comment by DanHickstein** [comment]
Good discussion!

I was thinking that we would just keep the "right side" transform (``|ABCD``) and not have the current left/right symmetric transform that we are currently using. I think that the same argument could be made that it should be nearly identical to just average the images first. 

In the long run, we may need to figure out how to do this as part of the larger process of figuring out how to manipulate the basis sets to work with even images as well as to use broader basis functions. 

So, fine with me to go with the "easy way" for now, but I would like to see the "hard way" implemented in the long run.

**Comment by DhrubajyotiDas** [comment]
#94 resolves this issue.

**Comment by DanHickstein** [comment]
Yup! Thanks for doing this!!
