### ISSUE TITLE
Quadrant slice alignment

### ISSUE THREAD

**Issue by stggh** [PyAbel/PyAbel#70]
The Abel transforms all appear to work well for single quadrant analysis (e.g. `examples/example_all_O2.py`)

Processing the whole image results in broadening of the speed profile structure, suggesting a slight miss-alignment.

I have run a test case that examines a simply 5x5 2D image, and the slice profiles from the BASEX test image `abel.tools.analytical.sample_image_dribisnki()`.  Recall:
```
                 Q1   |   Q0
     IM  =     -------|-------
                 Q2   |   Q3
```

```python
#!/usr/bin/env python 
# -*- coding: utf-8 -*-

from __future__ import division

import numpy as np
import matplotlib.pyplot as plt

from abel.tools.analytical import sample_image_dribinski
from abel.tools.symmetry import get_image_quadrants

# numpy array "image" 5x5
IM = np.arange(5*5).reshape((5,5))

# individual 3x3 quadrants
Q = get_image_quadrants(IM)

# visual
print("IM")
print(IM)

for i, q in enumerate(Q):
   print("\nQ{:d}".format(i))
   print(q)

print("\nall looks good")


# BASEX sample image
print("BASEX sample image, Gaussians at 10, 15, 20, 70, 85 ...")
IM = sample_image_dribinski(n=361)

# 181x181 quadrants
Q0, Q1, Q2, Q3 = get_image_quadrants(IM, reorient=True)
print("Q0.shape = ",Q0.shape)

# horizontal slice profiles do not align
plt.plot(IM[180, 180:], 'k-', lw=3, label="1/2 IM")
plt.plot(Q0[-1, :], 'r-', lw=2, label="Q0")
plt.plot(Q1[-1, :], 'b-', lw=2, label="Q1")
plt.plot(Q2[-1, :], 'g-', label="Q2")
plt.plot(Q3[-1, :], 'y-', label="Q3")
plt.title("Q1 slice does not align")
plt.axis(xmax=30)

plt.legend(fontsize=11)
plt.savefig("quad_check.png", dpi=150)
plt.show()
```
Output:
```python
[Steve:.+PyAbel/examples]$ ./quad_check.py 
IM
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Q0
[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]

Q1
[[ 0  1  2]
 [ 5  6  7]
 [10 11 12]]

Q2
[[10 11 12]
 [15 16 17]
 [20 21 22]]

Q3
[[12 13 14]
 [17 18 19]
 [22 23 24]]

all looks good
BASEX sample image, Gaussians at 10, 15, 20, 70, 85 ...
('Q0.shape = ', (181, 181))
```

However, for the BASEX sample image,  the `Q1` and `Q2` quadrant slices do not align.
![quad_check](https://cloud.githubusercontent.com/assets/10932229/12523893/a7f8f4e6-c1ad-11e5-998f-ad7113a843a5.png)

I am missing something obvious here. The printout `Q1`, `Q2` look fine from the 5x5 test image. Why do the slice profiles not all align for the `n=361` Dribinski sample image?

[OT] I will be in the Snowy Mountains until Tuesday, and may not have good internet access

**Comment by DanHickstein** [comment]
Good catch @stggh!

Sorry for the delayed response. I've started a new job ([here](http://www.nist.gov/pml/div688/grp80/index.cfm), if you're curious) and I've been busy trying to learn a lot of new things.

I think that I may have confused things with my meshgrid suggestion, and now the output of ``sample_image_dribinski()`` is not actually symmetric. 

Also, when you change the parameter ``n``, the sample image is cropped. I think that we actually want to keep the same sample image regardless of the resolution (``n``). With ``n=40`` you can see both that the image is zoomed in and that it's not quite centered (compare the left and right edges):
![image](https://cloud.githubusercontent.com/assets/1107796/12584613/9f7529ac-c405-11e5-9b99-38de0e058fc2.png)

Fortunately, I think that the fix to both is pretty easy. Just replace lines 55-57 in `abel/tools/analytical.py`:
```python
x = np.arange(n)  
n2 = n//2 + n%2
X, Y = np.meshgrid(x-n2, x-n2)
```
with
```python
x = np.linspace(-180,180,n)
X, Y = np.meshgrid(x, x)
```

The key here is that the x and y coordinates should run all the way from -180 to 180 (this is just based on the fact that we were previously using a size of ``n=361``). 

(An an aside, in the previous case, n2 was either 1 (even images) or 2 (odd images) pixels too large. I think that the old code would be symmetric if the line calculating n2 was changed to ``n2 = float(n-1)/2``. However, the above proposed change also keeps the image looking the same at various resolutions, which I think is the preferred behavior.)

**Comment by stggh** [comment]
@DanHickstein, thanks, your in depth analysis has fixed this issue. 

![quad_check](https://cloud.githubusercontent.com/assets/10932229/12594536/b54c984e-c4ca-11e5-9aba-56bd3052d852.png)
Updated `analytical.py` pushed to my `new-branch` fork. I will return the image `origin` parameter later.

Looks as though the apparent broadening for the full image analysis lies elsewhere.

[OT] I am off to the coast for the remainer of this week and, again, may not have much of an internet connection.

@DanHickstein congratulations on your new postdoc positition. There may be less need for PyAbel analysis,  but there will be no question about the correct time.

**Comment by DanHickstein** [comment]
Sounds good @stggh. Can you open a new PR for this as well?
