### ISSUE TITLE
Issue triage meeting for Pyabel v1.0 in February

### ISSUE THREAD

**Issue by rth** [PyAbel/PyAbel#73]
*Actually for clarity copying my previous message in a new issue here.*

@DanHickstein  Congratulations on your new job! Myself I'm also in a bit of a job transition at the moment (leaving the academia), so I will probably not be able to contribute to PyAbel much in the  future beyond some light maintenance. Still, I completely agree that we should  make the final push to get to v1.0 for PyAbel, and there are a number of points I should finish myself  :)
> we should make a final push to get the code documented, cleaned up, and ready for public consumption.  [...] we should get the documentation in working order and make the package look professional. Basically, the 1.0 release. 

@DanHickstein @stggh @DhrubajyotiDas I was thinking that it might be useful to make a short meeting (say 30 min) to go through the open issue together, decide what needs to be done for v1.0 and what each us is willing to work on given his availability. As email (or github messaging) conversation tend to linger, it would it probably be more efficient to just make decisions in a viso-conference (I was thinking Google Hangouts).  

Because of the time difference this could be [a bit tricky](https://www.timeanddate.com/worldclock/meetingtime.html?iso=20160210&p1=195&p2=57&p3=179&p4=75), but essentially something like,
   -  9 AM Canberra time (day after), 3PM Denver CO time, 5PM Eastern Standard Time (EST) and 11PM Paris time could work for all of us, I think.

*Note:* @DanHickstein I can't find the message where you mention the location of your new post-doc, I think it was not far from Texas, right? so in EST time, isn't it? @DhrubajyotiDas I'm not certain if you are in the EST time zone? @stggh Note, that there is a +1 day difference in the date for Australia. 

Here is a poll to decide on the date: http://doodle.com/poll/xahg84847swz252x
Even if 3 out 4 of us can make it, that would already be great.  I will send the Google Hangouts link shortly before (it requires to have a gmail account).   What do you think?

**Comment by DanHickstein** [comment]
Hi @rth, it would be great to chat online! I am flexible regarding the date and time. 

I work at NIST in Boulder, Colorado (very near Denver). Due to obscure government regulations, at work I am only allowed to video-chat with "[Skype for Business](http://www.skype.com/en/business/skype-for-business/)". Fortunately, I think that it's compatible with  regular Skype, so that shouldn't be a problem, it just means that we can't use google hangouts unless we pick a time in the morning or evening when I'm at home.

I think that any of those days you mentioned would be fine.

**Comment by stggh** [comment]
Hmm, such a meeting is doubly tricky for me:

  (1) Hardware
          At work (ANU) I use Linux workstations that have no video capabilities.  I do have a Macbook Pro at my home, which I could bring into the ANU (on my bicycle), but the wifi network is really slow, so I would need to apply for an IP address to gain access to the ANU wired network.

   (2) Software
         I eschew anything Microsoft, simply because I love Linux. I once had a skype account (under the old software/owners) but let it lapse due to lack of use.  I will need to renew/reapply for a skype account.

I would be quite happy to connect while I am at home, so 7am-9am, Wednesday or Thursday (Canberra time) would work, and perhaps, be more convenient for all others. I am also available during the weekend, which may open up @rth's google hangouts.

**Comment by DhrubajyotiDas** [comment]
Hi @rth, @DanHickstein, @stggh,

Apologies for the radio silence. I was pretty occupied with a research project/manuscript draft and couldn't devote any significant amount of time to PyAbel over the past few weeks. I'll be able to get back to the PyAbel things on my plate very soon (in the next few days).

Either Hangouts or Skype is fine with me. I'm on the East Coast, but I have significant time flexibility so feel free to schedule the meeting for whenever, and I'll most likely be able to join. I've updated the doodle poll with my available days.

**Comment by DanHickstein** [comment]
Now that I think about it, I could just use my smartphone for the google hangouts, so nevermind the skype thing. 

Also, I think that you can just call a landline (or mobile) phone from skype or google hangouts, so if we pick a time when @stggh is at work, we could just call his phone (I'd be happy to foot the bill, it's ~2 cents/minute).

**Comment by rth** [comment]
Hello everybody,

I'm happy that we can potentially all make it!

@DanHickstein If you could use your smartphone for google hangouts that would probably the easiest. :) I can confirm that Skype is also a pain to install on Linux (needs a bunch of 32bit dependencies on a 64bit system), although I do have it on my smartphone. 

How about Tuesday 9th (US, Europe) =  Wed 10th (Australia) at 
  -  7.30 AM Canberra time, 1.30 PM Denver CO time, 3.30 PM Eastern Standard Time (EST) and 21.30 PM Paris time

so that Steve would be still home (it you don't mind talking early)?

If everybody is OK with this, I propose we start on  google hangouts first, and if it does not work out, as a backup plan use Skype and call the people who don't have it. BTW, @DanHickstein apparently one can joint a google hangout from Microsoft Outlook which should use the Skype account  http://www.windowscentral.com/outlook-users-can-now-join-hangouts-new-google-plug 

Could you please email me your gmail address, so I can send you the hangout link before the beginning?  My email is listed on my profile https://github.com/rth . Thanks.

**Comment by DanHickstein** [comment]
Yup! This works for me. See you all on Tuesday :)

**Comment by stggh** [comment]
Is there an agenda for tomorrow's hangout meeting, apart from saying "g'day". Off the top of my head I would like to discuss:

1. Code robustness  - we should be confident that our Abel transforms produce the correct result. This requires more comparative real image testing and unit tests.  The inverse Abel transforms for a single `Q0` quadrant appear to be more consistent between methods that a whole image transform.

2. Code development - I plan to write code for:
       

   - image circularization (essential to obtain high-resolution spectra). This is simply comparing angular slice profiles, and scaling the radial coordinate to align the profiles. 

   - the evaluation of the photoelectron spectrum (PES), which is basically speed -> binding energy scaling.

3. Documentation ...

4. Future development of PyAbel - more application examples, your own spectroscopies, (satellite solar occultation me

**Comment by DanHickstein** [comment]
Well, the most important priority is to finally say "g'day" face-to-face! :)

But really, I think that the we should talk about what needs to be done to get PyAbel in a state where it can be easily found, understood, and utilized by the target users. The package has some great capabilities right now, but it would be difficult for most scientists to get going quickly, due to the lack of documentation (both general and comprehensive), as well as some lingering interface inconsistencies. 

We should make a plan for how we can quickly get PyAbel into a position where people can pick it up and use it.

Talk to you soon!

**Comment by rth** [comment]
@stggh Thanks for proposing an agenda!

I agree with @DanHickstein , from my point of view the main goal of this meeting would be to agree on the work necessary to make PyAbel a ready to use package. This does include documentation and code robustness, but also ensuring that the interface is consistent and modular (so additional features can be easily added in the future). So adapting slightly the agenda above, we could do for instance,

   1. Code robustness 
      -  comparison between different implementations
      -  unit tests coverage
   2. Documentation - see how we can distribute work that needs to be done there
   3. Next v0.7 release
     - quickly go together through all currently open issues, decide how critical it is for this release, and assign the person who would like to do it (if we keep the issue under the 0.7 milestone)
     -  see if anything else needs to be done (interface changes, naming convention, etc)
   4. Discuss other points that you would like to work on for v0.7 or v0.8. Future development of PyAbel.

**Comment by DanHickstein** [comment]
It was great meeting with all of you! I am excited about the improvements that we are making. 

I'm going to close this issue.
