### ISSUE TITLE
Importing PyAbel

### ISSUE THREAD

**Issue by DanHickstein** [PyAbel/PyAbel#74]
When pyabel is imported using `import abel`, none of the transform methods are imported. Is this intentional, or should we include these imports in the `__init__.py` file? 

When numpy of scipy is imported, basically all of the functions are automatically imported. I think that scipy leaves out a few packages to keep the import fast. But, I doubt that the PyAbel package would slow things down even if the whole thing was imported. 

Here is the autofill from iPython to emphasize this point:
```python
In [1]: import abel

In [2]: abel.
abel.absolute_import   abel.io                abel.math              abel.rst               abel.unicode_literals
abel.division          abel.lib.rst           abel.print_function    abel.tools
```

**Comment by stggh** [comment]
Good point. At some stage I commented out `from . import basex` since the other methods were not included. All makes sense now. Yes, I agree, the methods should all be imported.

**Comment by DanHickstein** [comment]
On a related note, why, in `abel/__init__.py`, do we use
```python
from .tools import io
from .tools import math
```
I think that this causes some problems with Sphinx because it cannot find `abel.io` and `abel.math` (since these files don't exist).

**Comment by stggh** [comment]
Probably, my back hack again. I simply modified `abel/__init__.py` to find `tools.py` and `io.py` in the new `abel/tools` directory, not realizing that `tools/__init__.py` would achieve a better outcome. Sorry!

**Comment by DanHickstein** [comment]
Ah, okay. Those lines can be safely removed then?

**Comment by DanHickstein** [comment]
I attempted to include the following in the `__init.py__` file:
```python
from . import basex
from . import benchmark
from . import direct
from . import hansenlaw
from . import three_point
from . import tools 
```
This imported all of the submodules as we wanted, but it caused the documentation to fail to build. 

@rth, is there a recommended way to get all of the submodules to import when we `import abel`?

**Comment by rth** [comment]
@DanHickstein IMO the most direct/clean way of doing this is as you propose: in `__init__.py` `from . import basex`, etc and `from . import tools`, then in `tools/__init__.py`  state `from . import io`, etc. 
 Now it this breaks the docs, something is wrong with the docs, I will look into it.

**Comment by DanHickstein** [comment]
Oh, false alarm. It works fine!

**Comment by DanHickstein** [comment]
One weird thing, when I import abel and the use the iPython autofill, I see almost all of the packages, except for `tool.io`. This seems strange...
```python
In [3]: abel.tools.
abel.tools.absolute_import   abel.tools.print_function
abel.tools.division          abel.tools.symmetry
abel.tools.math              abel.tools.unicode_literals
abel.tools.polar             abel.tools.vmi
```

**Comment by rth** [comment]
That is strange indeed...

**Comment by DanHickstein** [comment]
It work now, so I'll close this issue.
