### ISSUE TITLE
whole image vs single quadrant transform

### ISSUE THREAD

**Issue by stggh** [PyAbel/PyAbel#76]
This *issue* follows on from a previous # that may have been closed, but I have further information. This is FYI, I will investigate further:

(1) I constructed a function to generate a pseudo O<sup>-</sup> photoelectron spectrum. O<sup>-</sup> photodetachment has well defined fine-structure transition positions and intensity ratios. The spectrum consists of 6 Gaussian transitions, very similar to `abel.tools.analytical.sample_image_dribinski()`. In my new-branch fork, the "_dribinski" name has been dropped, and added as a parameter, `sample_image(n=361, name="dribinski", sigma=2)` and
for O<sup>-</sup> `sample_image(n=1001, name="Ominus", sigma=3, temperature=200)`.

(2) The speed distribution of the raw simulated spectrum agrees pretty well with an experimental measurement, for both the whole image, and single quadrant, from `calculate_speeds()`. Middle panel of figure.

(3) The speed distribution of raw `Q0` quadrant (green line, thickened) -> `fabel_hansenlaw_transform()` -> `iabel_hansenlaw_transform()` (red line) agrees exactly. Right side panel.

(4) There is a persistent issue with the full quadrant analysis which slightly broadens the speed distribution. Blue line right panel.

![simulated_o-pes](https://cloud.githubusercontent.com/assets/10932229/12969462/e76e58c4-d0d4-11e5-93ac-2d11f5a6da4d.png)

**Comment by DanHickstein** [comment]
@stgg, Thanks for making the new sample image! That looks really cool. 

Are you using the `get_` and `put_image_quadrants()` functions? I think that they may cause a one-pixel shift for the left quadrants in the case of a odd-sized image:

```python
In [54]: z = np.zeros((5,5)); z[1,1]=1; z[1,-2]=1; z[-2,1]=1; z[-2,-2]=1; print z
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.]]

In [55]: q = abel.tools.symmetry.get_image_quadrants(z, reorient=True)

In [56]: for quad in q: print quad
[[ 0.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  0.]]
[[ 0.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  0.]]
[[ 0.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  0.]]
[[ 0.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  0.]]

In [57]: r = abel.tools.symmetry.put_image_quadrants(q); print r
[[ 0.  0.  0.  0.  0.]
 [ 1.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 1.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.]]
```

**Comment by stggh** [comment]
Well done @DanHickstein, the bug was that I was trimming the left-half quadrants , before flipping, when the trim should be after the flip:
```python
else:
        # odd size image remove extra row/column added in get_image_quadrant()
        Top    = np.concatenate((np.fliplr(Q[1])[:-1,:-1], Q[0][:-1,:]), axis=1)
        Bottom = np.flipud(np.concatenate((np.fliplr(Q[2])[:,:-1], Q[3]), axis=1))
```

```python
In [2]: z = np.zeros((5,5)); z[1,1]=1; z[1,-2]=1; z[-2,1]=1; z[-2,-2]=1; print z[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.]]

In [4]: q = get_image_quadrants(z, reorient=True)

In [5]: put_image_quadrants(q, odd_size=True)
Out[5]: 
array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

**Comment by stggh** [comment]
Issue closed, solved by @DanHickstein
