### ISSUE TITLE
Online examples

### ISSUE THREAD

**Issue by DanHickstein** [PyAbel/PyAbel#77]
Good news! readthedocs.org [now has numpy, scipy, and matplotlib installed](https://github.com/rtfd/readthedocs.org/issues/896)! 

Not only does this mean that we don't need to bother with the "MOCK_MODULES" nonsense, but it also means that we can include examples and have the plots show up! Check them out:
http://pyabel-dh-fork.readthedocs.org/en/latest/example_direct_gaussian.html
http://pyabel-dh-fork.readthedocs.org/en/latest/example_hansenlaw.html
http://pyabel-dh-fork.readthedocs.org/en/latest/example_O2_PES_PAD.html
http://pyabel-dh-fork.readthedocs.org/en/latest/example_hansenlaw_Xe.html

The one catch is that the examples need to actually run each time we build the docs. So, if we want to feature an example in the documentation, it needs to run pretty fast. Currently, it's only really the basex examples that take a long time. So, we could just run these with smaller images if we want to include them with the docs.

**Comment by rth** [comment]
That's really good news! Thanks for checking that up.

**Comment by DanHickstein** [comment]
Some of the examples are now part of the online docs. I'm going to declare victory on this issue and close it.
