### ISSUE TITLE
GUI interface

### ISSUE THREAD

**Issue by DanHickstein** [PyAbel/PyAbel#81]
In PR https://github.com/PyAbel/PyAbel/pull/72, @stggh introduced a new GUI iterface.

I am excited about this, and the screen shot looks cool. Unfortunately, I got the following error (Mac laptop):

```
Traceback (most recent call last):
  File "/Users/danhickstein/Documents/PyAbel-DH/examples/example_simple_GUI.py", line 31, in <module>
    from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg,\
  File "/Users/danhickstein/Documents/matplotlib-quad/lib/matplotlib/backends/backend_tkagg.py", line 13, in <module>
    import matplotlib.backends.tkagg as tkagg
  File "/Users/danhickstein/Documents/matplotlib-quad/lib/matplotlib/backends/tkagg.py", line 9, in <module>
    from matplotlib.backends import _tkagg
ImportError: cannot import name _tkagg
```

**Comment by stggh** [comment]
Hmm,  I have run the example on a Mac book pro OSX 10.11. There may be an issue with your tkinter/matplotlib installation. Are your able to run this example code, which adds a "quit" button to matplotlib?
http://matplotlib.org/examples/user_interfaces/embedding_in_tk.html

**Comment by rth** [comment]
Yes, it looks like `tk` is not installed   which appears to an optional dependecy of matplotlib (I thought before that it wasn't) see https://stackoverflow.com/questions/13110403/matplotlib-backend-missing-modules-with-underscore. BTW, @DanHickstein  what scientific python distribution are you using on Mac? This path ` /Users/danhickstein/Documents/matplotlib-quad/` looks unusual, did you install `matplotlib` from sources?

**Comment by DanHickstein** [comment]
Whoops, as usual, @rth has found the problem. I was using a hacked version of matplotlib installed from source (in order to use the matplotlib TextBox widget for another project). 

It's fun to play with the different transform methods in the GUI! 

Switching back to the Anaconda python and it works. One issue is that the dropdown menu and texts boxes are not in quite the right place on my screen. And they become misaligned as the window is resized.

**Comment by stggh** [comment]
Button placement is with `.pack()`, the dropdown menu and text boxes are located using `.place(` with relative `(x,y)` coordinates. This was quick and dirty, there will be a better way.
