### ISSUE TITLE
3D renders

### ISSUE THREAD

**Issue by DanHickstein** [PyAbel/PyAbel#86]
Just for fun! @stggh @DhrubajyotiDas @rth @ldes89150 

A cylindrical shell and its forward Abel transform:
![image](https://cloud.githubusercontent.com/assets/1107796/13025765/b6fd12cc-d1cc-11e5-8d2f-c119ce48a863.png)

A cylindrical shell, its forward abel transform (pixelated), the inverse transform in 2D pixelated version, and the slice of the 3D image:
![image](https://cloud.githubusercontent.com/assets/1107796/13025768/c3d9af28-d1cc-11e5-8a83-a8c2cb158a81.png)

**Comment by DhrubajyotiDas** [comment]
Whoa, this is really neat!

**Comment by stggh** [comment]
Beautiful.  What software did you use for the 3D rendering? If python, code please ;-)

**Comment by DanHickstein** [comment]
I made those in Blender: https://www.blender.org/

It's open source and written mostly in Python. You can script it in Python, which is really cool.

It has a pretty steep learning curve, but there are some good tutorials. For some reason, a disproportionately fraction of the tutorial videos are recorded by people with Australian accents, so you may have an easier time than I did. (I could never find the "zed" key on my keyboard!)

**Comment by stggh** [comment]
The blender interface/learning curve has always scared me off. My 3D images, have in the past been created using `mayavi2` using `surf(im, options...)` and `show()`.

**Comment by ldes89150** [comment]
Awesome!! It can be a nice illustration on what PyAbel can do.

**Comment by rth** [comment]
That is very nice!

**Comment by DanHickstein** [comment]
Thanks!

**Comment by DanHickstein** [comment]
![small](https://cloud.githubusercontent.com/assets/1107796/13302896/7c7e74e2-db09-11e5-9683-a8f2c523af94.png)
Adding a smaller version so that I can link to this from the readme

**Comment by DanHickstein** [comment]
This is an image I want to include in the readme. Just posting here to get a hyperlink

![example](https://cloud.githubusercontent.com/assets/1107796/13399143/0883388e-debf-11e5-9068-8879a1828076.png)

**Comment by DanHickstein** [comment]
This is an image that I want to include in the readme. Just posting it here to grab a hyperlink.

![example](https://cloud.githubusercontent.com/assets/1107796/13399210/60c4ab22-debf-11e5-85eb-9311b304aca0.png)

**Comment by DanHickstein** [comment]
![example](https://cloud.githubusercontent.com/assets/1107796/13401302/d89aed7e-dec8-11e5-944f-fcafa1b75328.png)
