### ISSUE TITLE
Remove vertically symmetric BASEX

### ISSUE THREAD

**Issue by DanHickstein** [PyAbel/PyAbel#89]
@DhrubajyotiDas, 

Where are you at with cleaning up basex.py? I am playing with it, and I am not sure if it returns a one-quadrant transform. Also, I think that the symmetric transform code is still there. 

We can get rid of the centering stuff as well.

I will merge a good draft of the `abel.iabel` function here in about an hour, so that should allow you to prune down the basex.py file.

**Comment by DhrubajyotiDas** [comment]
@DanHickstein 

I am getting rid of the symmetric transform code today, and I expect the transition to one-quadrant transform to not take very long as well. I will work on it independently, and make sure it plays well with the `abel.iabel` function when you put it up.

**Comment by DanHickstein** [comment]
Sounds good! Thanks @DhrubajyotiDas!

**Comment by DhrubajyotiDas** [comment]
PR #94 is mostly cleanup of the symmetric code. I am currently working on enabling the single-quadrant functionality.

**Comment by DhrubajyotiDas** [comment]
#94 takes care of this issue.

**Comment by DanHickstein** [comment]
Great work @DhrubajyotiDas!
