### ISSUE TITLE
center of hansenlaw

### ISSUE THREAD

**Issue by ldes89150** [PyAbel/PyAbel#92]
After the last pull request, it seems the center is no longer the central axis of the image.

The symmetric axis is `x=0` now.

@DanHickstein Is this what you want? or just a bug?

**Comment by DanHickstein** [comment]
Yes, the new plan is to have each of the transform methods only deal with a right-side quadrant of the image (center is on the left, x=0 side). Whole images will need to be passes through the abel.iabel interface.
