### ISSUE TITLE
iabel/fabel versus "transform"

### ISSUE THREAD

**Issue by DanHickstein** [PyAbel/PyAbel#96]
Following up on https://github.com/PyAbel/PyAbel/issues/93: do people like the idea of having just one function?
```python
abel.transform(IM,direction='inverse')
abel.transform(IM,direction='forward')

```
rather than
```python
abel.iabel(IM)
abel.fabel(IM)
````

Should we make the same change for the individual transform functions?

It seems like this option would make the code slightly simpler. Of course, we would need to decide what to call the individual transform functions: `abel.basex.basex()` sounds a little bit funny.

@rth, @DhrubajyotiDas, @stggh, @ldes89150

**Comment by stggh** [comment]
[catching up on open issues, will @DhrubajyotiDas synchronize with me on this one, as per #99 ?]

I have no strong feelings either way, provided `function?` returns a parameter list.

I prefer the code/wrapper simplification of the one `abel.transform()` and this simplification should be continued to the individual transform functions. It would save many code lines.

**Comment by DhrubajyotiDas** [comment]
[Synchronization off by a few minutes, @stggh]

So, if I understand the difference between the two options,

```python
abel.transform(IM,direction='inverse')
abel.transform(IM,direction='forward')
```
would specify the transform algorithm (`basex` vs `three_point` vs `hansenlaw` etc) in the function call, whereas with
```python
abel.iabel(IM)
abel.fabel(IM)
```
would have `iabel` and `fabel` instantiated as objects of some sort of `AbelTransform` class, and therefore the transform algorithm and other relevant parameters would be specified when `iabel` and `fabel` are first set up in the user's code?

**Comment by DanHickstein** [comment]
@DhrubajyotiDas, here I was asking about the general interface, if you all preferred a single function or to have two functions, one for the forward transform and one for the reverse.

In reality, we would basically have the same `abel.transform()` function under the hood, but then we would provide the abel.fabel() and abel.iabel() functions that will call the main transform function with `direction='inverse'/'forward'`.

So, either approach would be without classes.

Now that I describe it, it sounds like we are just putting wrappers around our actual code to try to make things slightly easier for the user, but making the code less readable. So, maybe I've finally convinced myself that we should do away with the `iabel/fabel` nomenclature (at least for the overarching `abel.transfom()` function.

What do you guys think about the individual transform methods? Should we get rid of (for example) `abel.hansenlaw.iabel_hansenlaw/fabel_hansenlaw` and replace with a single method (perhaps called `abel.hansenlaw.hansenlaw_transform()` that accepts a `direction='forward'/'inverse'` keyword argument? 

A while ago, @rth and I had decided that the `iabel/fabel` nomenclature was a good idea, but I think that I'm drifting away from this view. Largely, my opinion has changed based on the fact that the two methods that support the forward transform (direct and hansenlaw) are both calling the same function, just with an `inverse=True/False` keyword.

Thoughts on this?

**Comment by stggh** [comment]
>So, if there are no objections, I think that we should keep the abel.transfrom(direction='forward'/'inverse') function the way that it is and not add abel.iabel/fabel methods.

Agreed.

Q2: Yes, remove the `f/iabel_<method>` wrapper, which in general (at least for `hansenlaw`, `direct`) call `abel.<method>.<method>_transform()` in any case. IMO, the old scheme added another layer of indirection and padded/confused the docs.

For consistency the `inverse=True/False` should be replaced with the `direction='forward'/'inverse'` keyword argument (or vice versa)? 

There may be user confusion generated by the whole image transform `abel.transform()` vs the core (or single quadrant) transform `abel.<method>.<method>_transform()`. A more distinguishing name for whole, or the quadrant transform may be required.

**Comment by DanHickstein** [comment]
> A more distinguishing name for whole, or the quadrant transform may be required.

This is a reasonable suggestion, but I can't think of a concise way to communicate it. Maybe `abel.basex.basex_right_side()`? That seems unwieldy. I think that as long as we are clear in the documentation, people shouldn't run into many problems. And if somebody passes the full image to one of the one-quadrant methods, it should go wrong pretty noticeably, so that users will realize that a mistake was made.

Opinions from @rth, @DhrubajyotiDas, and @ldes89150 regarding the use of 'iabel/fabel' nomenclature for the individual transform functions?

**Comment by stggh** [comment]
Perhaps, back to `_core`, `abel.<method>.<method>_core()`?

**Comment by DanHickstein** [comment]
`_core` might work. Maybe `abel.basex.basex_half`?

Other opinions?

**Comment by stggh** [comment]
Following on from the final comment issue #36 (closed)
>import abel
abel.transform(data, direction='forward')
abel.transform(data, direction='inverse')

Note that `direct.py` and `hansenlaw.py` use `inverse=True/False` in the "core" ;-) routines `_abel_transform_wrapper()` and `hansenlaw_transform()` respectively.  The parameter `inverse` should be changed to `direction` for consistency. @rth  `direct.py`. I will take care of `hansenlaw.py`.

@DhrubajyotiDas  `basex.py` and `three_point` only contain code for the `inverse` Abel transform, but, perhaps these could host a dummy 'direction` parameter for call consistency, and future development?

**Comment by DanHickstein** [comment]
Yes, I agree with this. `inverse` should be changed to `direction`, unless there is an argument in favor of keeping `inverse`?

I would also agree that `basex` and `three_point` should accept the dummy direction variable and just raise an exception when it's switched to `'forward'`. That seems like a fairly clear way to indicate to users that the functionality does not exist.

**Comment by DhrubajyotiDas** [comment]
@stggh I'll put in the dummy direction variable in `basex` and `three_point`. I agree your idea makes sense.

**Comment by DanHickstein** [comment]
I think that this conversion is complete. Closing this issue!
