### ISSUE TITLE
int/int in basex

### ISSUE THREAD

**Issue by ldes89150** [PyAbel/PyAbel#99]
@DhrubajyotiDas I think there is a bug at

https://github.com/PyAbel/PyAbel/blob/master/abel/basex.py#L294

```python
val = exp(k2 * (1 + log(l2/k2)) - l2) 
```

It should be 
```
val = exp(k2 * (1 + log(float(l2)/k2)) - l2) 
```

Same issue at
```
Mc_vert[1:, 1:] = np.exp(k2 * (1 + np.log(l2/k2)) - l2)
```

**Comment by stggh** [comment]
@ldes89150 I think that `from __future__ import division` takes care of integer division

**Comment by DhrubajyotiDas** [comment]
@ldes89150 I think the division operation from `__future__` takes care of float division (instead of integer division), so we don't need to say `float(l2)/k2`

```python
In [1]: 3/2
Out[1]: 1

In [2]: from __future__ import division

In [3]: 3/2
Out[3]: 1.5
```

**Comment by DhrubajyotiDas** [comment]
Whoops, @stggh scooped me by 3 seconds.

**Comment by stggh** [comment]
Amazing synchronization on a ~ 2 hour old query!

**Comment by DhrubajyotiDas** [comment]
Indeed!

**Comment by DanHickstein** [comment]
You guys are hilarious! :)

**Comment by ldes89150** [comment]
I see.  Sorry for not noticing that.

**Comment by stggh** [comment]
@ldes89150 don't be discouraged, you will no doubt find many other bugs. Thanks, for taking the trouble to look through the code.
